### ISSUE TITLE
Code coverage generates coverage for relative super directory

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#101]
For some reason, the code coverage shows a coverage for directory "../" that is not part of the repository: https://coveralls.io/github/unicode-org/icu4x?branch=master

I'm not sure if it's a bug in grcov, coveralls, or our github action and I'm not sure how to debug it.

**Comment by zbraniecki** [comment]
@echeran any ideas what may be going on?

**Comment by zbraniecki** [comment]
I performed local `grcov` run and it comes up with an HTML report that doesn't show the `../` directory and looks good. So either our action or coveralls?

**Comment by echeran** [comment]
Based on the strange, deeply-nested path `../../../../../usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/<rustcratenames>/....`, my first guess was that it is coming from the cache action's cache storage directory.  But that can't be the case because #99 is still open.

So my current guess is that this happens regardless due to some quirk with how Coveralls behaves on Github Actions.  Is there a way to configure Coveralls to ignore certain directories?  It would be good to ignore that strange relative path as well as the absolute path prefix `/usr` to be extra sure.

**Comment by echeran** [comment]
Maybe this [issue comment](https://github.com/coverallsapp/github-action/issues/20#issuecomment-585890235) from the `coverallsapp/github-action` repo might work for us?

**Comment by zbraniecki** [comment]
Hmm, I doubt that. We already are using a template var from the previous step there and not an env var.

**Comment by sffc** [comment]
Coveralls says coverage went down in my PR, but it only went down in the crate directory:

https://github.com/unicode-org/icu4x/pull/61#issuecomment-631177184
