### ISSUE TITLE
Add docs to GitHub pages

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#111]

**Comment by echeran** [comment]
@sffc @nciric @zbraniecki 
There are [a few ways to create a Github Pages site](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site).  Since we're creating a _project_ site (not a _user_- or _organization_-level site), the way to setup a site is to create a `gh-pages` branch in a repo.

But if we [do this in `icu4x` itself](https://github.com/echeran/icu4x/runs/809574969?check_suite_focus=true), we get a lot of noise and needless commits.  The [test commit](https://github.com/echeran/icu4x/commit/f8d1dd30090b060699874e3e7cea7a5af39d6bc5) that introduces the new GH Actions workflow (no code) results in a commit to the `gh-pages` branch with a [cumulatively large commit](https://github.com/echeran/icu4x/commit/a333fcf41720d149139e201b8516c301107a114f).

So instead, I think we should create a new repo under `github.com/unicode-org` for ICU4X docs that we can publish to (ex: `icu4x-docs`).  Does that sound reasonable to you?

(I've already tested the [action pushing to a separate repo for doc](https://github.com/echeran/icu4x/runs/809743175?check_suite_focus=true) and it works fine: https://echeran.github.io/icu4x-docs/)

**Comment by zbraniecki** [comment]
yeah, that sounds good to me!

**Comment by sffc** [comment]
ICU also has a separate repo for API docs.

https://github.com/unicode-org/icu-docs/

@srl295

**Comment by echeran** [comment]
FYI, I did a little more thinking and research on this, but I think it still makes sense to keep the currently proposed setup -- the docs are published to a separate repo with commits for each version -- it allows a history of docs to be available.  Some people tag their docs repo's commits to match code repo's version tags.

I also added a condition to make the docs generation only be triggered on changes to master, in contrast to build/test/fmt jobs, which executes for PRs and master.  We don't want in-flight PRs to clobber docs -- we only want docs to reflect the latest version of approved code.

I went ahead created the `unicode-org/icu4x-docs` repo and did all the setup steps (added an initial commit to the `gh-pages` branch, enables Github Pages in the repo settings, and added the public/private key pair to `icu4x-docs` Deploy Keys and `icu4x` secrets repo settings).
