### ISSUE TITLE
Consider using usize in the runtime computation steps in CPT

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1129]
We should store u32, but use usize for runtime calculations.

**Comment by echeran** [comment]
Just as an FYI, here is a [background on CodePointTrie design and lookups](https://docs.google.com/document/d/1weiKTPjbmfJNctmVVzbtXULABW9l7HWGi7L7DbnpiWE/edit#). For the purposes of this GH issue, "computation" is referring to the code that performs the lookup, which is basically taking the input code point, treating that integer in memory like a bit field, and performing a bunch of bit operations to achieve the effect of: 1) segmenting that bit field into parts, 2) using each part to index into successive levels of the trie, 3) using each value from the previous trie level combined with the next bit field segment to get the index for the next trie level, 4) finally arriving at the index in the last level (the data array) of the element containing the trie's value for the original input code point.

The Rust code at `utils/codepointtrie/src/codepointtrie.rs` is a port of the basic ICU4C/J code, which works since we're operating on data that we export from ICU as well. But these successive lookups mean that we're looking things up in arrays. In ICU, the CodePointTrie array indices are signed 32-bit ints (Java `int`, C++ `int32_t`). 

Given that Rust uses `usize` for indices, there are spots in the code (like [here](https://github.com/unicode-org/icu4x/blob/651f113cdcf85f620b56793f6b5c8b5c865a9a53/utils/codepointtrie/src/codepointtrie.rs#L185), [here](https://github.com/unicode-org/icu4x/blob/651f113cdcf85f620b56793f6b5c8b5c865a9a53/utils/codepointtrie/src/codepointtrie.rs#L200), and [here](https://github.com/unicode-org/icu4x/blob/651f113cdcf85f620b56793f6b5c8b5c865a9a53/utils/codepointtrie/src/codepointtrie.rs#L207)) where maybe the local variables for successive intermediate lookup indices could be `usize` instead of `u32`.

**Comment by sffc** [comment]
Based on @samchen61661's work, we decided that the current behavior is "as designed".
