### ISSUE TITLE
Converging a payload from two different projections

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#1151]
For #519 I'm using the following manual projections to allow for patterns to pattern projection:

```rust
    /// Helper struct used to allow for projection of `DataPayload<DatePatternsV1>` to
    /// `DataPayload<PatternV1>`.
    pub struct PatternFromPatternsV1Marker;

    impl<'data> DataMarker<'data> for PatternFromPatternsV1Marker {
        type Yokeable = PatternV1<'static>;
        type Cart = DatePatternsV1<'data>;
    }
```

Now I have a case where I need to project from a different payload to the same result payload and store that result on `DateTimeFormat`.

This means I need `PatternFromPatternsV1Marker` and `PatternFromSkeletonsV1Marker` and I'd like to end up with a single payload type that wraps `PatternV1`.

How to do that?

**Comment by zbraniecki** [comment]
@Manishearth @sffc

**Comment by Manishearth** [comment]
Honestly I'm not very happy with the concept of RcStruct (which is why we need `Cart` here); I suspect that's the core issue here. It's worth checking if we can avoid needing it.

**Comment by sffc** [comment]
I replied here:

https://github.com/unicode-org/icu4x/issues/1150#issuecomment-935486384

What @Manishearth said is correct.  We can't coalesce the two projections to the same type because we carry a cart around.  This is because we support 3 different ownership models in DataPayload:

1. Fully-owned
2. Borrowed from structured data
3. Borrowed from unstructured data

The "cart" type parameter feeds case 2; it allows the client to supply structured data and borrow from it.

To resolve the issue, we could:

1. **Fix Zibi's case as a one-off** by, e.g., specifying a custom cart type to be used by both `PatternsV1` and `SkeletonsV1` such that they can have a projection into the same type and everyone is happy
2. Decide that option 1 is not worth the tech debt and just clone the pattern from the skeletons as `'static` since the skeletons are a slower code path anyway and may soon be obsolete
3. Remove the structured data variant from DataPayload (and replace it with what? just drop it?)

As stated in the other thread, I suggest we do option 2 for now, and keep this issue to discuss when we have more time and aren't in a crunch.

**Comment by zbraniecki** [comment]
I'm not sure how (2) is solving it. How can I get a static pattern into `DataPayload<'data, PatternFromPatternsV1Marker>`?

**Comment by sffc** [comment]
> So using an enum here just means you have a slightly more complex destructor.

Can we project from Yoke<P1,C1> to Yoke<P2,C2> where C1 can be transformed into C2 (e.g. an enum variant)?
