### ISSUE TITLE
Should we have FromVarULE?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1180]
Part of https://github.com/unicode-org/icu4x/issues/1082

Split from #1179

If we want to support cases where the target type borrows from the VarULE, `FromVarULE` can work ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1bf93bd34bff6a0a96039a3ba9cc2089)):

```rust
trait FromVarULE<'a, U: ?Sized>: 'a {
    fn from_var_ule(ule: &'a U) -> Self;
}

impl FromVarULE<'_, str> for String {
    fn from_var_ule(ule: &str) -> Self {
        ule.to_string()
    }
}

impl<'a> FromVarULE<'a, str> for Cow<'a, str> {
    fn from_var_ule(ule: &'a str) -> Self {
        Cow::Borrowed(ule)
    }
}
```

Thoughts?  Needs input from:

- [x] @zbraniecki 
- [x] @Manishearth

**Comment by Manishearth** [comment]
Yeah so I do want this, but my general thoughts are that this function will basically be called by _users_ not the VZV/ZV APIs, so it's not important to have a _trait_ for it unless we're doing a custom derive (which we should absolutely do eventually). My suggestion to Zibi for now was to implement this as an inherent method on the ULE type (`.as_foo()`, we have `.as_varzerovec()` on VZVULE for example). Happy to have a trait early so that we can document this though; it's personally low-priority for me since it can be done as an inherent method.

**Comment by Manishearth** [comment]
yes! it would need an `index` argument, but yeah that sounds useful

`DecodeFromVarULE`?

We can actually merge `EncodeAs` and `DecodeFrom` but there are types that are encodable but not decodable (e.g. `String` can't be "decoded" as a cheap borrow)

**Comment by sffc** [comment]
FromVarULE is a special case of ZCF: the case when the source (the Yokeable) has no lifetime parameter.

Let's not combine encode/decode like we did with the old AsVarULE.  I prefer smaller traits when possible, and I think it results in a better outcome anyway.

**Comment by sffc** [comment]
Discussion: add FromVarULE as its own trait for now, and see if we can unify it with ZeroCopyFrom later in #1186.

**Comment by Manishearth** [comment]
Related: https://github.com/unicode-org/icu4x/issues/1255 . If we can make that happen first then we won't need a separate trait

**Comment by Manishearth** [comment]
Now that ZCF is simpler I think we should just use ZCF here. It might be worth having the proc macro autogen the impl if asked, though!

**Comment by Manishearth** [comment]
I'm going to close this issue then
