### ISSUE TITLE
Implement core case mapping functionality

### ISSUE THREAD

**Issue by iainireland** [unicode-org/icu4x#1226]
Support for case folding is the biggest missing piece for my work with irregexp. Dumping my thoughts on how we should tackle it:

## Scope

ICU4C provides low-level character/string case mapping code in `common/ucase.h`. Implementing the equivalent functionality in ICU4X seems like a good first step. The CaseMap class in `common/unicode/casemap.h` could be implemented as a follow-up.

## Strategy
`common/ucase.cpp` defines a UCaseProps class, which contains a codepoint trie and several auxiliary data arrays. A single instance, `ucase_props_singleton`, is initialized based on the data in `common/ucase_props_data.h`, which is auto-generated by `tools/unicode/c/genprops/casepropsbuilder.cpp`. The contents of the codepoint trie are a 16-bit value with an assortment of flags and a payload that can either represent the signed delta between a codepoint and its corresponding upper/lowercase version, or an unsigned index into a sidetable of exception data.

The most straight-forward approach is to reproduce that data structure in Rust and expose roughly the same API. We can export the data from ICU4C using a similar approach to unicode properties.

## Survey

I've split up the functionality in `ucase.h` into several categories.

### Simple case folding
These functions are obvious inclusions:
- ucase_tolower / ucase_toupper / ucase_totitle: convert  a char to lower/upper/title case
- ucase_fold: simple case folding for a single char
- ucase_getType: return the type (lower/upper/title/none) of a single char
- ucase_isSoftDotted / ucase_isCaseSensitive: whether a character is soft-dotted/case-sensitive. These have dedicated bits in the trie value, so they're easy to implement.

### Full case folding
Full case folding includes codepoints that map to multiple codepoints and vice versa. This uses an additional sidetable, `unfold`. In theory we could expose a version of this code that does not support full case folding to save memory for users who don't need it; however, the sidetable is currently just a `[u16; 370]`, so it hardly seems worth it.
- ucase_toFullLower / ucase_toFullUpper / ucase_toFullTitle / ucase_toFullFolding: the full case-folding equivalents of the simple case-folding functions above
- ucase_getCaseLocale: This converts a locale string to an enum to be fed into locale-sensitive functions.
- UCaseContext / UCaseContextIterator: These are used to examine surrounding context in cases where that matters for casefolding.

### Case closure
Given a char/string and a set, these functions add all case-mapped equivalents of the input to the set. We will likely want to modify the API to make it more idiomatic.
- ucase_addCaseClosure
- ucase_addStringCaseClosure

### Questionable utility
- FullCaseFoldingIterator: This iterates over all codepoints with more than one codepoint in their full case folding. Not sure what the usecase is.
- ucase_addPropertyStarts: AFAICT, this is used for populating unicode sets. We currently precompute those sets instead.
- LatinCase::*: See question 1 below.

## Questions 
1. **Overlap with Rust std**: `std::char` already provides `to_uppercase()` and `to_lowercase()` (plus a variety of ascii-specific methods that I think make LatinCase obsolete), and it's awkward to duplicate functionality. However, it's not clear that we can build everything we need on top of Rust's stdlib. Furthermore, Rust updates to new versions of the Unicode standard regularly and [does not consider this a breaking change](https://doc.rust-lang.org/std/char/constant.UNICODE_VERSION.html), which could be a problem for users who expect their case mapping to be stable only to see it change when compiling with a more recent Rust compiler.
2. **Data representation**: The representation of data inside UCaseProps is not very Rust-idiomatic: for example, the exceptions data is an array of raw u16 values representing variable-length entries with a header and a variable number of slots. However, it seems space-efficient and fast to access, so it's likely best not to mess with it.

**Comment by sffc** [comment]
A few initial comments:

**APIs:** As with Unicode Properties, our API should favor handing over reference-counted objects wrapping zero-copy data pointers.  The `CaseMap` class achieves this goal.  `CaseMap` is also newer in ICU than the older functions like `ucase_fold`, and it encourages best practices.  Also, the hard part is the algorithm, not the API; implementing either the older function-based APIs or the newer `CaseMap` APIs require roughly the same amount of technical work.  So I would advise that we start (and finish) with `CaseMap`.

**Strings vs chars:** In general, to achieve the best possible i18n behavior, we should favor an API that processes entire strings, rather than one that works code point by code point.  However, we may end up with both APIs.

**Data representation:** I believe we can do with `UCaseProps` what we did with `CodePointTrie`: we take the unstructured ICU data, make sense of it in icuexportdata with a TOML representation, and then use the zerovec constructs to put it in the data provider.

**Comment by iainireland** [comment]
**Strings vs chars** Some use cases (like irregexp, which is my primary motivation for working on this right now) prefer a codepoint-based API. We should provide both. Looking at the code in `ucasemap.cpp`, it looks like the string API uses the char API internally, so I think it makes sense to start with the char API.

**APIs** I agree that the algorithm is the important part. At this point I just want to make sure that the right functionality is available; we can figure out the best way to expose it to the user once that's in place. The design of ICU4X pushes us towards exposing a `CaseMapping` struct that can be returned by a data provider and contains (zero-copy pointers to) a codepoint trie and some auxiliary data arrays. I think that's more or less what you are suggesting? 

** Data representation ** Yeah, that's basically what I'm planning. The question I was raising above is orthogonal to that, though. Describing it again, with a bit more background: in `UCaseProps`, `exceptions` is an array of uint16_t. For codepoints that don't fit a simple pattern, the value we store in the codepoint trie includes an index into that array. The element at that index is a header, which (among other things) has a bit array describing which slots are present, and a flag indicating whether those slots are 16-bit or 32-bit. Depending on that, the next N (or 2N) elements of the `exceptions` array contain the values in those slots. The closure and full mappings slots can also contain additional inline data (and the location of the closure data changes depending on whether full mappings are present). It's a space-efficient representation, but it gives up some type system guarantees. My inclination is to stick with the existing approach to save memory, and maintain the invariant that the data is well-formed by validating it when we parse the toml.

**Comment by iainireland** [comment]
To be more concrete, here's my current data structure:
```rust
pub struct CaseFoldingData(u16);

struct CaseFoldingExceptions<'data> {
    raw: ZeroVec<'data, u16>,
}

pub struct CaseFolding<'data> {
    trie: CodePointTrie<'data, CaseFoldingData>,
    exceptions: CaseFoldingExceptions<'data>,
}
```
I have initial implementations of everything in the "simple case folding" section above, although I haven't hooked up any data yet so it's all untested. I should be able to do case closures using this data, and then I'll have to add one more ZeroVec (`unfold`, in the ICU4C implementation) to handle full case folding.

The CaseFolding struct would then be handed out as a payload.

**Comment by markusicu** [comment]
This is the kind of discussion where a GitHub issue is very clunky because comments accumulate and don't get tracked or resolved... would you mind taking it into a Google doc?

(And yes, I have implemented & still maintain all of this stuff here.)

Briefly: ucase.h and UCaseProps are completely internal to ICU, not public API. As such, they have not gone through any API design scrutiny. They are low-level tools that follow the Unicode spec & data.

There are public APIs in several places. Class CaseMap is the latest & greatest for string case mappings. Otherwise we have related APIs on class UnicodeSet, class UnicodeString and in unicode/ustring.h. The latter has the public functions for simple case mappings/foldings (code point to code point). (And when something is a simple Unicode property, then it's exposed in unicode/uchar.h.)

Some of the issue text says "case folding" when it should use "case mapping". These terms are not synonyms.

ECMAScript regex uses Simple_Case_Folding. ICU UnicodeSet does not yet have a case closure API for that. I am planning to create one, using a subset of the "unfold" data. There is a question of whether to perform a traditional closure, or whether to *replace* items with their `scf` forms, as in the draft proposal for the next ES regex version.

FullCaseFoldingIterator: Internal API only for a unit test, for checking that the case folding data is correct.

LatinCase: Technically redundant / implementation detail. Used for fastpath code for full string lowercase/uppercase mapping.

**Comment by iainireland** [comment]
[Here's a google doc for comments.](https://docs.google.com/document/d/1wHL4uogYJxiV-OrAAgEd0UWWtdvFWFW9g8ExSjZ2iqU/edit?usp=sharing)

I've also renamed the issue to clarify my goal for this issue. Basically, I think step 1 for implementing case mapping in ICU4X is getting a Rust implementation of `ucase.cpp`, and then we can build subsequent code on top of that. I'm not worrying too much about the external API yet.

**Comment by markusicu** [comment]
> Here's a google doc for comments.

Thanks. I added suggestions & comments.

**Comment by iainireland** [comment]
@echeran Some of the design decisions for case mapping are also documented here. Note that some of the details have changed over time; I think I described the changes in the PR comments, but if you are confused ping me and we can sort it out.
