### ISSUE TITLE
Specify Custom Fallbacking for TimeZoneFormat

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#1232]
Depends on #622 

Currently, `FormattedTimeZone` follows hard-coded fallbacking rules according to [UTS-35](https://unicode.org/reports/tr35/tr35-dates.html#dfst-zone):

https://github.com/unicode-org/icu4x/blob/26d779ac767f613aace34a2031d9d474b11c913a/components/datetime/src/format/time_zone.rs#L121-L135

We would like for users to be able to specify custom time-zone fallbacking rules for both stand-alone `TimeZoneFormat` and for `ZonedDateTimeFormat`. 

I would imagine that this API could take a slice of enums that will be defined in #622 to specify a custom fallbacking order, and that the current fallbacking behavior could be encapsulated as constants that would be used if the user-provided slice is empty. 

That is, if the user provides a custom fallback strategy, use that, otherwise use the UTS-35 fallbacking constants. 

Note that this will affect that data loading strategy dynamically, which is currently also hard-coded according to UTS-35:

https://github.com/unicode-org/icu4x/blob/9aaf98424fed0a14f37ce6f8962229967eb0a77a/components/datetime/src/time_zone.rs#L187-L207

**Comment by sapriyag** [comment]
@samchen61661 can work on this next.

**Comment by nordzilla** [comment]
# Discussion

---

### Background Info

In #622 we introduce an enum of configuration options for stand-alone TimeZoneFormat:

```rust
/// A config enum for initializing TimeZoneFormat.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TimeZoneFormatConfig {
    GenericNonLocationLong,                     // Pacific Time
    GenericNonLocationShort,                    // PT
    GenericLocation,                            // Los Angeles Time
    SpecificNonLocationLong,                    // Pacific Standard Time
    SpecificNonLocationShort,                   // PDT
    LocalizedGMT,                               // GMT-07:00
    Iso8601(IsoFormat, IsoMinutes, IsoSeconds), // -07:00
} 
```
And `TimeZoneFormat` now has the following public constructor:

```rust
    pub fn try_from_config<L, ZP>(                                                                                  
        locale: L,
        config: TimeZoneFormatConfig,
        zone_provider: &ZP,
    ) -> Result<Self, DateTimeFormatError>
```

Currently, these formatting options have hard-coded fallback chains that correspond to the UTS-35 spec, but we want to do something more robust: we want to allow users to specify a custom chain of fallbacks that best fits their use case.

---

### Possible Solutions

#### Solution 1: Slice of `TimeZoneFormatConfig`.

We could allow the constructor to take a slice of config enums to specify the order in which fallbacks should happen. For example:

**Definion**
```rust
    pub fn try_from_config<L, ZP>(                                                                                  
        locale: L,
        config: TimeZoneFormatConfig,
        fallbacks: &[TimeZoneFormatConfig],
        zone_provider: &ZP,
    ) -> Result<Self, DateTimeFormatError>
```

**Usage**
```rust
let tzf = TimeZoneFromat::try_from_config(
    locale,
    TimeZoneFormatConfig::GenericLocation
    [
        TimeZoneFormatConfig::SpecificNonLocationLong,
        TimeZoneFormatConfig::GenericNonLocationLong,
        TimeZoneFormatConfig::Iso8601(
            IsoFormat::UtcExtended,
            IsoMinutes::Required,
            IsoSeconds::Optional,
        ),
    ],
    provider,
);  
```
---

In the above usage, the `TimeZoneFormat` will first try `GenericLocation` format. If localized data is unavailable for this format, it will fall back to `SpecificNonLocationLong` format, then to `GenericLocationLong` format, and finally to `Iso8601` format. 

**pros**
* Robust
* User friendly
* Supports any combination of fallbacks
* Easy to implement.

**cons**
* May not be able to trigger dead-code elimination.
* Allows users to create redundant or sub-optimal fallback chains.

---

#### Solution 2: Pre-defined constants

Create some sort of pre-defined enum where each variant points to a constant set of fallback options. 

```rust
pub enum TimeZoneFormatFallback {
    LocalizedGmt,
    GenericLocation,
    Iso8601BasicWithMinutes,
    Iso8601ExtendedWithMinutes,
    GenericNonLocationLongThenShort,
    SpecificNonLocationLongThenShort,
    // ...
    // various others and
    // combinations of the above?
    // ...
}

pub static LOCALIZED_GMT_FALLBACK: &[TimeZoneFormatConfig] = &[
    TimeZoneFormatConfig::LocalizedGmt,
];

pub static GENERIC_LOCATION_FALLBACK: &[TimeZoneFormatConfig] = &[
    TimeZoneFormatConfig::GenericLocation,
],

pub static ISO8601_BASIC_WITH_MINUTES_FALLBACK: &[TimeZoneFormatConfig] = &[
    TimeZoneFormatConfig::Iso8601(IsoFormat::Basic, IsoMinutes::Required, IsoSeconds::Optional),
],

...
```

**Definion**
```rust
    pub fn try_from_config<L, ZP>(                                                                                  
        locale: L,
        config: TimeZoneFormatConfig,
        fallback: TimeZoneFormatFallback,
        zone_provider: &ZP,
    ) -> Result<Self, DateTimeFormatError>
```

**Usage**
```rust
let tzf = TimeZoneFromat::try_from_config(
    locale,
    TimeZoneFormatConfig::SpecificNonLocationLong,
    TimeZoneFormatFallback::GenericNonLocationLongThenShort,
    provider,
);  
```

---

In the above usage, users would provide only a single enum that corresponds to a pre-defined fallback chain. 

**pros**
* Dead code elimination should be able to determine exactly which enum is present.

**cons**
* Users must use pre-defined fallback chains.
* This enum could get big and difficult to document clearly. 
* Adding a new fallback chain will require version bump.

---

#### Solution 3: Any other ideas?

**Comment by sffc** [comment]
- @sffc - It can be a non-exhaustive enum to remove the third con of option 2
- @sffc - Option 2 basically means that we define a set of fallbacks that make sense, instead of the user constructing something that doens't make sense
- @sffc - Another option for ultimate flexibility is to just make the TZFs return error codes or empty options when they don't have data for one specific format
- @nordzilla - That's an interesting idea that seems to have the flexibility of option 1
- @samchen61661 - The problem with option 2 is that we have to maintain this enum. With option 1 we would need some runtime checks like removing duplicates.

@nordzilla to sketch out option 3.

**Comment by nordzilla** [comment]
Exploring `Option3` from the discussion above. 

Currently, `TimeZoneFormat` always has a final fallback to localized GMT format, which is always available, so the `format()` function and related functions are infallible with regard to the available data, since something will always be formatted in the end.

Based on the discussion, `Option3` would be to let stand-alone `TimeZoneFormat`'s `format()` operation be fallible based on the data it has available.

The idea then would be that each `TimeZoneFormat` object is responsible for only one style of formatting, and users of ICU4X would construct multiple `TimeZoneFormat` objects that can be chained together with any precedence.

For example,

```rust
 let [tzf1, tzf2, tzf3] = [
    TimeZoneFormat::try_from_config(locale, TimeZoneFormatConfig::GenericLocation, &provider)?,
    TimeZoneFormat::try_from_config(locale, TimeZoneFormatConfig::GenericNonLocationLong, &provider)?,
    TimeZoneFormat::try_from_config(locale, TimeZoneFormatConfig::LocalizedGmt, &provider)?,
];
    
let formatted = tzf1.format(...)
    .or_else(|| tzf2.format(...))
    .or_else(|| tzf3.format(...))?;
```

**pros**
* This is maximally configurable: users can use any combination they want, in any order. 
* Should not have any issues with dead-code elimination.

**cons**
* Syntax is a bit verbose.
* Every formatting function will become fallible, even when it doesn't need to be, such as with localized GMT format.
* Formats that require overlapping data (such as two formats that need exemplar cities) may end up loading that data twice. 
* There is no clean way to specify default fallbacks, or pre-defined fallbacks.

Questions:

Do we ever intend to allow custom fallbacking in `ZonedDateTimeFormat`, or will this strictly be for stand-alone `TimeZoneFormat`?

**Comment by sffc** [comment]
> Every formatting function will become fallible, even when it doesn't need to be, such as with localized GMT format.

I think we can get around this problem with a bit of API design work.  For example, I see this as being two different kinds of TimeZoneFormat: one that performs exactly one type of formatting and is fallible, and one that falls back between multiple types of formatting and always ends up with GMT at the end.  In other words, there is a "low level" and a "high level" TimeZoneFormat.  The high-level TimeZoneFormat can be composed of multiple low-level ones.  This is a design pattern I want to adopt more broadly in ICU4X.

> There is no clean way to specify default fallbacks, or pre-defined fallbacks.

The "clean way" can be to have these settable in the options bag for the high-level TimeZoneFormat.

> Formats that require overlapping data (such as two formats that need exemplar cities) may end up loading that data twice.

This is a good observation.  The severity of the problem is reduced by the fact that we use zero-copy data (or will soon), but there is still duplicated work in the data provider.  If this option looks promising otherwise, I would like to set this aside as a premature optimization that we could perhaps improve later by doing something clever in the data provider.

**Comment by sffc** [comment]
Two thoughts.

**On data structure:** Given that we already have some precedent for `smallvec` (in FormattedDecimal), I think using `smallvec` here is going to be fine.  The concern about the size of TimeZoneFormat is valid, but I would point out that these bytes will need to be allocated *somewhere*, either on the stack or the heap.  If using a `Vec`, we may waste even more space, since we don't always have direct control over how `Vec` does its memory management.

**On API choices:** Here's another idea. I'd like to see if we could avoid publicly exposing `TimeZoneFormatUnit`, since it seems probable that we may want to have the ability to continue to optimize TimeZoneFormat since it is hot code that changes a lot based on world events.  Here's a possible approach:

```rust
impl TimeZoneFormat {
    pub fn load_generic_non_location_long(&mut self) -> Result<(), TimeZoneFormatError>;
    pub fn load_generic_non_location_short(&mut self) -> Result<(), TimeZoneFormatError>;
    pub fn load_generic_location(&mut self) -> Result<(), TimeZoneFormatError>;
    // ...
}
```

Internally, these methods could construct a `TimeZoneFormatUnit` and append it to the fallback list.  With these methods, we could tweak the internals at a future time; for example, perhaps we want to tweak the way we handle data loading, or perhaps we need to introduce multiple types of `TimeZoneFormatUnit` for different types of algorithms.  Code size is handled by the fact that methods not being called by the client are easy to DCE.

**Comment by nordzilla** [comment]
> Here's another idea. I'd like to see if we could avoid publicly exposing `TimeZoneFormatUnit`

I agree that this would be good. It's also somewhat builder-pattern-esque which is well-liked in the Rust community. 

In that regard, I might suggest changing the `Result` to return a `Self` type on success (either `Self` or `&mut Self` depending on how we want it to be invoked) so that it could be chained with the `?` operator.

```rust
time_zone_format
    .load_generic_non_location_long()?
    .load_generic_location()?
    .load_iso8601()?;
```

But I'm otherwise on-board with that plan. 

@samchen61661 thoughts?

**Comment by samchen61661** [comment]
That sounds like a good plan! 

IIRC, we want to improve the dead-code elimination and avoid using heap in ICU4X. So in the fourth solution:
- For dead-code elimination: It uses chained APIs instead of a list of TimeZoneFormatUnit instances to determine the fallback orders. So we can know the dead-code during compile. Meanwhile, we are able to control the TimeZoneFormatUnit instances entirely.
- For avoid using heap in ICU4X: We still need to use vector to maintain the fallback order. But we can use `smallvec` so that its size is known and it can live in the stack although it is not space efficient.

Is it correct?
