### ISSUE TITLE
Add Fixed Decimal Type

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#125]
I have the workings of a FixedDecimal type [in my fork](https://github.com/sffc/omnicu/tree/decimal), and I realized today that it may be useful to pull this out into its own PR so it can also be leveraged by @zbraniecki's work on PluralRules.

The data type supports the following features important for both number formatting and plural selection:

- Decimal digits represented in a list-like structure for easy scaling by powers of 10 and formatting to a string
- Support for both leading and trailing zeros
- Support for an exponent field, representing an exponent in scientific or compact notation

I don't know exactly what to name this type.  Ideas:

- Decimal
- FixedDecimal
- FormattableDecimal
- FormattedDecimal
- DecimalNumber
- DecimalDigits
- DecimalQuantity (this is the internal name used by ICU4C/ICU4J since ICU 60)
- DigitList (a class used in ICU4J prior to ICU 60)
- VisibleDigitsWithExponent (a class used in ICU4C prior to ICU 60)

I also don't know what crate to use.  I think maybe I'll make a new independent crate.  What should it be named?

- `icu_decimal`
- `icu_fixed_decimal`
- `icu_math`
- `icu_number_types`

**Comment by zbraniecki** [comment]
I have little experience with lingo around this area, but I like `FixedDecimal` or `DecimalNumber` or `FormattedDecimal`.

`Decimal` sounds a bit generic.
`FormattableDecimal` sounds like a struct that has methods that allow it to be formatted, while I believe the struct will hold an already formatted information.
`DecimalDigits` and `DigitList`  feel like a list of digits, rather than a number.
`DecimalQuantity` doesn't match anything I would understand :)
`VisibleDigitsWithExponent` is very descriptive but long, and unless we expect to have multiple different similar types that we have to differentiate by exact part of name, I don't think its necessary.

As for name, I suggested to start `components/number` and have it there. My assumption is that any crate that will want to use `FixedDecimal` will depend on `number`.
If that assumption is not warrant, then `components/decimal` or `components/types` or `components/math` sound good.
I don't know how much more is there to distribute to such crates except of this one struct.

**Comment by zbraniecki** [comment]
@Manishearth @hsivonen

**Comment by Manishearth** [comment]
I don't have strong opinions on this in any direction.
