### ISSUE TITLE
Naming for GeneralCategory

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1296]
From [TR 44](https://unicode.org/reports/tr44/#General_Category_Values):

> General_Category values in the table highlighted in light blue (LC, L, M, N, P, S, Z, C) stand for groupings of related General_Category values.

@markusicu suggested we change what we currently call "GeneralSubcategory" to "GeneralCategory", and "GeneralCategory" to "GeneralCategoryGroup".

Needs approval from:

- [x] @echeran 
- [x] @iainireland

**Comment by echeran** [comment]
I was thinking something similar before, but I was convinced otherwise by the same sentence. The first part of the sentence reads "General_Category values in the table highlighted in light blue (LC, L, M, N, P, S, Z, C)".  However, the second part of the sentence was interpreted as stating that these are groupings -- special cases -- and should not be considered like the other 30 stable simple property values.

Currently, our property value getter API for `General_Category` looks like:
```rust
pub fn get_general_category<'data, D: ?Sized>(
    provider: &D
) -> Result<DataPayload<'data, UnicodePropertyMapV1Marker<GeneralSubcategory>>, PropertiesError> 
where
    D: DataProvider<'data, UnicodePropertyMapV1Marker<GeneralSubcategory>> + ?Sized, 
```

What some people find confusing is that we pull from the `gc` CodePointTrie, so the function name is appropriate -- `get_general_category`, but the return type property enum name is `GeneralSubcategory`.

I think we can have APIs to return a UnicodeSet for a `GeneralCategoryGroup` enum just as well, and predicate functions to check whether a code point's gc property value matches a particular GeneralCategoryGroup mask/bitset.

So I would be okay with the proposed change.
