### ISSUE TITLE
One big crate or many small crates?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#13]
We've agreed to start out with a monorepo.  However, the question remains about whether we ship artifacts as one large crate or many small crates.

**Comment by zbraniecki** [comment]
Why not both?

Rust handles really well an ecosystem where we release `icu-locale`, `icu-langneg`, `icu-datetime` etc. and at the same time we can release `omnicu` which will be an umbrella package linking all of them together.

**Comment by sffc** [comment]
If we release many small crates, we face interesting questions about dependencies against internal libraries.

For example, if crate A (like `icu-datetime`) depends on crate B (like `icu-number`), then Crate B needs to expose additional APIs that crate A can use, even if those are APIs that we don't want B's clients to use directly.

Also, what happens if your app depends on both crate A and B directly, but crate A requires a different version of crate B?  Do you get crate B compiled twice, increasing code size?

**Comment by Manishearth** [comment]
For doing internal APIs we can use `doc(hidden)`, it's pretty universally recognized that `doc(hidden)` APIs have no stability guarantees.

I'm strongly in the camp of using multiple crates; my experience is that if you don't do this the code has a natural tendency of becoming very interdependent and hard to untangle. Plus typically people tend to avoid internal APIs like that, instead choosing to find an equally good but better segmented option.

> Also, what happens if your app depends on both crate A and B directly, but crate A requires a different version of crate B? Do you get crate B compiled twice, increasing code size?

Yes, but for that we should try and coordinate version numbers somewhat so that this rarely happens. Note that this is also possible with a single crate, when transitive dependencies are involved. The rust community typically tries to avoid this and is welcoming of patches that get rid of dependency dupliciation.

**Comment by nciric** [comment]
Should we call this issue closed given #18 discussion? We are going to have 1 workspace with numerous sub-packages/crates.

The final question (that can be resolved later) is whether we deploy the whole library under one crate.

**Comment by Manishearth** [comment]
We can have a shim omnicu library that has lots of cargo features reexporting types from individual libraries of the form omnicu-foo

**Comment by sffc** [comment]
Let's document the decision and then close the issue.

**Comment by sffc** [comment]
This should be documented as part of the Rust style guide (#12).

**Comment by zbraniecki** [comment]
I think this is done. We have a solid understanding on how we're going to work and individual crates vs. `icu` package.
