### ISSUE TITLE
Figure out plan for constructing DateTimeFormat for different calendars

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1316]
Part of https://github.com/unicode-org/icu4x/issues/1115

The status quo of calendar support is that:

 - We support `Date<C>` for different `Calendar`s `C` (there's an `AsCalendar` trait in there but we can mostly ignore it). Dates are strongly typed.
  - At _some point_ we would like to add support for `ErasedCalendar` which can contain dates from any calendar. This does not currently exist, but one can imagine it as an enum of calendar values that raises errors when calendars are mixed.
 - DateTimeFormat accepts `DateInput` objects. Currently only `Date<Gregorian>` supports being used as a `DateInput`. Of course, we want to change that
 - DTF data is split by variant; so you have to specify `variant: buddhist` (etc) when loading DTF data
 - `DateTimeFormat::try_new()` loads data at construction time, so it too must specify a variant at construction time. It _can_ load multiple variants at once if desired.

We would like to add support for formatting non gregorian calendars with DTF. Some preexisting requirements are:

 - **Architectural**: We have an existing architectural decision that data loading should be independent of formatting: You should walk into formatting with the appropriate data loaded already.
 - **Performance**: We would strongly prefer to not unconditionally load all calendar data at once

A hopeful requirement this introduces is
 - **i18n**: It should not be easy to accidentally support a single calendar

Reconciling this trifecta is tricky.

## Option 1: Type parameter on DTF (compile time checks)

```rust
struct DateTimeFormat<C: Calendar> {...}

impl<C> DateTimeFormat<C> {
   fn try_new(...) -> Result<Self>
}

trait DateInput<C: Calendar> {
  ...
}
```

DTF is parametrized on the calendar type, so at compile time, one must choose to construct `DateTimeFormat<Gregorian>` or `DateTimeFormat<Buddhist>`. `DateTimeFormat<C>` will only accept `DateInput`s with the same calendar, enforced at compile time.

`DateTimeFormat<ErasedCalendar>` will load all calendar data at once.

If you wish to format values from multiple calendars, you have two options:

 - At compile time: you can construct a DTF for each calendar you're going to be formatting; given that the dates for different calendars have different types anyway
 - At runtime: You can construct a `DTF<Erased>`, which will accept `Date<Erased>` as well as specific calendars like `Date<Buddhist>` (etc).

Note that the naïve way of writing this can lead to code bloat: Given that the calendar type is only needed at construction time, the way to write this would be to write `DTFInner` which has a `try_new()` that takes in a string or enum value for calendar type, and wrap it in a `DTF<C>` that is a thin wrapper. Otherwise Rust is likely to generate multiple copies of the mostly-identical functions.

For `DTF<Erased>` to work, `DTF` will need to be able to store a map of calendar data at once. I do not plan to do this immediately, but it's something that can be done when we add support for erased calendars.

This method does not really leave space open for dynamic data loading though I guess that can be achieved on `DTF<Erased>`.

This method does not help the **i18n** requirement, but I'd argue that folks can write generic code as needed and since the dates are strongly typed anyway at some point they need to pick runtime or compile time calendars.

## Option 2: Runtime option

```rust
struct DateTimeFormat {}

enum CalendarType {
   // This can also be a full enum with variants like Gregorian/Buddhist/etc
   BCP(&'static str),
   All
}

impl DateTimeFormat {
   fn try_new(..., c: CalendarType) -> Result<Self> {}

  // OR

  // This is essentially a fancier way of writing the above function
  // without requiring an additional parameter
  fn try_new<C: Calendar>(...) -> Result<Self> {}
}

trait DateInput {
   const NeededCalendarType: CalendarType;
   ...
}
```

Here we specify the calendar we need at data load time, and DTF will attempt to load this data. If you attempt to format a date that uses a different calendar, DTF will error at runtime.

Similarly to the previous option, if and when we add support for `Erased` calendars and/or `CalendarType::All`, we'll need to have this contain some kind of map from calendar type to loaded data. I do not intend to do this immediately but I want to plan for it.

The nice thing is that this can be extended to support dynamic data loading in a much cleaner way (see below section).

Pros (compared to option 1):
 - More flexible at runtime
 - Allows for dynamic data loading (which helps the **i18n** requirement)
 - 
Cons:
 - Will error at runtime, not compile time

This method does not help the **i18n** requirement much but it gets better with the dynamic data loading extension below.

### Option 2 extension: dynamic data loading

This can work on Option 1 (`impl DateTimeFormat<Erased>`) as well, but it's cleaner with Option 2. We can add dynamic data loading of the form

```rust
impl DateTimeFormat {
   fn load_data_for::<C>(&mut self, data_provider: ...) -> Result<()>;

   // or, for convenience
   fn load_data_for_date::<D: DateInput>(&mut self, d: &D, data_provider: ...) -> Result<()>;
}
```

that allows users to dynamically stuff more data into the DTF as needed.

## Option 3: Give up on a requirement

We can also give up on either the **Architectural** or **Performance** constraints as given above. I'm not super happy with doing this, but it's worth listing as an option. This makes it easy to support the **i18n** requirement since we can either dynamically load data or load all data at once.

Thoughts?

Input requested from:

 - [x] @zbraniecki 
 - [ ] @gregtatum 
 - [ ] @nordzilla 
 - [x] @sffc

**Comment by Manishearth** [comment]
I was initially gunning for the compile time option (Option 1) but after writing this out I think I slightly prefer Option 2 since it does better on all points, and I'm okay with losing a little compile time safety if it means that we have better dynamic data loading in the extension.

**Comment by zbraniecki** [comment]
Thanks for writing this down Manish! I think this is a good intro to the trilema.

I'm using the ignorance-is-bliss perspective of not being pondering over the architectural solution for a while, and looking at it akin to other user preferences.

My first principle here is that calendar is a customization of a date. In other words, there is one moment in time, and calendar is just an abstraction over it.
The moment (e.g. "now") is the same no matter if we then format it to `21st January 2021` or `Rabiʻ II 13, 1443 AH`.

The reason we store it on Date is not because it stores a different anchor in time, but because we need different information and different API logic to operate on it.

In result it does feel like a more complicated version of the question of - there is one hour, do you want to see it in 24h/23h/11h/12h? There is one month in gregorian calendar, do you want to see it as "January" or "01" or "1" or "Jan" or "Styczeń" (polish)?

So far, in such decisions we followed the priority of I18n>Architecture>Performance order.
First, we ensure that our API does not lock user away from ability to see the date in their locale and with their preferences.
Second, we front-load at construction time everything we *may* need to format *any* datetime to those preferences.
Third, we try to minimize how much we load to optimize performance.

From that angle, it seems to me that the ideal solution would be to unfortunately:
1) Ensure that every DTF can format any Calendar
2) Front-load all data required to format any datetime to any calendar according to requested options

This is a much larger decision that for other cases like this tho.
So far, I don't know of any place where options to the constructor of DTF would limit the data we load in a way, that later an input to formatter might require. You can't put DTF options that result in us not loading symbols for a month name and then have a `DateInput` that *requires* month names.

I believe in a few edge cases we have a fallback "if you don't have month name but somehow ended requiring it, show month number".
We can't do that on the scale of "fallback to another calendar" imho.

==========

I'm tempted to fiddle with the *architectural* parameter of enabling lazy-loading, because I believe real-wodl uses will be very heavily skewed to single-calendar for 99% of cases and for *i18n* reasons we'd like to support the remaining 1%.

But I'm afraid we can't, trying to relax it would require `format` to be optionally async and I am cautiously pessimistic we can justify such change for this reasons.

Overall, I feel stuck with this problem and I don't see a clean architectural model yet, and I do not like either of the options Manish presented as an ultimate solution :(

**Comment by Manishearth** [comment]
> My first principle here is that calendar is a customization of a date. In other words, there is one moment in time, and calendar is just an abstraction over it. The moment (e.g. "now") is the same no matter if we then format it to `21st January 2021` or `Rabiʻ II 13, 1443 AH`.

Ah, but it participates in _arithmetic_ differently: and this is why we have `Date<C>` and not `Date`. I don't think we should solely be looking at dates from the perspective of formatting, and we chose strongly typed dates

As I mentioned before, this choice is a preexisting choice that we've made: code dealing with dates _already_ needs to either be generic or select a particular calendar (or eventually, use ErasedCalendar).

**Comment by zbraniecki** [comment]
I understand that, but I wouldn't want to use to bandwagon just because it's there. The decisions around architecture should at least consider a model that ignores sunk cost and fixates on the slice of the problem space.

I believe there are arthmetic differences and they are fundamental to the decision, but from the angle of user experience, there's a moment in time and the user wants to see it formatted in their app.
And they may even want to change the calendar *preference* and see the same moment in time formatted in different calendar without having to restart the app.
Everything else is an implementation detail and limitation set.

**Comment by Manishearth** [comment]
> I understand that, but I wouldn't want to use to bandwagon just because it's there. The decisions around architecture should at least consider a model that ignores sunk cost and fixates on the slice of the problem space.


It's not a sunk cost argument: I mean that there are very strong reasons for making that decision, and we can totally revisit them, but I we have to consider those reasons too.

> And they may even want to change the calendar _preference_ and see the same moment in time formatted in different calendar without having to restart the app.

I think those are use cases for the dynamic data loading option and `ErasedCalendar`. Any case where there's a runtime preference for calendar formatting will probably be one for `DTF<Erased>` or `DTF::try_new::<Erased>()` (which give us the behavior of loading everything at once) or dynamic data loading.

I see the runtime option as having far more performance flexibility, and it basically allows for the pattern of "load all calendars at once" anyway, but it also allows for other patterns.

**Comment by zbraniecki** [comment]
Can you provide a user story of a system that is not a complete edge scenario where "allowing for other patterns" is the correct architectural decision?

**Comment by Manishearth** [comment]
I don't think that question is relevant: I think all of these options "allow for other patterns" (all of them have a "load all patterns" erased option, all of them have dynamic loading extensibility though some are better at that than others).

**Comment by zbraniecki** [comment]
> Note that we already do this for locales! In fact, for locales there's less flexibility, we do not even support the case of "I would like this object to work for multiple locales", you need to make new objects for each locale.

That's a convincing argument to me. We could treat calendars the way we treat locales, except that input is not locale specific, but it may be calendar specific which makes the resolution between constructor and formatter operations fragile.

**Comment by Manishearth** [comment]
Yeah, I think that's a crucial difference here, input is never "locale specific" but dates in our current model _can_ be (they don't have to be! ErasedCalendar will exist), and this is why this issue seems dicier, but I think the similarity between both situations is that _situationally_ you still know what calendars/locales you want to load at _some_ point (usually at runtime).

**Comment by zbraniecki** [comment]
I'm convinced that we can treat locales and calendars similarly, and expect recreation of DTF on calendar change.
I would like the default, most convinient, best documented API and usage to be one that enables that model.

**Comment by Manishearth** [comment]
Seems fair. I think that makes the runtime option the right one, which expects an explicit `load_data_for()` call on calendar changes (Not great, not terrible), and we can document that equally alongside `ErasedCalendar`.

Note that my current plans are not to add `load_data_for()` or `ErasedCalendar` _soon_ (I want to unblock calendar implementations) but we should make those block 1.0.

**Comment by zbraniecki** [comment]
Relevant: https://github.com/tc39/ecma402/issues/623

**Comment by nciric** [comment]
I am leaning towards Option 2:
1. Create specific calendar
2.  Format dates based on that calendar
3. If a date from other calendar is passed in convert it into absolute format (ISO, Gregorian?)

One difference from the original proposal is to not error out but to do conversion. This may hide performance penalty from the developer but they can also alleviate it by manually converting into ISO and passing that around.

**Comment by zbraniecki** [comment]
I second Nebojsa' proposal. `format<I: Into<ISODateInput>>(&self, input: I)` and the only place where you define what calendar the date is formatted to is in constructor.

**Comment by sffc** [comment]
First, some background on how this is handled in ECMA-402 and Temporal.

Temporal has two types of calendars:

1. The ISO-8601 calendar
2. Human-readable calendars (everything other than ISO-8601)

Further, the Intl.DateTimeFormat constructor takes the calendar in its constructor, either directly as an option or implicitly by selecting the calendar based on the locale.  Note that Intl.DateTimeFormat only supports formatting to human calendars; formatting to ISO-8601 is not localized and is therefore not handled by Intl.

The behavior is as follows:

| Temporal Cal | DTF Cal | Behavior |
|---|---|---|
| iso8601 | any | Convert iso8601 to DTF's calendar and format |
| human (e.g. gregory) | same (e.g. gregory) | The date is already in the correct calendar; format it |
| human (e.g. gregory) | different (e.g. buddhist) | Throw an exception: DTF does not have the data |

***Crucially,*** this only works because DTF is capable of converting between calendars.

In ICU4X, I have been advocating to decouple calendrical calculations from core DTF.  I still stand by that advocacy, since it is important for modularity.

However, I could see a world where we have a lower-level DTF that has data for a single calendar, and a higher-level DTF that also includes the calendrical calculations logic.

**Comment by Manishearth** [comment]
> I second Nebojsa' proposal. `format<I: Into<ISODateInput>>(&self, input: I)` and the only place where you define what calendar the date is formatted to is in constructor.


I'm maybe misunderstanding this proposal, but I don't think this works: If we're unconditionally converting to ISO date then the date time formatter is not equipped to get the actual calendar-specific values out: you may need calendar-specific data. `format()` has to take in calendar-specific values.



> 3\. If a date from other calendar is passed in convert it into absolute format (ISO, Gregorian?)

Would this mean that DTF always will load gregorian data and potentially one other calendar? That seems reasonable.

(I don't think there's currently any ISO data in CLDR but we can hack it in if we'd like.

**Comment by Manishearth** [comment]
- (some discussion elided)
 - @sffc : We should have a higher level and lower level API
     - Lower level API: should just be able to format a date with a particular calendar
  - @nciric Seems okay for a generic calendar that you pass in the right calendar type
  - @mihnita as an end user, for the final API: two main situations.
     - (1) i get a list of dates, some in diff calendars: either convert to gregorian, or formatter switches types
        - Totally fine if formatter converts
     - (2) in a document i'm showing the same date in 2 different calendars.
  - @Manishearth Dates are statically typed. one downside of using generics everywhere is that ErasedCalendar won't work with the low level API.
  - @zbraniecki Temporal erroring about mixing calendars was not discussed in 402 (@sffc : discussed in Temporal, should be on 402 agenda though)
  - @sffc i think erased calendar belongs in the higher level API. for lower level one-calendar one-formatter makes sense
  - @mihnita surprised to see ecma throwing on mismatch. i don't think the mental model is "oh this is a different type".
  - @Manishearth:
       - Question 1: should we have high and low level split : Answer seems to mostly be yes
       - Question 2: Should the calendar data be loaded based off of the locale or off of an additional parameter (compile time or runtime)
       - Question 3: Should DTF validate calendar type at runtime or compile time
       - Question 4: If at runtime, how does it error
       - Question 5: How does Erased work: Answer seems to mostly be "lives in higher level magic"

strawman:

```rust
// very low level
pub struct DTF {
   data: Data,
   calendar: CalendarType,
}

impl DTF {
  // ignore calendar on locale or error if it doesn't match
  fn try_new(data provider, locale, ty: CalendarType) -> Result<DTF>
  fn format(&impl DateInput); // panics on bad calendar
}

// extremely thin wrapper (no codesize cost)
pub struct TypedDTF<C> {
   dtf: DTF
}

impl<C> TypedDTF<C> {
  fn try_new(data provider, locale) -> Result<TypedDTF<C>>;
  fn format(d: &impl DateInput<Calendar = C>);
}

// high level (??)

struct MagicalDTF {
  formatters: HashMap<CalendarType, DTF> // NOT TypedDTF
}

impl MagicalDTF {
  fn try_new(locale, data provider, calendars: &[CalendarType]) -> Result<Self>;
  fn load_cal(&mut self cal: CalendarType);
  // can use a separate trait that allows it to accept ErasedCalendar too
  fn format(&impl DateInput) -> Result<(), CalendarNotFoundError>;
}

struct ShanesMagicalDTF {
 dtf: DTF,
 calendar: ErasedCalendar, // for conversions
}

impl ShanesMagicalDTF {
  // figures out calendar type from locale, loads it
  fn try_new(locale, data provider) -> Result<Self>;
  // will convert date to local calendar
  fn format(ISODate);
  fn format_2(&impl DateInput); // must match (panic)
}
```

 - @nciric unsure what ShanesMagical brings compared to lower level DTF
 - @mihnita i like the shanes magical model
 - @sffc adding ErasedCalendar

**Comment by Manishearth** [comment]
Low level implementation at https://github.com/unicode-org/icu4x/pull/1339

**Comment by Manishearth** [comment]
I allowed the PR to close this issue since the goal of this issue was to figure out the low level stuff. If someone wants they should file an issue about the high level APIs or reopen this issue (or ask me to do so).
