### ISSUE TITLE
Add FormattedStringBuilder

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#135]
FormattedStringBuilder is a building block for ICU formatting APIs.  This ticket is to track the addition of this feature to ICU4X.

**Comment by zbraniecki** [comment]
I hope we'll be able to use Rust traits for handling zero-allocation writing like `Formatter`, `Write` and `Display` here.

**Comment by sffc** [comment]
I was just going to implement it as a struct with features including field support (formatToParts) and fast prepend and append.  I'm not a big fan of `Formatter`, `Write`, and `Display` because they pull in a lot of code dependencies.  As long as the things we're returning are shortish strings, I think we can write a FormattedStringBuilder struct that support strings up to a certain length without allocation, and spills over to the heap in the edge cases.

**Comment by robertbastian** [comment]
`FormattedStringBuilder` existed for a while during the implementation of `ListFormatter`, but was then deleted because it's not needed now that `ListFormatter` returns `Writeable`. In #1438 we added formatting/parts logic to `Writeable`, see the [design doc](https://docs.google.com/document/d/1gtyV8uYxTNp0Ti2HoHN-5eK-L-HIed3umVSTWWqfHyY).
