### ISSUE TITLE
Migrate UAX 14 data to DataProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1372]
Currently, UAX 14 data is built using a Python script:

https://github.com/unicode-org/icu4x/blob/main/experimental/segmenter/tools/generate_properties.py

The Python script reads data from the following Unicode property files:

- EastAsianWidth.txt
- LineBreak.txt

It then creates several *.rs files:

- lb_define.rs
- properties_defines.rs
- properties_other.rs
- property_table.rs
- rule_table.rs

Instead of a Python script generating *.rs files, this should be a Rust data transformer generating data structs which can then be serialized to *.json or *.postcard files.

**Comment by sffc** [comment]
I spawned #1376 for my side of the work, and I'll leave this issue for @aethanyc to migrate the Python script to Rust in order to generate the data structs.

**Comment by aethanyc** [comment]
The python script does two things: 
1. generates the state transition table from UAX14 rules. I believe we can migrate it using the `bulid.rs` added in #1273. This is tracked in #758.
2. reads `EastAsianWidth.txt` and `LineBreak.txt`, and generate these two Unicode Properties. I've added them officially in #1280, so we don't need to add data structure to migrate this part. Just use [get_line_break()](https://unicode-org.github.io/icu4x-docs/doc/icu/properties/maps/fn.get_line_break.html) to get code point trie in `build.rs`.

**Comment by sffc** [comment]
The generated Rust files create two tables: `UAX14_RULE_TABLE` and `UAX14_PROPERTY_TABLE`.

To make sure I understand: are you suggesting that we:

1. Remove `UAX14_PROPERTY_TABLE` and replace it with a query at runtime to the two Unicode property CPTs
2. Migrate `UAX14_RULE_TABLE` to a new data struct

**Comment by aethanyc** [comment]
I'd suggest we consider the data provider story #1373 first because `UAX14_RULE_TABLE` and `UAX14_PROPERTY_TABLE` generated by python is roughly the same as `BREAK_STATE_MACHINE_TABLE` and `PROPERTY_TABLE` generated by `build.rs`. In our plan, we eventually want to re-implement UAX14 rules in a toml file rather than in python script (similar to `data/word.toml` for UAX29). If your work involves modifying the python script to emit a new data struct, I would be a bit waste of the effort. 

Would it be easier if we design the new data structure suitable to consume at runtime in `build.rs`, and serialize it into json or postcard? We need your expertise on this.

> 1. Remove UAX14_PROPERTY_TABLE and replace it with a query at runtime to the two Unicode property CPTs

I don't think so. We still need the property tables at runtime. UAX14 or UAX29 rules often involves more than one Unicode property. For example, UAX14 needs East_Asian_Width and Line_Break, so we synthesize the two properties along with UAX14 rules into a pseudo-enumerate-properties or so-called "states" (those defines in `lb_define.rs`). During runtime, we query `UAX14_PROPERTY_TABLE` to map a code point to a "state", and the `UAX14_RULE_TABLE` can determine whether there is a break opportunity between two states.

> Migrate UAX14_RULE_TABLE to a new data struct

Yes, I think this is equivalent to [`break_state_table`](https://github.com/unicode-org/icu4x/blob/1d9ddad75f72a378881526e0fc2cd3ac0f37c6e0/experimental/segmenter/build.rs#L210) in `build.rs`. Instead of [printing the vec in a generated rs file](https://github.com/unicode-org/icu4x/blob/1d9ddad75f72a378881526e0fc2cd3ac0f37c6e0/experimental/segmenter/build.rs#L383-L401), I guess we want to serialize it into json or postcard, and deserialize during runtime.

**Comment by sffc** [comment]
Okay, so we need to keep both UAX14_PROPERTY_TABLE and UAX14_RULE_TABLE for runtime use.

The next step I plan is to make those two tables be backed by ZeroVec in a data struct. For the time being, I will keep pointing to the same Rust data files, but we will want to generate them as data struct (postcard) blobs in icu4x-datagen.

That final step, which I hope you will be able to do, is the one that involves moving the code around between the Python and build.rs files and into a "segmenter transformer".  I'm happy to make this a feature-flagged module in the segmenter crate.  This should expose a DataProvider implementation producing the data struct containing ZeroVecs by reading from the source data files (like TOML).  Then, we plug that into icu4x-datagen, and allow the data pipeline to get the ZeroVecs into the segmenter at runtime.

**Comment by aethanyc** [comment]
@makotokato Do you have cycle to switch line break property table generation to using TOML? I believe it is the first step before we generate data struct (postcard) blobs in icu4x-datagen.
