### ISSUE TITLE
Migrate UAX 29 data to DataProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1373]
Currently, UAX 29 data is built using a build.rs script:

https://github.com/unicode-org/icu4x/blob/main/experimental/segmenter/build.rs

The build.rs script reads from "data/word.toml" as well as from Unicode property testdata (word_break, extended_pictographic, and line_break), generating a new *.rs file named "generated_word_table.rs".

Instead of a build.rs file, this should be a Rust data transformer, and instead of creating a Rust file, it should create a data struct that can be serialized to JSON or Postcard.

**Comment by aethanyc** [comment]
After #1579, the runtime data structure `RuleBreakDataV1` is ready for the rule segmenter.

Here is my approach to this issue.

1. Create a new crate called `icu_provider_segmenter` under `provider/segmenter`, and move toml files (`data/word.toml`, etc.) from segmenter main crate into the new crate. (The segmenter main crate is `no_std`, but icu_provider_segmenter needs `std` to read file from a `Path`, etc.)

2. Write a `SegmenterRuleProvider` to load the toml files, and port the transformation code in `bulid.rs`. It should transform the source data structure [`SegmenterRuleTable`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/build.rs#L68-L73) (in build.rs) to ICU4X runtime data structure [`RuleBreakDataV1`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/src/provider.rs#L103-L119) as described in step 3 in https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/writing_a_new_data_struct.md#lifecycle-of-icu4x-data

3. Hook `SegmenterRuleProvider` into `icu4x-datagen` so that `RuleBreakDataV1` can be serialized into a desired format such as json or postcard.

4. Remove [`RuleBreakDataProvider`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/src/provider.rs#L157-L158) (in provider.rs) because it's no longer used.

Note: generating `RuleBreakDataV1` required various Unicode properties such as `Word_Break`, `Extended_Pictographic`, etc. I'll probably use the existing Unicode properties in `icu_testdata` crate. So one possible issue is that: imaging a user wants to use icu4x-datagen to generate segmenter data from scratch, we'll need to improve `icu4x-datagen` to generate Unicode properties first and then use them to create the segmenter runtime data. This is out of the scope of this issue.

@sffc @makotokato Does the above steps sound good to you?
