### ISSUE TITLE
Add binary size testing

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#140]
In each component, we should have a set of demo files that illustrate common use patterns.  We should then compile those demo files with optimizations for code size (`-s`), and have a test that reports their sizes and complains if they grow.

I suggest building the demo files to WebAssembly and checking the size of the output .wasm file, because:

1. WebAssembly is not platform-dependent
2. WebAssembly has good tooling to inspect what causes size regressions to occur
3. We have WebAssembly in mind as a possible target in the future

**Comment by zbraniecki** [comment]
I think cargo `/examples` may be a good vehicle for such little demo apps. Also, it's related to #107 and maybe we could visualize it via #117.

**Comment by sffc** [comment]
Sounds good.  I can't seem to find the official documentation for the `examples/` directory, but I found it mentioned in a few places:

https://www.google.com/books/edition/_/kOiZDwAAQBAJ?hl=en&gbpv=1&pg=PA66&dq=cargo+examples+directory

**Comment by eyeplum** [comment]
> Sounds good. I can't seem to find the official documentation for the `examples/` directory

[This](https://doc.rust-lang.org/cargo/reference/cargo-targets.html?highlight=Examples#examples) and [this](https://doc.rust-lang.org/cargo/guide/project-layout.html?highlight=Example#package-layout) might explain `examples/` a bit more :)

**Comment by sffc** [comment]
With #365 merged, this issue is unblocked.  We can test how the size of the `*.wasm` files changes across PRs.

**Comment by gnrunge** [comment]
Questions of a newcomer:
- Do the demo files mentioned above exist? What are the common use pattern?
- How to build the compiled demo files? 
- Will GHA be a suitable platform for this CI task? GHA is stateless, isn't it?

**Comment by sffc** [comment]
The demo files are found in the `examples/` directories in each component. You can build them to WASM by running `cargo make wasm`, and from there you can measure their file size.

I imagine the file size should be recorded in a manner similar to how we record performance data (cc @echeran).

**Comment by echeran** [comment]
Yes, I expect binary size testing would be similar to performance testing. Ideally, the manifestation of the information would be a dashboard that allows us to notice changes over time. The reason is the same for performance testing -- it is easier to help us determine whether a change in metric value is reasonable through comparison to previous values than it would be assessing the absolute number directly.

For dashboards, we have a [high-level overview](https://github.com/unicode-org/icu4x/blob/master/docs/process/ci_build.md#implementation-of-various-ci-functionality) of how the dashboard action works and [inline source comments](https://github.com/unicode-org/icu4x/blob/master/.github/workflows/build-test.yml#L113-L218). I think that we could reuse the dashboard, but instead of providing it a performance metric number, we provide it a different number (binary size), and inherit the benefits of the dashboard 'infrastructure' provided by the GH Action.

Specifically, this would be providing our own value to the `tool` parameter of the benchmark dashboard GH Action to represent binary size testing. Seeing that the `tool` parameter is required and must be provided from a short list of options that represent supported performance testing tools, we would need either:

1. The benchmark action repo to [genercize its notion of a benchmark tool](https://github.com/rhysd/github-action-benchmark/issues/52)
2. Fork the benchmark action repo and modify it to have support for binary size numbers. It might be similar to how people have [created working support  for benchmarkdotnet](https://github.com/rhysd/github-action-benchmark/issues/43#issuecomment-686969453) via their fork, but perhaps with less logic required. At first glance, it seems like the core of the work is mimic the [JSON format consumed directly](https://github.com/Happypig375/github-action-benchmark/commit/4e3f7dbc3572b82f1f923dc94a1907e3039dd59d#diff-e1f84474b41230810df9943f2d15d1269a5dc790b3c4054d65abc85f2f6016d6) by the benchmark action (and thereby skip the [benchmark output -> JSON conversion](https://github.com/Happypig375/github-action-benchmark/commit/4e3f7dbc3572b82f1f923dc94a1907e3039dd59d#diff-5a62c4cdfb37aae9bf48e8f7c76e57e9481efe48903e43c5b801ccfad5590d7a)) followed by enabling a new [corresponding option for the `tool` parameter](https://github.com/Happypig375/github-action-benchmark/commit/4e3f7dbc3572b82f1f923dc94a1907e3039dd59d#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012).

**Comment by gnrunge** [comment]
Draft PR: https://github.com/unicode-org/icu4x/pull/859
