### ISSUE TITLE
Optimize Japanese calendar data loading

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1409]
In https://github.com/unicode-org/icu4x/pull/1394 we added support for the Japanese calendar; which included era data support. Currently, we load era data for both historical and modern (post Meiji) eras.

There are a couple things that can be optimized here:

Firstly, most people do not need pre-Meiji era data and we can fall back to Gregorian eras if we please. This would significantly cut down on data size. A simple way of doing this is to split the data into two variants: modern and historical (alternatively, "modern", and "full"). Data bundlers can choose to include historical data, and furthermore we can handle this in the calendar constructor by having an option on the constructor which decides whether or not to load historical data. It might need to be a tristate "Yes/No/Fallback" where in the third case it falls back to Gregorian eras for pre-Meiji.

Secondly, all the era data for post-Meiji is already hardcoded in the source; the only reason we load data is so that the potential for _new_ eras should be possible without a software upgrade. As such, we can further reduce data size by storing the data as an empty object

This would mean the data struct would look something like the following:

```rust
struct JapaneseErasV1<'data> {
   #[serde(borrow)]
   era_map: Option<ZeroMap<EraStartDate, TinyStr16>>
}
```

stored at variants `calendar/japanese@1/modern` and `calendar/japanese@1/historical`. The `modern` version is allowed to have the Option be `None`, which indicates that the five hardcoded post-Meiji eras are all it would contain otherwise. `calendar::Japanese` has an option which lets it either just load `modern` or attempt to load both.

Thoughts?

 - [x] @sffc 
 - [x] @zbraniecki

**Comment by Manishearth** [comment]
Note that the proposal here also includes a behavior change in that it allows the user to select a (probably default!) mode where pre-Meiji eras render as Gregorian.

**Comment by sffc** [comment]
There are two pieces of data:

1. Era cutoffs
2. Era display names

In terms of scalability, I am more worried about (2) than I am about (1).

I think an elegant way to solve this problem is to have two Japanese calendar types: one that contains all historical data, and one that only contains it for modern eras, using a Gregorian-like fallback for dates before 1868 AD.  They need different calendar identifiers: perhaps `japanese` for the modern-only one and `japanext` for the historical one.

The modern-only calendar would basically contain an engine that produces one of seven eras: BC, AD, Meiji, Taishō, Shōwa, Heisei, or Reiwa.  The data file contains names for those seven eras, all self-contained without having to explicitly reference Gregorian.

**Comment by Manishearth** [comment]
That works for me.

**Comment by sffc** [comment]
In terms of calendar data: I think `calendar/japanese@1.json` and `calendar/japanext@1.json` is what you want.  Make them separate keys, parallel to other calendars that may need data such as `calendar/hebrew@1.json`

**Comment by zbraniecki** [comment]
That sounds good to me.

My only question is about:
> The modern version is allowed to have the Option be None, which indicates that the five hardcoded post-Meiji eras are all it would contain otherwise. 

Is there a forward-compatible path to one day "hardcode" sixth post-Meiji era, or will introduction of the sixth era turn off the hardcoded path value in future ICU4X?

**Comment by Manishearth** [comment]
> Is there a forward-compatible path to one day "hardcode" sixth post-Meiji era, or will introduction of the sixth era turn off the hardcoded path value in future ICU4X?

Yes: the "empty data" case will always trigger "use as many eras as you have hardcoded". The onyl problem with that is that if you use newer data with an older ICU4X the older ICU4X will not know the new era, in which case you should run the datagen in a way that produces 6 era entries.

**Comment by sffc** [comment]
For the era cutoff data, we should do one of two things...

1. Make it fully data-driven
2. Do not have data at all and make it hard-coded

I think (1) is better than (2), because it may be necessary to push locale data updates on short notice without rebuilding the app.  My preference is to therefore always put the era map into the data file (it's not very big at all, and we only need 1 copy), and not rely on anything being hard-coded at runtime.  (Hard-coded is okay in the transformer.)

**Comment by Manishearth** [comment]
@sffc The hardcoding is just an optimization, where "empty era data" is a shorthand for "five post meiji eras". I'm fine with declaring that to be the only meaning of "empty era data" instead of having it mean "whatever is hardcoded", so that when a sixth era is added the era data can no longer be empty.

But I felt that it would be okay for "empty era data" to just mean "fall back to hardcoded eras" with the caveat that if you are running an older icu4x you should generate newer data.

**Comment by Manishearth** [comment]
Discussion:
 - @sffc Perhaps have u-ca-japanese and u-ca-japanext, upstream to cldr eventually
 - @mihnita: feels weird for users to have to care about this
 - @sffc yoshito said japanese people don't know pre-meiji eras. Most understandable behavior is to use gregorian eras prior to 1863
 - @Manishearth i like this reasoning
 - @mihnita why not just hardcode
 - @Manishearth, @sffc we prefer data-driven. Like the guarantee that building the data file includes the era cutoffs as well as the display names
 - @sffc easy to push data updates, hard to push code updates

Decision: split the calendar data. Perhaps single calendar type.

**Comment by sffc** [comment]
Regarding japanese/japanext, @macchiati said via email: "Looks like a reasonable approach to me."
