### ISSUE TITLE
Consider returning an upgraded type from char16trie

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#1444]
Currently the char16trie returns a i32 value like UChar16Trie. In https://github.com/unicode-org/icu4x/pull/1264/#discussion_r754621861, Shane suggested making the value type generic. See Markus' comment here as well: https://github.com/unicode-org/icu4x/pull/1264/#discussion_r762161243

**Comment by echeran** [comment]
FYI, we previously discussed the same topic for Unicode Properties, which came up regarding the [return type for enumerated property APIs](https://docs.google.com/document/d/1Ocsmakc9ydXaJ-3ntCd25H3wnCHTRe0S1sRUzJ0iqvc/edit#bookmark=id.g8ksdpyxfjwe).

The topic was discussed on 2 different days. We have [notes from the first session](https://docs.google.com/document/d/1Ocsmakc9ydXaJ-3ntCd25H3wnCHTRe0S1sRUzJ0iqvc/edit#heading=h.4miu2d96mvvg) and [notes from the followup session](https://docs.google.com/document/d/1Ocsmakc9ydXaJ-3ntCd25H3wnCHTRe0S1sRUzJ0iqvc/edit#bookmark=id.nl0r3j3rgu0k).

The conclusion of the discussion was that we will use the newtype idiom by default for representing Unicode Properties (given that it's possible for new property values to be added over time), with the exception of using a true Rust enum for the General_Category  property because the Unicode TR44 spec guarantees that the set of values for General_Category is permanently fixed.  It has been working well enough. The rationale also included the fact that newtypes should [also have minimal perf impact](https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html).

The [CPT code](https://github.com/unicode-org/icu4x/blob/main/utils/codepointtrie/src/codepointtrie.rs) is mostly the same after the change -- the concrete return type (`u32`) was replaced by the `TrieValue` trait.  You can look at PRs from @aethanyc and @younies ([example](https://github.com/unicode-org/icu4x/pull/1716/files)) for what has to happen when a new property is added, but basically it has to implement the `TrieValue` trait and a few other small things.

**Comment by sffc** [comment]
Related: https://github.com/unicode-org/icu4x/issues/1445

**Comment by sffc** [comment]
- @sffc - It seems important for 1.0 because it's an API issue.
- @dminor - The consistency with CPT is important.
- @sffc - We should see if we can get a 20%er to contribute here.

**Comment by sffc** [comment]
@pandusonu2 is interested in this.

**Comment by sffc** [comment]
So I confirmed with @markusicu that char16trie uses a variable-width encoding and is designed specifically for storing values of up to 32 bits. Smaller values take fewer bytes than larger numbers. This model is more similar to FlexZeroVec (#1790) than to ZeroVec.

Part of the design here is for the char16trie to store indices into another array that stores actual values.

Negative numbers are stored as twos-complement bits. This means that any negative number consumes the full 32 bits in the char16trie.

Therefore, I believe that the correct course of action here is to return a `u32` as the default type from a char16trie, with no support for upgraded types. If you want to upgrade your type, you will need to convert it from a `u32`.

We could optionally keep the `i32` getter under a different name like `get_i32`.

**Comment by sffc** [comment]
2022-01-09: Consensus on what I posted above.

**Comment by echeran** [comment]
After looking at the code and understanding the problem more, this issue seems moot.

In theory, it would be useful to have separate getters for returning as `u32` and `i32` so that we can allow more efficiency for users who only need `u32` data by reading the bytes as-is, and let users who need signed numbers (`i32`) to pay the cost of necessarily reading the full 32 bits (both `u16` elements) and converting from `u32` to `i32`.

However, we don't have any sources of char16trie data that are writing that data using exclusively `u32` data.  The only source is ICU4C, which currently writes `i32` data exclusively.  So it makes sense to keep things the way they are, because we shouldn't design for efficiency when it doesn't have a way of being realized.

Maybe in the future, if there is a use case that requires extra efficiency, we can reconsider this (ex: maybe something like for custom CodePointTries for Segmenter, where the ICU4C Builder code was compiled and topped with a Rust API) if it's worth the extra work.

**Comment by sffc** [comment]
I agree that since we are only ever consuming ICU4C data, which always uses `i32`, we can justify `i32` in this API. The footgun of `-1` looking like it should be stored efficiently, even though it is not stored efficiently, still exists, but that is an issue more for the builder than the consumer.
