### ISSUE TITLE
Unify methods between Yoke and DataPayload

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1485]
We have methods in Yoke like `get` and `project`, and the same methods in DataPayload.  We should consider unifying them somehow.  A few options:

1. Make DataPayload deref to Yoke
    - Problem: This may expose too much of the internals of DataPayload, especially the Cart since we want to keep the Cart as an implementation detail.
2. Add a trait YokeLike with getter functions, but nothing that deals with the Cart
    - Problem: May make the methods less discoverable
    - Problem: We can't add more methods to the trait without breaking stability
3. Status quo
    - Problem: Duplicated code which may get out of sync

Thoughts?

- [x] @Manishearth

**Comment by Manishearth** [comment]
I strongly prefer the status quo. The duplicated code is fine: it's thin wrapper code and it's hard to imagine it going out of sync due to type safety.

I don't like leaking the implementation detail by adding a deref. I'd like to be able to add more cart types as needed in the future.

A trait like YokeLike would have to live in the Yoke crate and I really don't think it belongs there; such traits typically need more of a reason to exist over "I don't like wrapping this type". I cannot imagine users of yoke wanting such a trait. Furthermore, calling these methods via a trait will put more strain on the type system for an abstraction that is already frequently poking holes.

Typical Rust style is to simply wrap the type, wrapper APIs do not go out of sync easily, and it's not much code.

Note that as the type system bugs get fixed the number of Yoke/DataPayload methods will likely reduce.

**Comment by sffc** [comment]
Fair enough.  I will close this issue then.
