### ISSUE TITLE
Revisit ja_zh option in LineBreakSegmenter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1490]
We have the following option:

https://unicode-org.github.io/icu4x-docs/doc/icu_segmenter/struct.LineBreakOptions.html#structfield.ja_zh

I would like to understand better the goal that this option achieves (why not always turn it on?), and the I'd like to discuss whether it should be an enum instead of a boolean.

@aethanyc @makotokato

**Comment by aethanyc** [comment]
The `ja_zh` option implements the requirement by [line breaking strictness](https://drafts.csswg.org/css-text-3/#line-break-property) in CSS Text spec. For example, the spec says:

- The following breaks are allowed for normal and loose line breaking if the writing system is Chinese or Japanese, and are otherwise forbidden:
  - breaks before certain CJK hyphen-like characters:
    〜 U+301C, ゠ U+30A0 

Line breaker adjusts the break opportunity according to `ja_zh` during runtime in https://github.com/unicode-org/icu4x/blob/c6a9402a015fa39b08123ca89ca370986c4a7563/experimental/segmenter/src/line_breaker.rs#L214-L221

**Comment by sffc** [comment]
Okay, thanks for that additional context.  I am generally opposed to booleans in APIs, because a question rarely has a "yes or no" answer.  However, since this directly corresponds to spec text, which is indeed a yes or no answer ("is the writing system Chinese or Japanese, yes or no?"), then a boolean seems appropriate.
