### ISSUE TITLE
Create wrapper object for ScriptExtensions array return value

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#1536]
This issue is spun off from a [previous discussion](https://github.com/unicode-org/icu4x/pull/1529#discussion_r789942566).

The question is whether, when returning the Script_Extensions property value for a code point, which is an array of Script values represented as a `ZeroSlice<Script>`, it would be better to wrap the `ZeroSlice<Script>` return value in an object that can allow specific extra functionality (ex: helper methods) added to it.

This seems somewhat reminiscent of #1239 which regards returning Unicode property data in terms of interfaces rather than hard-coding concrete data structures.

Pros & cons identified so far:

Pros:
- allows us to add helper methods to the return value
- would allow us to change the underlying implementation without affecting user-facing API (akin to idea of #1239)

Cons:
- Would lose the ZeroSlice functionality that we get for free (iterators, getters) unless we add methods to delegate accordingly

@iainireland @sffc

**Comment by markusicu** [comment]
Could this simplify the implementation? For example, for a character that has no Script_Extensions, it could copy the Script *value* into the return value, rather than having to treat the trie data array element as a Script array slice. This then also frees the trie encoding from *having to* store a non-scx value as a Script with no extra bits. (This is currently the case, but it could prevent future extensions of what is stored in the trie.)

**Comment by sffc** [comment]
Yeah, what Markus describes is an example of the second bullet under "pros", which is that we have more control over the implementation if we change it in the future.  We're not locking ourselves into having a ZeroSlice for all cases.

**Comment by sffc** [comment]
The thing that gives us the ultimate amount of flexibility actually is to return an iterator, like you're working on doing for the other case (script-to-cp-range).

**Comment by sffc** [comment]
There are two operations you may want from the return value:

1. Take the list as a whole and do something with it
2. Check to see if the list contains a particular value

(1) can be done with an iterator. (2) is more efficient with the ZeroSlice since you can binary search in it.

These two operations could perhaps be separate methods on ScriptExtensions.  But, they could also be a single method, returning a struct that implements `IntoIterator` and also has a `.contains()` function.  I think I lean toward separate methods.  We'd keep the current method, make it private, and call it in each of these two convenience functions.

**Comment by sffc** [comment]
The more I think about this the more I think we should probably go ahead and wrap the ZeroSlice.

This issue has no triage labels.  @echeran Are you happy with this conclusion, or do you want more input?

**Comment by sffc** [comment]
@snktd may be interested in this.
