### ISSUE TITLE
Implement naming convention for "data provider"

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1576]
In #1554 I am removing the `DataProvider` type and making it `ResourceProvider` and `DynProvider`.

The prelude types are now:

```
    pub use crate::any::AnyMarker;
    pub use crate::any::AnyPayload;
    pub use crate::any::AnyProvider;
    pub use crate::any::AnyResponse;
    pub use crate::buf::BufferMarker;
    pub use crate::buf::BufferProvider;
    pub use crate::data_provider::DataPayload;
    pub use crate::data_provider::DataRequest;
    pub use crate::data_provider::DataResponse;
    pub use crate::data_provider::DataResponseMetadata;
    pub use crate::data_provider::DynProvider;
    pub use crate::data_provider::ResourceProvider;
    pub use crate::error::DataError;
    pub use crate::error::DataErrorKind;
    pub use crate::marker::DataMarker;
    pub use crate::marker::ResourceMarker;
    pub use crate::resource::ResourceKey;
    pub use crate::resource::ResourceOptions;
```

It is weird that some of them are "data" and some are "resource".  I started using the word "resource" to refer to specific pieces of data.  The word "data" is vague, overused, and is weird when it comes to singular and plural.  However, I still think it is okay to talk about "data pipeline" and "data provider" as a high-level concept.

We should also think about the naming for `DynProvider`.  I chose this name because the main use case for `DynProvider` moving forward are things like `DynProvider<SerializeMarker>`, where you want a pluggable marker representing a trait object.

Seeking input from:

- [x] @robertbastian 
- [x] @Manishearth 
- [x] @zbraniecki 
- [ ] others?

**Comment by sffc** [comment]
Also address this comment from @Manishearth:

> issue: I'm not a huge fan of "type 1" and "type 2" naming, can we just call these any providers and buffered providers?

_Originally posted by @Manishearth in https://github.com/unicode-org/icu4x/pull/1554#discussion_r798872212_

**Comment by Manishearth** [comment]
I think moving to "resource" provider is nice. I don't know what to do about DynProvider, I don't _like_ having dyn in its name when it does not in its definition provide dyns, but it _is_ supposed to largely be fore type erased stuff.

**Comment by robertbastian** [comment]
1) The name I have the biggest issue with is `icu_provider::marker::DataMarker`. I think it should be `DynMarker` to give us the symmetry `DynProvider<M: DynMarker>` <-> `ResourceProvider<M: ResourceMarker>`

2) Most crates seem to call their error types just `Error`. I understand that our style guide prescribes such repetitive naming but I don't agree with its reasoning.

3) Same for `icu_provider::data_provider::{DataPayload,DataRequest,DataResponse,DataResponseMetadata`, I'd prefer dropping the `Data` prefix, but I don't think this is confusing as is, because these types are shared between the `DynProvider` and `ResourceProvider`API.

4) Now that we don't have a `DataProvider` type anymore, I would not be opposed to renaming `Resource*`* to `Data*`. I think that would make it easier to understand the whole system, `DataProvider` is what we're talking about when we say "data provider", and `DynProvider` is a tool that can be used to implement a `DataProvider`.

**Comment by robertbastian** [comment]
5. If we decide against (4), I think we should rename `FsDataProvider`, etc. to `FsResourceProvider`, as clients should interact with them through the `ResourceProvider` trait.

**Comment by robertbastian** [comment]
(with (4) we'd have to rename `load_payload` and `load_resource` as well, we could do something like 

`DynProvider::load_dyn(ResourceKey, DataRequest) -> Result<DataResponse<M>, DataError>`

`DataProvider::load_data(DataRequest) -> Result<DataResponse<M>, DataError>`)

**Comment by Manishearth** [comment]
> 1. I think it should be `DynMarker` to give us the symmetry `DynProvider<M: DynMarker>` <-> `ResourceProvider<M: ResourceMarker>`

Honestly this is kinda why I disagree with the naming `DynProvider`, the dyn provider does not _just_ provide `dyn`s, and neither does `DataMarker`.

**Comment by robertbastian** [comment]
How about `RawProvider`? We usually use it to provide raw things (any, byte buffers) that have to be processed before they can nicely be returned as by `ResourceProvider`

**Comment by sffc** [comment]
Discussion:

Old names:

```
    pub use crate::data_provider::DataPayload;
    pub use crate::data_provider::DataRequest;
    pub use crate::data_provider::DataResponse;
    pub use crate::data_provider::DataResponseMetadata;
    pub use crate::data_provider::DynProvider;
    pub use crate::data_provider::ResourceProvider;
    pub use crate::error::DataError;
    pub use crate::error::DataErrorKind;
    pub use crate::marker::DataMarker;
    pub use crate::marker::ResourceMarker;
    pub use crate::resource::ResourceKey;
    pub use crate::resource::ResourceOptions;
```

New names:

```
    pub use crate::data_provider::DataPayload;
    pub use crate::data_provider::DataRequest;
    pub use crate::data_provider::DataResponse;
    pub use crate::data_provider::DataResponseMetadata;
    pub use crate::data_provider::DynamicDataProvider;
    pub use crate::data_provider::DataProvider;
    pub use crate::error::DataError;
    pub use crate::error::DataErrorKind;
    pub use crate::marker::DataMarker;
    pub use crate::marker::KeyedDataMarker;
    pub use crate::resource::DataKey;
    pub use crate::resource::DataOptions;
```

**Comment by robertbastian** [comment]
Our load methods are now
```
AnyProvider::load_any
BufferProvider::load_buffer
DynamicDataProvider::load_payload
DataProvider::load_resource
```

The last one is obviously not great anymore, and I'm also not a fan of `load_payload`, because all of these methods return some kind of payload (`DataPayload` or `AnyPayload`).
I proposed `load_data` above but we didn't discuss it in the meeting; we could also use `load`. Maybe `DataProvider::load` and `DynamicDataProvider::load_data`? I can't see how we would put the concept of compile-time keys into the names, which is the only difference between those, but we need different names to avoid fully qualifying them.

**Comment by sffc** [comment]
`DataProvider::load` and `DynamicDataProvider::load_data` works for me
