### ISSUE TITLE
Investigate staggered results of binsize benchmark variant jobs

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#1641]
In Github Actions, the `binsize` benchmark computes stats for the uncompressed and compressed versions of the WASM binary output.

In 2 back-to-back merges to `main`, we see the alerts firing as expected (due to an increase after including serde was added to the zerovec proc macro).  However, the alerts don't appear simultaneously on [the commit that causes the size increase](https://github.com/unicode-org/icu4x/commit/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976).  Instead, one of the alerts fires only during [the next commit](https://github.com/unicode-org/icu4x/commit/caacf5426577cf9e77523a2ca05a86ca0af04e3f)'s workflow run, even though that next commit is totally unrelated.

**Comment by sffc** [comment]
@gnrunge to monitor whether this issue has happened again. If there is no evidence of this issue repeating, we will close the issue, and reopen in the future if the issue happens again.

**Comment by gnrunge** [comment]
The binsize (gz) threshold alert was triggered at [this GHA](https://github.com/unicode-org/icu4x/actions/runs/1896132175) run of 'Build and Test'.  A look at the summary shows that the corresponding binsize (wasm) run was canceled in its step 'Build wasm executables'. Apparently it was hanging for almost six hours. Because of the cancellation of binsize (wasm) no binary size alert was triggered. Instead, the alert was then triggered at the possible opportunity, which was the [next GHA](https://github.com/unicode-org/icu4x/runs/5338336626?check_suite_focus=true) run.
This explains why the alerts were triggered one after the other in two subsequent GHA runs for two different merge requests.
No explanation can be found for the hang-up of the binsize (wasm) run:
```
2022-02-25T00:46:57.8287572Z Writing wasmpkg/wasm-opt/syntatically_canonicalize_locales+opt.wasm 
2022-02-25T06:37:22.1005723Z ##[error]The operation was canceled.
```
That may be an odd GHA fluke, and has not happened again so far. And the typo in 'syntatically' is not the issue, works in other runs.
I plan to close this bug soon since it looks more like a GHA issue. If it happens again in any systematic manner we need to reopen.
