### ISSUE TITLE
Move segmeter_lstm into segmenter

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#1654]
From https://github.com/unicode-org/icu4x/issues/1033#issuecomment-1027198713

**Comment by aethanyc** [comment]
This is a good first step toward fixing #1531.

**Comment by sffc** [comment]
What is the status of this issue? It is assigned to "0.6 Sprint E" which is in the past. I hope that this issue can be prioritized so that we can ship Segmenter with the LSTM models for SEA languages.

Note that we now have models for all four languages covered by ICU4C: Thai, Burmese, Lao, and Khmer.

**Comment by dminor** [comment]
Blocked on https://github.com/unicode-org/icu4x/issues/1427
