### ISSUE TITLE
Consider making ULE generic over const N?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1692]
Currently the ULE trait is not great in the following ways:

1. Every validate impl needs to check for length (in checklist but easy to forget)
2. Cannot easily parse a single item out of a slice without validating the whole slice
3. No way to know how many bytes are needed at compile time

These problems would be solved by making `ULE` generic over `N`, as follows:

```rust
pub unsafe trait ULE<const N: usize> {
    // Primary function that clients should implement
    fn validate_item(bytes: &[u8; N]) -> Result<(), ZeroVecError>;

    // New function that would not otherwise be possible generically
    // `ULEIterator` is `impl Iterator<Item = Result<Self>>`
    fn iter_parsed(bytes: &[u8]) -> ULEIterator { ... }

    // Another convenience function
    fn get_parsed(bytes: &[u8], index: usize) -> Result<Self, ZeroVecError> { ... }

    // Clients can implement this as well if they can do so more efficiently
    fn validate_byte_slice(bytes: &[u8]) -> Result<(), ZeroVecError> {
        // check length; chunkify; pass to Self::validate_item
    }

    fn parse_byte_slice(bytes: &[u8]) -> Result<&[Self], ZeroVecError> {
        // unchanged
    }

    unsafe fn from_byte_slice_unchecked(bytes: &[u8]) -> &[Self] {
        // unchanged
    }

    fn as_byte_slice(slice: &[Self]) -> &[u8] {
        // unchanged
    }
}
```

Use case: I need to validate that a byte slice contains valid Region subtags. In order to do this, I first need to validate the whole slice as TinyStr, and then again as Region. It would be nicer if I could implement `validate_item` that does the TinyStr and Region checks at the same time.

I'm not completely sold on this, and there are workarounds for my use case that don't involve changing the trait.

- [x] @Manishearth 
- [ ] @robertbastian

**Comment by Manishearth** [comment]
This has to be an associated constant, not a constant parameter (otherwise it becomes pervasive for no reason whatsoever), and we could mandate it always be set to `::mem::size_of::<Self>()`. We've wanted a `BYTES` parameter anyway.

I think this could work, but I'm _very_ skeptical of the benefit, as long as things get inlined Rust will very likely collapse the two length checks. I'd like to see a more general motivation over the specific use case; for the specific use case there are many other ways of achieving this. Introducing more load-bearing constants at _this_ stage of rust's const support doesn't seem great to me.

One thing to note is that transmutes don't always work in the presence of associated constants, which is a bit of a worry for me.

For me the right way to do this would perhaps be to expose an API on TinyStr that allows for more complex validation (with a closure, probably), and use it in the validation code. I'd rather not make zerovec changes that can be satisfied with changes on the user side unless there's a more general use case for the feature.

**Comment by sffc** [comment]
Closing because `ULE` is fine right now but we may revisit this in the future.
