### ISSUE TITLE
What are the key low-level data structures we need to support ECMA-402?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#17]
ICU4C/ICU4J is built on top of a large, internal standard library of low-level data structures.  We will likely want at least a subset of those in OmnICU.

My question is, which ones do we need in order to support the ECMA-402 featureset?

Examples:

1. UCharsTrie: map strings to integers.  Useful for parsing well-defined syntaxes like number skeletons and measurement unit identifiers.
2. UCPTrie: map code points to integers.  Useful as a basis for UnicodeSet.
3. UnicodeSet: a set of code points and strings (usually graphemes).  Useful for a wide range of operations in ICU.
4. FormattedStringBuilder: A string builder that supports field positions (formatToParts) and is optimized for dealing with LDML string patterns.

CC @markusicu

**Comment by markusicu** [comment]
Looks like a good start to me.

In addition to UCharsTrie, its sibling BytesTrie is sometimes more appropriate (smaller). For example, ICU uses a BytesTrie for Unicode property names and property value names, and also for data lookup in the LocaleMatcher code for likely-subtags mappings and for looking up languageMatch distances. (Those essentially work with ASCII-repertoire strings.)

We have a serialized form of a UnicodeSet that contains only code points (as an inversion list stored in an array of 16-bit units). We do not currently have a serialized form of the set of strings in a UnicodeSet. I plan to use a UCharsTrie for that, for the emoji properties of strings.

Note on UCPTrie=CodePointTrie vs. UnicodeSet: 1. A UnicodeSet is a boolean set while a CodePointTrie maps code points to an 8/16/32-bit int. 2. A built CodePointTrie is *fairly* compact but optimized for speed. It is not necessarily great for enumerating ranges. A UnicodeSet always carries data that is usually very compact and makes enumeration trivial, and when frozen adds a small, additional data structure that speeds up "contains" but not necessarily to the same level as a CodePointTrie.

The "runtime" parts of these classes are relatively small and simple. I would port them so that they can work with the same serialized data structures. I would use C++ and/or Java builder code for necessary sets of data, calling into the regular ICU builders for the low-level structures.

For UnicodeSet, we could go as far as limiting a port to read-only functions such as "contains" and "span". If necessary, port some of the modifiers (add/retain/remove/...). I would try not to port code for building sets from pattern strings, especially not ones involving properties.

I wonder about the ability in Rust and other languages to memory-map data structures and "just use them" like we do in C/C++. But maybe that's a question for a different issue.

**Comment by sffc** [comment]
> The "runtime" parts of these classes are relatively small and simple. I would port them so that they can work with the same serialized data structures.

That makes sense to me.

> I would use C++ and/or Java builder code for necessary sets of data, calling into the regular ICU builders for the low-level structures.

What are the "necessary sets of data"?

One desired setup for ICU4X is to give it raw CLDR data (and presumably also raw UCD data) and have it process it at runtime, not for production use but for testing.  For production use, the same code would build an intermediate data file (much like ICU4C), but it would be in the same toolchain.  I'm not sure how calling existing ICU tools ties in with this.  @zbraniecki

**Comment by macchiati** [comment]
If we had the opportunity to do UnicodeSet over, I would have defined the
class such that it didn't do any parsing of properties, and had a separate
parsing class and a separate formatting class that could take advantage of
more data (eg about unicode properties) and options (eg different regex
conventions).

Then the core functionality would be the boolean operations, plus building
from ranges and code points; just code.

Mark

**Comment by sffc** [comment]
Follow-up issues:

- UnicodeSet: #91
- BytesTrie: #131
- UCPTrie: #132

Closing this issue since we've now split it in three.

**Comment by zbraniecki** [comment]
What about `FormattedStringBuilder`?

**Comment by sffc** [comment]
> What about `FormattedStringBuilder`?

I was going to add that as part of NumberFormat, but good idea bout splitting it out.  Smaller tickets and PRs are good.  #135
