### ISSUE TITLE
Add Clippy check for #[non_exhaustive]

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#170]
All public API structs and enums should be tagged with `#[non_exhaustive]`.  Is there a Clippy check for this?

https://github.com/unicode-org/icu4x/blob/master/docs/style-guide.md#implement-default-and-non_exhaustive--required

**Comment by Manishearth** [comment]
This can be done as a "restriction lint" (i.e. a lint that's not enabled by default that people can enable). It would be a rather simple lint to write: you would write a lint with an early pass that runs `check_item` that checks all enums for the attribute.

See https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md for docs on adding lints.

**Comment by Manishearth** [comment]
I'm going to work on this now

**Comment by Manishearth** [comment]
PR at https://github.com/rust-lang/rust-clippy/issues/6616

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/pull/6617 landed, and clippy's biweekly sync is scheduled tomorrow (i can do an unscheduled sync if we ever need though), so we can basically start using it in one or two days when it hits a nightly!

**Comment by Manishearth** [comment]
Alright, so these lints exist as `clippy::exhaustive_enums` and `clippy::exhaustive_structs`. We have a couple paths forward:

 - Blanket turn on `-W clippy::exhaustive_enums -W clippy::exhaustive_structs` for all our crates. This will be tedious, and not everyone knows whether an enum should be tagged with `#[non_exhaustive]` or `#[allow(clippy::..)]`
 - Turning it on crate by crate, so that the appropriate maintainers can properly review it
 - Turning it on only for specific crates (which?)

Also I discovered a bug in `clippy::exhaustive_structs`, so let's not use that yet, but we can figure out a plan.

**Comment by sffc** [comment]
I think it should be enabled for most components, although some components can opt out. For the enabled components, I put some ideas in #383.

We should close this issue once the Clippy check is all finished, and move discussion on how to apply it to #383.

**Comment by Manishearth** [comment]
The clippy check exists, and is in the current nightly. I did the work for an early sync so that we can get the bugfix soon.

**Comment by sffc** [comment]
We still need to enable the lint. This should be 1.0-blocking.

**Comment by Manishearth** [comment]
We can make the `#[data_struct]` attribute apply the allow attribute automatically
