### ISSUE TITLE
Use argh instead of clap for CLI tools

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1741]
I originally wrote the code to use `clap` for argument parsing in ICU4X CLI tools. However, I've since discovered [argh](https://github.com/google/argh), a Fuchsia tool used in projects such as cargo-gnaw. I find it simpler to use, and organizationally we are closer to the Fuchsia team, so all else equal, it seems like we should consider `argh`.

Needs approval from:

- [x] @Manishearth 
- [x] @filmil 
- [ ] @zbraniecki 
- [ ] @dminor

**Comment by Manishearth** [comment]
argh is low-overhead, i think it's a good choice. clap is the semi-official standard, though (maintained by the CLI WG), so there's value in that too.

**Comment by filmil** [comment]
Hi folks. 

Of course, it is up to you to decide what you are going to use, I just want to give you a data point.

While `argh` is a package that you can use in all rust programs if you so choose, it follows the Fuchsia's [command line rubric](https://fuchsia.dev/fuchsia-src/development/api/cli), rather than GNU or POSIX arg parsing conventions which may be more prevalent and perhaps expected. The rubric prescribes a tad bit different behaviors from what you may be used to.  For example, IIRC, the form `--flag=value` is not supported, and must be `--flag value` instead. This is convenient in Fuchsia, which does not really need or want many different flags on binaries. But it may prove unusual of you intend to write command line utilities where flags there are many flags, and flags are used often. 

On the other side of this dichotomy, I remember that `clap` used to have an [outrageously complex API](https://docs.rs/clap/2.21.0/clap/index.html), which would have been a deterrent for me.  But it seems that [latest versions](https://docs.rs/clap/3.1.6/clap/index.html) are way saner and follow the `Args` struct approach which seems to work quite well.

With that in mind, and given that `argh` is somewhat biased towards Fuchsia's use cases, you may want to re-evaluate your proposal.
