### ISSUE TITLE
Dependency version style

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#175]
@zbraniecki suggested in https://github.com/unicode-org/icu4x/pull/141#discussion_r453153314 that we use only major and minor versions for dependencies, and not patch versions.

Although this might make sense in some cases, I think in general it's probably safer to include major, minor, and patch versions.  The main reason is that if people have different versions of a dependency installed, they can and will get different results in code size, which might make those benchmarks harder to reason about.

**Comment by Manishearth** [comment]
I like using patch versions for small fixes, like perf fixes or adding small APIs.

**Comment by zbraniecki** [comment]
@Manishearth does it mean you recommend us locking, for example, smallver on `1.4.1` over just `1.4` or `1`?

**Comment by Manishearth** [comment]
I'm not sure what you mean by that

**Comment by zbraniecki** [comment]
We're about to pull dependency on `smallvec`. The use we have works with any `smallvec` over `1`. We can set dependency on `1.0` and it'll work for any `smallvec` at version `1.*.*` that the user has in their system.

Or we can set dependency on `1.4` and then if any other dependency of an app/library has `1.3` cargo will bump both to `1.4`, or if something else has a strict dependency on `1.3.1` then we'll have two versions.

Or we can set dependency on `1.4.1` which means that if something else uses `1.4` or `1.3.1` we'll force them to update or have two versions.

My take was that since our use works with all `smallvec` `1.0` and up, we should be loose, but I feel like your comment indicates that you prefer to set the strict dependency on `1.4.1`, am I correct?

**Comment by Manishearth** [comment]
Oh, I see.

I misunderstood the question then, I was talking about the crates _we_ publish. For your situation I would suggest using 1.0 and only bumping that number when there's a new feature we need, or when there's a 2.0

**Comment by sffc** [comment]
In general, I like using major+minor in dependencies, but my suggestion here was that if we use major+minor+patch, it will help make more consistent benchmarks on code size (and also memory/performance).

**Comment by Manishearth** [comment]
Not really, because when you try building without a preexisting Cargo.lock, Rust will pick the latest of all the dependencies. The way to force a particular version is `=foo` constraints, and that's not recommended since it overly constrains dependency resolution.

If you want consistent benchmarks, check a Cargo.lock into tree. It's not usually done for libraries but it makes sense if the library also has binaries like benchmarks. But it's also worth regularly updating deps in such a case.

**Comment by sffc** [comment]
That makes sense.  I think checking Cargo.lock into tree is probably what we want then.

**Comment by sffc** [comment]
We discussed this on 2020-07-17 and agree with @Manishearth's suggestion.  The action on this ticket is to add Cargo.lock to source control.
