### ISSUE TITLE
Error naming and layout conventions

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#183]
I've been making errors such as

```rust
#[non_exhaustive]
#[derive(Debug)]
pub enum ResponseError {
    UnsupportedCategoryError(Category),
    UnsupportedDataKeyError(DataKey),
    // ...
}
```

I think that putting "Error" in both the name of the enum and the name of the variant is redundant.  I was thinking of changing this to

```rust
#[non_exhaustive]
#[derive(Debug)]
pub enum ResponseError {
    UnsupportedCategory(Category),
    UnsupportedDataKey(DataKey),
    // ...
}
```

About Error enums, I also think:

1. `Error` should be a top-level export of each component
2. It should implement `std::error::Error`
3. It should be `#[non_exhaustive]`, such that we can add variants later without a major version bump

Thoughts?

@Manishearth @zbraniecki

**Comment by zbraniecki** [comment]
I tend to name errors in a generic way because I noticed that `std::io::Error` and `std::foo:Error` are common, so I tend to do `icu::locale::Error`.

Inside, I do:

```rust
pub enum Error {
  Parser(ParserError),
  Unknown
}
```

I do implement `std::error::Error` and derive `Debug`.

I'm not sure about if `non_exhaustive` should be the right to do thing to do.

**Comment by Manishearth** [comment]
@sffc the guidelines look good to me

while the stdlib _does_ use `io::Error` etc, those names come from a time where stdlib design was hoping we'd use paths in names more often (importing `io` and using `io:Error`). In practice people rename these types anyway (people don't like doing `io::Error`), so I think calling it `ResponseError` or whatever is better.

**Comment by zbraniecki** [comment]
Oh, that's great!
I was always confused because I prefer explicit names (I spent some time with @filmil on `ListFormat` vs `list::Format` advocating for the former), but with errors I was following the `io::Error` which felt inconsistent.

I'm also in support of naming public things in a discriminatory way, so I prefer `PluralRulesError` and `ListFormatError` over `icu::list::Error`.

We should write it in the style guide :)

**Comment by zbraniecki** [comment]
Manish opened https://internals.rust-lang.org/t/does-the-avoid-prefixing-the-type-with-the-name-of-the-module-style-rule-still-apply/12819

**Comment by sffc** [comment]
Convention from 2020-07-30 meeting: Add a prefix to types that have an overly-generic name: "ListError" instead of "Error"; "ListOptions" instead of "Options"; "DataCategory" instead of "Category".

**Comment by sffc** [comment]
Action: Document this in style-guide.md
