### ISSUE TITLE
Move error_value (and optionally default_value) to the CPT header?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1879]
See previous discussion in #1183.

The thread #1183 got derailed into a discussion on trust boundaries. I moved that conversation over to #1290. Our work on CrabBake is our solution to that side of the problem and allows us to reason about "invalid serialized data" in the serde case.

I increasingly feel that the option most consistent with how our data model works is to move these two fields, especially `error_value`, into the CPT header. This would help us eliminate the problematic `DATA_GET_ERROR_VALUE`.

This should be an easy change: the error value is always the last value in the data array, so at datagen time, we just remove the last value from the array and save it into the header.

Responses to the pushback on this idea from the previous thread:

> @markusicu: Between UTrie2 and the newer CodePointTrie, I moved the error value from the header struct into the data array in order to make the code simpler and more uniform.

In Rust, I do not believe that this will increase code complexity. It would involve adding a type parameter to `CodePointTrieHeader`, but this parameter would just be bubbled down from `CodePointTrie`, which already has a type parameter.

It may require adding `#[derive(Deserialize)]` on TrieType types that don't already have it.

> @hsivonen: This would make ICU4X compute bogus results if externally-traveled data actually has been corrupted. In terms of surprise and what it takes to understand what's going wrong, this seems worse than any of the other options. However, in terms of usage ergonomics, I'd rather settle on this option than option 2 if we can't agree on panicking on malformed data at the time of making lookups from the data.

We are moving from one type of GIGO to another type of GIGO. The new type of GIGO is in fact slightly more robust, because it allows us to automatically fail in the constructor if the error value field is not present in the header, something we can't as easily do when it is stored in the data array. Discussion of when or when not to rely on GIGO is the topic of #1290 and I do not want to derail this thread again on that separate, very important issue.

Needs approval from:

- [x] @echeran 
- [ ] @markusicu 
- [x] @Manishearth

**Comment by Manishearth** [comment]
This makes sense to me.

**Comment by echeran** [comment]
It seems fine to me, it seems to be an incremental improvement on code clarity and safety without actually changing any behavior.

If you're so inclined, since this value should be the last element in the CPT's data array (according to this [constant](https://unicode-org.github.io/icu4x-docs/doc/src/icu_codepointtrie/impl_const.rs.html#21)), you could truncate the data array by 1 element. But I don't know if that's beneficial.

**Comment by Manishearth** [comment]
@pandusonu2 is working on this


The bug is to add an error_value field to this type, of type `T`

https://github.com/unicode-org/icu4x/blob/b6774e2212d47d9c24648ccc065ba4637c68b9ce/utils/codepointtrie/src/codepointtrie.rs#L114

And we can parse it in from the last element of the data array here:

https://github.com/unicode-org/icu4x/blob/b6774e2212d47d9c24648ccc065ba4637c68b9ce/utils/codepointtrie/src/toml.rs#L103-L122

And then replace all uses of the following constant with it:

https://github.com/unicode-org/icu4x/blob/b6774e2212d47d9c24648ccc065ba4637c68b9ce/utils/codepointtrie/src/codepointtrie.rs#L44

We also probably need a `pub error_value()` function that returns this.

**Comment by sffc** [comment]
@pandusonu2 What is the status of this issue?
