### ISSUE TITLE
Make collator resilient against bogus data from the provider

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1891]
Either validate upon deserialization or emit a placeholder collation element at run-time for bad data. The consistency of case bits in metadata should probably be the former and bad indices in CE32s that hold indices should be the latter.

**Comment by sffc** [comment]
For `CollationMetadataV1`, it looks like you are storing a `u32` bitmask as the entire value for a key. This is fine, but we should consider expanding the bitmask to individual fields upon deserialization (i.e., expand the struct to contain a bunch of bools instead of a bitmask). It could have a custom Deserialize impl that writes out the fully expanded struct in human-readable form, and the bitmask version in machine-readable form. This is better code style because then your validation logic takes place during the deserialization phase, and you can error out, rather than relying on GIGO in the runtime phase. Note that the validation logic can likely be quite minimal, since it's basically infallible to pull out a boolean.

**Comment by hsivonen** [comment]
Validate that `last_primaries` is at least 4 entries long.

**Comment by hsivonen** [comment]
> For `CollationMetadataV1`, it looks like you are storing a `u32` bitmask as the entire value for a key. This is fine, but we should consider expanding the bitmask to individual fields upon deserialization (i.e., expand the struct to contain a bunch of bools instead of a bitmask). It could have a custom Deserialize impl that writes out the fully expanded struct in human-readable form, and the bitmask version in machine-readable form. This is better code style because then your validation logic takes place during the deserialization phase, and you can error out, rather than relying on GIGO in the runtime phase. Note that the validation logic can likely be quite minimal, since it's basically infallible to pull out a boolean.

I think that would be excessive. Opened #1914 instead.
