### ISSUE TITLE
Hoist U24 to zerovec

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1982]
There's now a [`U24`](https://github.com/unicode-org/icu4x/blob/main/experimental/normalizer/src/u24.rs) definition in the normalizer. It might turn out to be useful in other crates that use `zerovec`, so it would make sense to hoist it into `zerovec` itself.

**Comment by sffc** [comment]
Thoughts:

1. If we do this, it would be better to make `RawBytesULE<3>` work as expected so that we can remove the `unsafe impl ULE for U24`
2. I'm a little bit unclear on the use case. My understanding was that the original use case was a more compact representation for `char`, but that is tracked already in #1970.

**Comment by hsivonen** [comment]
> I'm a little bit unclear on the use case.

The use case at hand is making the supplementary-plane expansion tables in the normalizer use 8 bytes per scalar value, and making sure that happens by file format freeze regardless of the schedule for #1970. If `CharULE` migrates to 3 bytes, then it could address that particular use case. However, it's reasonable to expect that numbers that fit in 24 bits but not in 16 bits may come up again for users of `zerovec`.

Aside: It would be a very bizarre end state if the normalizer started using deserialization-time-validated data for the least-often accessed data without also changing the other places that hold (16-bit) scalar values to be validated at deserialization time.

**Comment by sffc** [comment]
I think this is obsolete.
