### ISSUE TITLE
It should be easy to construct ZonedDateTimeFormatInputs

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2145]
Currently it's quite easy for the user to construct DateTimeInputs via the `icu_calendar` crate. The same cannot be said of `ZonedDateTimeInput`, for which we only have a single type: `MockZonedDateTimeInput`, which only supports gregorian dates.

I propose we get rid of `ZonedDateTimeInput`, and instead have a:

 - `TimeZone` type
 - `Zoned<T>`, which wraps a datetime type with a timezone

This is fewer traits, and overall cleaner to work with IMO. These types could even live in `icu_calendar`. I see that `DateTimeInput` is quite useful since people may want to construct custom datetimes that potentially require some computation, but I can't say the same about `ZonedDateTimeInput` since I don't really see any need for computation for a timezone specifier.

Currently this blocks me from writing any useful tests for https://github.com/unicode-org/icu4x/issues/1673, and in general makes that code gnarlier.

At the very least we should export a default way for users to create ZonedDateTimeInputs, but I'm skeptical that we should have that trait in the first place.

Thoughts? @sffc @dminor @gregtatum @nordzilla @zbraniecki

**Comment by sffc** [comment]
This relates to something I was discussing with @nordzilla @samchen61661 this week, which is what exactly the data model of `TimeZone` should be. I think `TimeZone` itself can/should be a concrete struct, similar to `MockTimeZone`.

A way to defer this decision would be to make a function

```rust
impl ZonedDateTimeFormat {
    pub fn format_datetime_with_time_zone(datetime: &impl DateTimeInput, time_zone: TimeZone)
}
```

then we reserve `pub fn format` for some future trait/struct.

**Comment by Manishearth** [comment]
This also works for me. In fact, I don't even think we should have a separately named constructor for that, I'd just prefer to pass aroudn TimeZone everywhere directly.

**Comment by sffc** [comment]
I envision that in the future we _may_ want to allow users to implement a `ZonedDateTime` type (similar to Temporal.ZonedDateTime) and implement a ZonedDateTimeInput trait.

**Comment by sffc** [comment]
One question that we haven't fully addressed is whether to handle the time zone at construction time or format time. We are doing the calendar system at construction time; should we also do that with time zone?

Thoughts:

- With calendars, we can use Rust type safety to ensure that the thing being formatted has the same calendar as what the formatter was configured with; we can't do this with time zones since the set of time zones is unbounded
- ZonedDateTime values typically should travel with both a time zone and a calendar
- If we handle these cases differently, we should be able to justify it
- Setting up the time zone formatting in the constructor is more efficient if the same time zone is used in a loop, but less efficient if the values all have different time zones. To address this we could consider making a ZonedDateTimeFactory that owns the full data and ZonedDateTime borrows just the part it needs

**Comment by Manishearth** [comment]
I think it's a reasonable use case to want to format dates for different time zones in one go. I can't say the same for calendars; I woudl typically expect people to be formatting a bunch of dates for the same calendar. Folks could build an AllCalendarFormatter type if they really want to format for a mix of calendars. So I think the "pass in the time zone when formatting" status quo is great.

The factory thing works, but we _already_ have that kind of API with `.format()`, where ZonedDTF turns into a FormattedZonedDateTime that borrows everything, just that it also borrows the date. I don't know if there really is a need to make it three-level.

**Comment by sffc** [comment]
Conclusion from discussion with @zbraniecki @sffc @nordzilla @Manishearth:

- Introduce `TimeZoneInput` trait
- Make the function take both the `&impl DateTimeInput, &impl TimeZoneInput`
- Extract the fields from both DateTimeInput and TimeZoneInput before returning the FormattedZonedDateTime; this will be optimized in #2143 
- Introduce a canonical time zone type (rename MockTimeZone)
- Introduce `icu_timezone` which does time zone calculations (but not formatting), similar to `icu_calendar`
- Define the canonical `TimeZone` type in `icu_timezone`, and `TimeZoneInput` in `icu_datetime`
- Work toward making `icu_timezone` and `icu_calendar` be optional features on `icu_datetime`

**Comment by sffc** [comment]
Additional addendum that I realized later and discussed with @Manishearth: the thing that is currently named "MockTimeZone" should be named "RawTimeZone" or similar, because we most likely want to reserve the "TimeZone" name for a thing that has the time zone and meta zone data inside.

@Manishearth also suggested that we have an always-available `UTC` type that implements `TimeZoneInput` and can be used if you just want UTC.

**Comment by Manishearth** [comment]
So it might be a bit late to suggest this but I'm now wondering if instead of `icu_datetime`, `icu_calendar`, `icu_timezone` we should have `icu_temporal_format`, `icu_datetime`, and `icu_timezone`. Especially since the actual `DateTime` type lives in `icu_calendars`.

@echeran also noted that it can be confusing talking about formatter crates vs other crates.

**Comment by sffc** [comment]
We don't put "format" in other formatter crate names: `icu_list`, `icu_decimal`, etc.

The utility for `icu_decimal` is `fixed_decimal`, which could suggest that the utility for `icu_datetime` is some other entirely new name. But I think it's fine if it is `icu_*` like `icu_locid` which is not a formatter.

I do think that `icu_datetime` should remain the formatting crate, because it is DateTimeFormat[ter] basically everywhere.

**Comment by Manishearth** [comment]
Yeah, I know, it does feel weird that DT is in icu_calendar, and icu_datetime contains TZF as well

**Comment by sffc** [comment]
Perhaps `icu_datetime_calendars` and `icu_datetime_timezones`, similar to how we scope the provider names like `icu_provider` for the "main" one and `icu_provider_adapters`, `icu_provider_fs`, ... ?

Personally I'm fine with `icu_calendar` and `icu_timezone` though.

**Comment by sffc** [comment]
Note also that the choices here affect the meta crate. All of these should be re-exported by `icu`.

Basically you end up with `icu::calendar::DateTime` and `icu::datetime::DateTimeFormatter`, which I think is fine.

**Comment by echeran** [comment]
An alternative to renaming, in order to mitigate any potential confusion of new users to the crates / codebase, could be through added documentation.  We could have a doc with a graph -- a "visual map" -- of the major crates in a dependency forest graph with nodes color-coded by components (formatter & non-formatter) & utils.  Of course, an extra doc wouldn't have to be strictly coupled with the release, but such timing would be nice to have.

**Comment by Manishearth** [comment]
Yeah, to be clear I'm not really proposing renaming right now, but I do think the names are confusing. Docs might be a good call here.
