### ISSUE TITLE
Implement UTS 35 locale canonicalization

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#218]
icu::Locale does not currently implement full UTS 35 locale canonicalization as defined in [UTS 35 section 3.2.1](http://unicode.org/reports/tr35/#Canonical_Unicode_Locale_Identifiers).  In particular, it does not resolve aliases from CLDR data files, and it does not support adding likely subtags.  This feature is important for a full robust implementation of the locale class.

Note that UTS 35 is currently being updated to clarify the algorithm.

I envision an async method on icu::Locale that takes a data provider, requests the necessary data, and then performs the canonicalization.

CC @FrankYFTang @macchiati

**Comment by zbraniecki** [comment]
I'm wondering if this should be behind a feature. In particular, `icu::Locale` is useful without data, so maybe auxiliary data operations such as `likelySubtags` and aliases should be optional?

`unic-locale` implements the `likelySubtags` via stable table - https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/likelysubtags/tables.rs

**Comment by sffc** [comment]
I agree that icu::Locale is useful without data.  I opened https://github.com/unicode-org/icu4x/issues/219 to discuss guidelines about what enhancements should require features.

**Comment by sffc** [comment]
See also https://docs.google.com/document/d/1x14W-jBfra3Y-Lg-UfnippIMmU29VISI8dSAAUCcRhE/edit

**Comment by sffc** [comment]
Most of the data will come from https://github.com/unicode-org/cldr/blob/master/common/supplemental/supplementalData.xml

**Comment by sffc** [comment]
- @mihnita: It's a big can of worms, but I think we have to do it.
- @sffc: Is it required by the 402 spec? Unsure.
- @sffc: The practical use case is, if you have your OS's language code set to a deprecated language code, ICU4X should normalize it, rather than serving you data from und. Right?
- @mihnita: It's generally very useful to bring things to a canonical form for processing.

**Comment by FrankYFTang** [comment]
I suggest you to wait a little bit till Mark flush out the new spec . The current UTS35 spec is way too vague to implement. Wait for 2 months and we should have a better version published. (Mark should land the spec text soon but will take a while to publish it officially with next CLDR data)

**Comment by zbraniecki** [comment]
> @mihnita: It's generally very useful to bring things to a canonical form for processing.

My take is in line with Mihai's. We should do it, and I'm increasingly confident that it should be behind a `feature`.

If you compile `icu-locale` with that feature, constructor and canonicalization also loop through that logic internally.

**Comment by sffc** [comment]
> If you compile `icu-locale` with that feature, constructor and canonicalization also loop through that logic internally.

Canonicalization requires a data provider, which means a different constructor signature, and we can't pass it to `FromStr`.  So I think it makes the most sense for this to be its own function like `await locale.canonicalize(data_provider)`.

**Comment by dminor** [comment]
I'm planning to work on this as a follow up to the likely subtags work. I'm renominating for discussion to clarify what still remains in scope here now that we support likely subtags. Since we already do some canonicalization in Locale/LanguageIdentifier, it looks to me like the big piece of work remaining is resolving aliases from the https://github.com/unicode-org/cldr/blob/master/common/supplemental/supplementalMetadata.xml data.

**Comment by sffc** [comment]
2021-02-04: The goal is to implement full locale ID canonicalization according to UTS 35.  See this section: http://unicode.org/reports/tr35/#LocaleId_Canonicalization

**Comment by dminor** [comment]
I started looking at this today. My mental model going into it was something similar to the likely subtags algorithm, where we would pass in a Locale and make modifications as necessary. Now that I've looked at the alias data, it turns out that there are aliases for things that are not valid locales, e.g.
```
          "en-GB-oed": {
            "_reason": "deprecated",
            "_replacement": "en-GB-oxendict"
          },
```
In this case, "oed" is too short to be a valid extension. So it seems like what will have to be done here is to implement a more forgiving parser than what we have in the locid crate and then apply the canonicalization from UTS 35 to the results of that parser to build and return a valid Locale.

@zbraniecki Does that make sense to you?

**Comment by zbraniecki** [comment]
Ugh, I'd love to not support those. Can we ignore such legacy aliases? The UTS says to syntax canonicalized first which would reject those and they serve such a nieche purpose :(

**Comment by aphillips** [comment]
All of the grandfathered tags (particularly the "regular" ones) are deprecated and have mappings. Many implementations just match those off the top and replace them with the recommended valid, well-formed tag. The only exceptions are `i-enochian`, `i-mingo`, and `i-default`.

**Comment by dminor** [comment]
The UTS-35 rules are defined to be applied iteratively until the locale can no longer be modified, e.g. given `sgn-DD` as input, first `und-DD` -> `und-DE` is applied, giving `sgn-DE` and then `sgn-DE` -> `gsg` is applied. In the SpiderMonkey canonicalization implementation, new rules are added to avoid iteration, so a direct `sgn-DD` -> `gsg` rule would be added for this case.

The SpiderMonkey code only covers cases for transitive rules that are in the current CLDR data, and errors out if an unsupported case is hit.

For ICU4x I see three possible ways of handling this situation:

- Apply rules iteratively at runtime
- Follow SpiderMonkey and add new rules only for cases in the current data, and error out otherwise (in provider_cldr)
- Try to support all possible cases for transitive rules in provider_cldr, so errors are not possible even when the CLDR data changes.

To a certain extent, this is a trade off between space (adding extra rules) and time (needing to apply rules iteratively at runtime), but I'm also concerned about the implications of missing a case where we needed to compute a transitive rule, and then generating incorrect results at runtime because we don't iterate.

Offhand, I don't think it would be easy to write and test code to cover all possible future cases in the CLDR data.

**Comment by sffc** [comment]
2021-04-09: Apply the rules iteratively.  Make sure performance of inputs that don't require data-driven canonicalization (en-US, sr-Cyrl) is not impacted.  Test performance of common data-driven substitutions like iw/he and nb/no.

**Comment by dminor** [comment]
In the dusty corners of canonicalizing extensions, there are a small number of canonicalization rules that aren't part of the cldr-json supplemental data (https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-core/supplemental/aliases.json).

For example, `und-u-ms-imperial` should canonicalize to `und-u-ms-uksystem`, but this alias is defined in https://github.com/unicode-org/cldr/blob/master/common/bcp47/measure.xml#L14, and `und-Latn-t-und-hani-m0-names` should canonicalize to `und-Latn-t-und-hani-m0-prprname`, but this alias is defined in https://github.com/unicode-org/cldr/blob/master/common/bcp47/transform.xml#L33.

The unfortunate thing is that as far as I can tell, there is no equivalent of the data in these bcp47 xml files in cldr-json.

From my experience with provider_cldr so far, trying to use it to pull a small amount of data from disparate xml files would be awkward at best. Please let me know if I've missed something.

One option would be to advocate for the inclusion of the aliases from the bcp47 xml files in the cldr-json aliases.json file.

Another option would be to follow the SpiderMonkey approach and generate code to handle these rules, instead of being data driven like the rest of canonicalization. Here's an example of code generation [1] and the generated code [2].

[1] https://searchfox.org/mozilla-central/rev/3151f97de27730793c2e298716df760999423f26/js/src/builtin/intl/make_intl_data.py#1172
[2] https://searchfox.org/mozilla-central/rev/3151f97de27730793c2e298716df760999423f26/js/src/builtin/intl/LanguageTagGenerated.cpp#820

@sffc @zbraniecki any thoughts? It seems like getting this into aliases.json would be the best solution.

**Comment by zbraniecki** [comment]
> @sffc @zbraniecki any thoughts? It seems like getting this into aliases.json would be the best solution.

I'm definitely in favor of baking this in. We don't expect to grow those aliases, we hope the list is stable and mostly due to legacy (and we're smarter now so we are not going to introduce new legacy, now, are we?) and the cost of fetching the data from Provider is substantial for such edge case outlier stable data.

My dream would be to only use data provider to provide the "good" data - formats, patterns, etc. and bake all the "obsolete" data in.

**Comment by sffc** [comment]
This should be a data-driven operation with minimal code.  For your imperial/uksystem example, we shouldn't have to write any code to do that transformation; it should be in the data file.

It could be the case that for Unicode extension aliases, we don't canonicalize those in Intl.Locale at all, instead leaving that up to the code that reads from those extension alises.  I think this is the model that the CLDR data was designed around.

So I'd say to ignore things that aren't in aliases.json for now, and open a CLDR ticket to discuss what to do with these other odd aliases.

**Comment by dminor** [comment]
I filed https://unicode-org.atlassian.net/browse/CLDR-14742 upstream. We also have https://unicode-org.atlassian.net/browse/CLDR-14571 to add the timezone.xml data to CLDR JSON, so one solution would be to build on that work to export all of the bcp47 xml to json.

I think things will be easier to work with if all of the required aliases ended up in aliases.json, but I can see the argument for mirroring the structure of the xml as closely as possible.
