### ISSUE TITLE
Naming of DateTimeFormat types

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2180]
Our current DTF naming is the following:

 - We have `DateFormat<C>`, `TimeFormat<C>`, `DateTimeFormat<C>`, `ZonedDateTimeFormat<C>`, taking in a typed calendar. (https://github.com/unicode-org/icu4x/issues/2153 will remove the typed calendar from `TimeFormat`)
 - We have `AnyDTF` and `AnyZonedDTF` taking in `DateTime<AnyCalendar>`s

For the purposes of this discussion, let's call the first set "TypedDTF" and the second set "AnyDTF"

Overall, AnyDTF is more general and better at i18n, however it's heavier and needs more data. TypedDTF is quite useful if all you care about is one calendar. It's unclear to me which one of these we want to put as our "best foot forward" as the default DTF type, if at all.

There are basically three naming options here:

 1. We have AnyDTF and TypedDTF
 2. We have DTF (i.e. AnyDTF) and TypedDTF
 3. We have AnyDTF and DTF (i.e. TypedDTF)

Furthermore, "AnyDTF" and "TypedDTF" are placeholder names, would appreciate more suggestions.

Thoughts?

cc @dminor @gregtatum @zbraniecki @sffc @nordzilla

**Comment by sffc** [comment]
Discussion:

- @zbraniecki - There may be cases where we need to add more types, like numbering system.
- @sffc - I think that's motivation to use `Typed` because we can have whichever types we need, and just one `TypedFormatter` for a particular formatter
- @Manishearth - If we have `Calendared`, `Numbered`, etc., then we can choose a set of types to make generic
- @Manishearth - Would adding more types be a breaking change? I guess it could use default type parameters
- @sffc - I think this won't happen very often and we can do it on major releases
- @Manishearth - Should we do it on DateFormat too?
- @sffc - Yes

Conclusion: `[Zoned]Date[Time]Format` and `Typed[Zoned]Date[Time]Format`

**Comment by Manishearth** [comment]
Fixed by #2298

**Comment by sffc** [comment]
In 2.0 we're changing `TypedX` to `FixedCalendarX`; see discussion:

https://github.com/unicode-org/icu4x/issues/1317#issuecomment-2422927324

This is somewhat consistent with the observation @Manishearth made pre-1.0:

> * @Manishearth - If we have `Calendared`, `Numbered`, etc., then we can choose a set of types to make generic

However, we rejected `Calendared` because the AnyDateTimeFormatter is also "calendared."
