### ISSUE TITLE
PluralRules DataProvider performance

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#231]
I have a pr in #230 to switch PluralRules to use DataProvider.

I took a stab at testing the performance impact of this switch on my performance harness in https://github.com/zbraniecki/intl-measurements/blob/master/unic/pluralrules/src/main.rs

The results are not great.

* Old https://github.com/zbraniecki/pluralrules which uses static data gets `Select 31 numbers for 10 locales: 3045 ns`
* Current master with `io-bincode` gets `Select 31 numbers for 10 locales: 66592 ns`
* Current master with `io-json` gets `Select 31 numbers for 10 locales: 136357 ns`
* #230 PR gets `Select 31 numbers for 10 locales: 725027 ns`

**Comment by zbraniecki** [comment]
Here's a result of `cargo flamegraph -F 100000` on it - https://cloud.braniecki.net/index.php/s/dd8dow5dZXLyyJP

**Comment by sffc** [comment]
`icu-cldr-json-data-provider` is not intended to be fast.  It's intended to be run as an offline tool to generate optimized JSON or Bincode.  Your results are what I expect, and they are not particularly useful, since `icu-cldr-json-data-provider` should not be used in production or other performance-sensitive applications.

`fs-data-provider` is probably faster than `icu-cldr-json-data-provider`, but it, too, is not going to be competitive against your baseline.  What I hope to be competitive against your baseline is a `static-data-provider`, which I have not yet written.

**Comment by sffc** [comment]
An interesting benchmark would be InvariantDataProvider, which is the fastest possible thing implementing DataProvider.  Hopefully that is competitive against what you had before.  If it's not, then it suggests that the CowableAny technique incurs a nontrivial performance cost.

**Comment by sffc** [comment]
I think the main reason why `icu-cldr-json-data-provider` is not competitive is because everything is owned (cloned).  There are no borrows.  The reason I did it this way is twofold:

1. In order to make data borrowed, I'd need to read the CLDR JSON into a string, and then self-reference slices of that string.  However, self-references are not easy to do in Rust.
2. It's not clear how to make a Serde struct support both owned and borrowed data. https://stackoverflow.com/questions/63201624/how-do-you-make-a-serde-struct-work-with-both-borrowed-and-owned-data

The idea is that in a production environment, you can either read from static data, in which case a `Cow<'static, str>` can work, or you read only small pieces of data, in which case making it owned data is fine.  `icu-fs-data-provider` only opens data for one locale at a time, instead of parsing the whole CLDR JSON file, which should come at a performance boost.

**Comment by zbraniecki** [comment]
My hope is that we can get something competitive with `io-json` with DataProvider. I'll try `icu-fs-data-provider`

**Comment by zbraniecki** [comment]
* `InvariantDataProvider` - `Select 31 numbers for 10 locales: 5783 ns`

How do I produce data for `icu-fs-data-provider` for all locales I need for my test?

**Comment by zbraniecki** [comment]
I think one thing is that my current data provider caches parsed rules, while here I'm re-parsing them on each new instance, because DataProvider returns textual form.

Could we consider checking how it'll look to store parsed rules (memory, size, perf)?

**Comment by zbraniecki** [comment]
Or some way to cache result?

**Comment by sffc** [comment]
https://github.com/unicode-org/icu4x/tree/master/components/fs-data-provider/tests/testdata/json_plurals_37 contains a limited set of locales that you can use with FsDataProvider.  If you want to generate the full set, run the `icu4x-cldr-export` binary tool from the fs-data-provider crate.  You can also invoke the tool programmatically as described in https://unicode-org.github.io/icu4x-docs/icu_fs_data_provider/export/index.html

It would be great to consider a different data model to return from the DataProvider with the AST already parsed.  However, then we'd basically be putting the job on Serde to parse the JSON into the AST at runtime, so I don't know what the performance improvement would be.  This would be a good test to run.

**Comment by zbraniecki** [comment]
Thank you! I was able to generate `compact` data and the result is:
* `Select 31 numbers for 10 locales: 86562 ns`

So, to sum it up:

|                    Test                      |   Time   |
| -------------------------------------------: | --------: |
| unic-pluralrules (static)              | 3045 ns |
| icu-plurarules (bincode)              | 66592 ns |
| icu-plurarules (json)              | 136357 ns |
| icu-plurarules + CldrJsonDataProvider | 725027 ns |
| icu-plurarules + InvariantDataProvider | 5783 ns |
| icu-plurarules + FsDataProvider (compact)| 86562 ns |

I think we're in a good place!

Two things we can do to play with performance is:
* Remove the examples (don't expect large diff since I use streaming parser, but size is smaller so maybe buffer will be smaller)
* Consider shipping pre-parsed rules (may blow up size and not sure about memory)

**Comment by zbraniecki** [comment]
In #233 I was able to strip examples which led to a small win: `Select 31 numbers for 10 locales: 76485 ns`.

With that PR, `FsDataProvider` beats `icu-pluralrules json` and should lead to another nice win when we plug `bincode`
