### ISSUE TITLE
Collator: why are the options not a bag?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2415]
Most of our options are plain structs with public fields, as the style guide says. However, the collator options have getter/setter methods. Why? Can we fix it before 1.0?

CC @hsivonen

**Comment by hsivonen** [comment]
We discussed this previously. The options for the collator support the notion of explicitly-set value and left-at-default values so that the left-at-default values get overwritten with locale-specific defaults before the collator actually uses the options. We discussed previously whether it should be possible to set a value back to default after setting it so an explicit value, and we decided that setting a field back to default should be supported. That's why the setters take `Option`s to be able to take `None` as "back to default".

**Comment by hsivonen** [comment]
To organize the reply a bit more:

* Because the actual locale-dependent defaults are merged in _later_, the options keep track of what was explicitly set and what was left at default, so that the later-merged stuff overwrites only the not-explicitly-set parts. We can't just initialize the fields to defaults and forget about what's explicit and what's not.
* The getters give a view to what the current values are without complicating the return value with explicitness information. Obviously, before the locale-dependent defaults have been merged in, this reflects the default defaults that apply to locales that don't override defaults. (IIRC, only Danish, Maltese, Thai, and Canadian French override defaults.)
* Initially I was going to make the explicitness state be entirely encapsulated hidden state without having an ability to reset a field back to "default" state. However, when we discussed this (on 2022-02-07, I think) in the light of the ICU4C and ICU4J APIs, we arrived at the conclusion that there should be API surface to reset back to default. That's why I changed the setters to take `Option` of what they took originally to make `None` reset to the default "not explicitly-set" state, despite this making the common case feel a bit clunky due to having to wrap the actual argument with `Some(...)`.
* Since originally the "explicitly-set" state was not supposed to be directly settable, the object had internal hidden state, which excluded an all-public options bag design.
* After making the explicitness resettable, I didn't seriously entertain the idea of having an all-public options bag with `Option` fields with `None` signifying default, since I thought the current representation (`u32`) was easy to pass over FFI while `Option`s don't pass nicely by value through the FFI and that was the compact code that I already had. The thinking of what's FFI-friendly and what's not predated Diplomat and was based on thinking about what a manually-written FFI might look like. (I considered it a possibility to replicate the setters and getters in C++ so that they'd operate on the `uint32_t` representation directly.)

**Comment by sffc** [comment]
OK! Thanks for the clarification. My initial thought would be for the options bag to have a bunch of fields that are all `Option<Foo>`. It's true that there is some trickiness getting that to work over FFI, but that's solvable by making the FFI layer use a different style than the Rust layer (something we alreaddy do in various situations).

**Comment by sffc** [comment]
Discussion:

- @zbraniecki - `set_defaults` sounds like `merge` and I would like it to have that name
- @sffc - I don't see any other invariants here

Decision: make it an options bag with public fields (and non_exhaustive)
