### ISSUE TITLE
Delete format_to_write functions or reorder arguments

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2511]
Feedback from @markusicu:

> TypedDateTimeFormatter::format_to_write has an in+out argument and an input argument, and the output argument comes before the input argument, which is not the convention in C/C++.  Also, in other place, the name of that argument is `sink`, but here it is only called `w`, which is inconsistent and not as readable.
>
> Do you need format_to_write()?  If it is a convenience method that isn’t all that convenient, then maybe you don’t need it.  Maybe we don’t – maybe we only need format() and format_to_string() – and we don’t need format_to_write which is just like `.append()` in Java.

**Comment by robertbastian** [comment]
+1 to removing `format_to_write` and `format_to_string` as those are available through `format(...).write_to` and `format(...).write_to_string`. The current `format_to_string` implementations also don't respect the size hint, and it's inconsistent with other components where `format` is the only method.

**Comment by markusicu** [comment]
A basic format_to_string() convenience method is generally nice.

**Comment by sffc** [comment]
Another advantage of `format_to_string` is that it doesn't require importing the trait.

**Comment by robertbastian** [comment]
> A basic format_to_string() convenience method is generally nice.

It's not really done in Rust though. You implement `Display` to get `to_string`, `write!`, `print!`, `format!`, etc.


There are several things that would be nice to achieve:
1) have a preallocating `to_string`
2) have support for `core::fmt`
3) not require extra trait imports
4) not have redundancies in the API surfaces that lead to users doing the wrong thing

For 2) we implement `Display`, which gives us a non-preallocating `to_string` (`.format(...).to_string()`). For performance critical users, 1) is still achievable as `.format(...).writeable_to_str()`, however requiring an extra trait import. I'm worried that if we have add `format_to_string` for 1), users will use

`write!(f, "Foo bar {}", f.format_to_string(...))` instead of the more efficient 

`write!(f, "Foo bar {}", f.format(...))`

Rust's `fmt` package is a great API for avoiding intermediate strings. I guess the question is, will more users produce standalone strings from our APIs, or use them to build larger strings? Will non-Rust-power-users be able to recognize that the `format_to_string` version does an extra allocation?

(Note that `String::from(self.format().write_to_string())` might allocate two strings, it should be `self.format(...).write_to_string().into_owned()`)

**Comment by sffc** [comment]
I don't think the risk of users doing the wrong thing is very high. The short method `format` is the main one, and the longer one `format_to_string` is the specialized convenience one. The docs of `format_to_string` can reiterate this.

Also, the fact that we're debating the most efficient way to make a string from a writeable means that this is something complex enough to justify a helper method.

**Comment by sffc** [comment]
Here are a bunch of ways to make a string:

```rust
fmt.format().to_string() // use ToString via Display impl
format!("{}", fmt.format()) // use Display impl directly
String:from(fmt.format().write_to_string()) // use String::from(&str)
fmt.format().write_to_string().into_owned()
```

The last one is most efficient, but this confusion can be remediated if we just have `fmt.format_to_string()`

**Comment by robertbastian** [comment]
The third one does two allocations, it creates a String from a Cow<str> that will in 99% of the cases be owned.

The first two options is what everyone is used to and will want to use, but sure let's add this, but everywhere.

**Comment by sffc** [comment]
- @zbraniecki - I'm concerned about the performance impact. It seems `format_to_write` could have better performance characteristics since it doesn't have an intermediate object.
- @sffc - The intermediate object is just a bag of pointers.
- @robertbastian - I have benchmarks in the PR.
- @Manishearth - Adding it back is easy. We can do it at any time if people want it. I think we should wait for someone to show a need for it.
- @zbraniecki - Recognizing the importance of `format_to_write` requires recognizing it as a bottleneck, like I was doing with gecko benchmarks.
- @robertbastian - It looks like it is about 6% slower on Criterion (the main components benchmark)
- @zbraniecki - Mainly I would like to preserve the knowledge about this being an option.

Action:

- @zbraniecki to review @robertbastian's PR and decide on the right way to document this

**Comment by sffc** [comment]
- @robertbastian - Do we want `format_to_string` on everything that has `format`?
- @sffc - I think yes, for reasons I listed above.
- @zbraniecki - +1
- @robertbastian - It's annoying but I can see it being useful.
