### ISSUE TITLE
More docs cleanups in list, decimal, plurals, normalizer

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2590]
More feedback from @markusicu regarding docs:

In `icu_list`:

- `ListFormatter::format` - docs are jarring because the second sentence mentions “first layer of parts” without introducing “parts”.  Should say that it implements Writeable and also provides Parts.
- An example of the `Writeable::with_part()` would be helpful to the user.  Maybe, FormattedList would be a good place to have the example.  There exist unit tests, but they are not turned into doc tests
- Is there any documentation on `writable::Part`?  The struct just uses 2 strings (category, value).  Java uses opaque objects, ICU uses integers.  It’s okay to use strings in ICU4X to be non-opaque and extensible, but you just need to document what they are.  There are constants like icu::list::parts::{ELEMENT, LITERAL}, but the Rust docs don’t show you the `category` and `value` unless/until you click on the source.  There should be documentation on what `category` and `value` mean.

`icu_decimal`:

- May want to rename “Bengali” to “Bangla” in the lib.rs examples docs page
- The syntax `1000007.into()` is interesting – very clever and very weird.  It’s not very readable.  The compiler has to read ahead lines of code to find usages in call sites that constrain the type
- Consider not using `.into()` in `1000007.into()`. You’re converting to a FixedDecimal without even importing FixedDecimal
- The Bangla digits look confusing compared to Latin decimal digits.  But maybe that is the point?
- The biggest APi in `FixedDecimalFormatter` is actually in the `FixedDecimal` itself

`icu_plurals`:

- Docs has text for “Language Plural Rules” and “Plural Category” links also formatted as code when they shouldn’t be.

`icu_normalizer`:

- `Normalizer::normalize_utf8()` - in docs, change “Errors” to “Ill-formed [byte] sequences” in “Errors are mapped to”.  Ditto for all methods taking UTF-8 strings that use the broad word “error” for this narrow meaning.  Ditto for methods in ComposingNormalizer and elsewhere.

**Comment by robertbastian** [comment]
Bangla vs Bengali: we currently use a mix of both in our code, and Bengali [in our API once](https://icu4x.unicode.org/doc/icu/properties/struct.Script.html#associatedconstant.Bengali). I think this is the least desirable state and we should align on one name. 

CLDR calls the language "Bangla", however the Wikipedia article for both the script and the language refer to them as "Bengali", with the [justification](https://en.wikipedia.org/wiki/Talk:Bengali_language#Shouldn't_%22Bengali%22_be_replaced_with_%22Bangla%22?) that this is the commonly used English name, no matter what the Bengali constitution says. I personally had never heard the name Bangla before, and didn't even make the connection that it's the same as Bengali. I think because our API and documentation is in English, and our users are not i18n experts familiar with endonyms for all the world's languages, we should use Bengali.

**Comment by sffc** [comment]
When it comes to region/language naming, I tend to be of the opinion that we should set a good example and use the name that the people of that region/language prefer, not the anglicized/colonial version.

The CLDR script code is not a great example, because that is a computer identifier that was chosen when the script was encoded into Unicode, and identifiers never change to reflect the latest best practice of naming.

**Comment by robertbastian** [comment]
I think we should use names that the majority of the population using that language will understand. Our task is to model the status quo, not to decolonise the English language.

**Comment by Manishearth** [comment]
> The syntax 1000007.into() is interesting – very clever and very weird. It’s not very readable. The compiler has to read ahead lines of code to find usages in call sites that constrain the type

FWIW this is very normal Rust syntax. Type inference is the bread and butter of Rust programs. In general while "what the compiler is doing" is a common thought process for C++, especially around preprocessor ordering, it's not super common in Rust: the compiler just does it and you don't think about it.

Also, the compiler architecture is not such that it's actually "reading ahead", it's resolving all of these things in one holistic pass. The compiler does not see code "in order", that's more of the design of C and C++.

I'd rather stick to idiomatic Rust. I think there is an argument to be made for using more explicit types in examples, but the syntax being weird doesn't really line up for me.

**Comment by Manishearth** [comment]
> You’re converting to a FixedDecimal without even importing FixedDecimal

Some of this is a matter of norms: in Rust, glob imports are not the norm, so not needing to import ten types to use an API is considered a plus. Here by importing the formatter you get something on which to bolster your inference, so FixedDecimal comes in for free, which is typically considered a good thing.


In cases with a lot of inference people may start writing stuff out explicitly for the purposes of readability, but this is small enough to not be a huge deal.

Bear in mind: these examples are right above the docs of the relevant function, so people can *see* what the type was, and click it. The inference isn't confusing to the compiler, and it _can_ be confusing to programmers but this is not sufficiently complex for that to be the case.

> The Bangla digits look confusing compared to Latin decimal digits. But maybe that is the point?

Yeah I picked them specifically as:

 - Non Latin to show off capabilities (mostly restricts us to Eastern Arabic / Indic)
 - Not RTL because that can be a mess in CLI
 - Not from a language I can speak to not privilege languages I speak when it comes to our examples
 - Still from a writing system I can _read_ so I could spot check when I was writing some of these trsts

**Comment by robertbastian** [comment]
> In general while "what the compiler is doing" is a common thought process for C++, especially around preprocessor ordering, it's not super common in Rust: the compiler just does it and you don't think about it.

It's not just the compiler, it's also the reader. Reading this line by line, I think `let fixed_decimal = 1000007.into();` is a speed bump, because now I have to keep this untyped variable in my memory until I find the place where it's used. I think if we don't explicitly type it, there's not much value in assigning a name to it, and we could just inline it.

**Comment by Manishearth** [comment]
I guess my perspective is that we're giving it a separate variable precisely because we're not typing it: the variable name should be a sufficient hint for the use case of the compiler.

(also because we wish to draw attention to it)

I understand the impact on the reader, I mentioned it in my comment, I'm just saying that in Rust it's not typical to use explicit types at _this_ level, because the impact on the reader isn't huge and it's easier to scan. Does it actually matter what the precise type was? At a bird's eye view when scanning, the number was converted to "whatever type `.format()` needs". If you care about knowing what that type is, you can look at the variable name for a hint, or in the case of the example, the docs right below.


To give a bit of an idea why I'm pushing back: in Rust explicit types often give the impression that the explicit type was _needed_ precisely because the norm is to rely on inference as much as possible. This makes people start expecting there to be complicated trait things going on under the hood. I see `let foo: Foo = y.into(); frob(foo)` and my impression is that `frob()` is doing something fancy, or the Into impl is complicated. This isn't always the case (explicit types are the norm in sufficiently complex code), but here the code is otherwise simple enough that the extra line noise feels pertinent.

And like I mentioned earlier, people tend to copy code from examples without cleaning up stuff like this.

**Comment by zbraniecki** [comment]
> I'd rather stick to idiomatic Rust.

I'm with Manish. I think the "I'm not used to Rust so it looks odd" is not something we should be fixing by diverting from Rust patterns.

I want to recognize Markus feedback, and the bits that look odd to him are useful, but I'd much rather document them extra, rather than rewrite them so they look familiar to someone unfamiliar with Rust.

For example, in examples `let fixed_decimal = 1000007.into();` could be written as `let fd: FixedDecimal = 1000007.into();`

**Comment by zbraniecki** [comment]
Ah, I see that that's what Robert is suggesting and Manish is pushing back on.

I'm ambivalent on the solution. I disagree with Robert that it's a "speed bump", but I wouldn't mind `let fd = FixedDecimal::from(100_000);`.

**Comment by sffc** [comment]
What persuaded be to @markusicu's suggestion was that FixedDecimal is where the bulk of configurations lie for FDF. You're going to need to know what it is and import it most of the time you use FDF. So my preference is narrow to FixedDecimal and I'll abstain from the general question of when to use from vs into.

**Comment by Manishearth** [comment]
@zbraniecki yeah i'm also not pushing back _strongly_ on `let fd: FixedDecimal = foo.into()`, I just don't want us to do it too often. I'm fine if others feel strongly about having more explicit stuff here.

**Comment by robertbastian** [comment]
Reopening for Bangla discussion

**Comment by Manishearth** [comment]
on that note I will say that given "Bangladesh" exists I would be rather surprised if the majority of the English speaking population would _not_ understand what Bangla is (though there is a chance they would not realize it is the exact same as Bengali)

As an internationalization library I feel comfortable using language names in a closer-to-native rendition, I actually wouldn't see a huge problem if we started using the native scripts, even: for the purposes of the examples people just have to recognize that it is _some_ other language.

**Comment by sffc** [comment]
Decision: follow CLDR precedent for this and similar issues. Be consistent across all of ICU4X. Optionally add a unit test enforcing that the name is the same as in CLDR language display name data.
