### ISSUE TITLE
Error names should be consistent with crate names

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2612]
In my opinion:

`icu_datetime::DateTimeFormatterError` should be `icu_datetime::DateTimeError`

`icu_calendar::DateTimeError` should be `icu_calendar::CalendarError`

@Manishearth @zbraniecki

**Comment by Manishearth** [comment]
My (not super strong) opinion is that icu_calendar is primarily a crate about dates and times, and it just happens to be nameed calendar because datetime is already taken (since datetime_formatter is too long). The name length matters less for the error so we can give these errors the good name. I find that CalendarError feels weird coming out of date/time types (whereas DateTimeError seems okay coming out of calendar types)

But I do see that uniformity is nice.

**Comment by sffc** [comment]
## Rant regarding crate names

We're in a situation where the "good" names are taken by the formatters, since we don't include "formatter" in the crate/module names. `icu_decimal` is FixedDecimalFormatter and `fixed_decimal` is FixedDecimal.

In this case, `icu_datetime` took the good name, so we're stuck with `icu_calendar` for the input type. I think that's just fine. Most of the content of `icu_calendar` is closely coupled with calendar systems; if we didn't have calendars, we likely wouldn't need this crate.

In the medium term, I would like to see an additional super-low-level crate that contains the new IXDTF parser and other primitives, without explicit knowledge of time zones or calendar systems.

## Rant regarding using crate names as error name prefixes

My preference for a long time has been to export the crate's error module as simply `Error`, since most people never need to import this type, and it makes it easier knowing that you can always `use icu::whatever::Error` and it works. However, we decided long ago that explicit namespacing should apply to error types. At least now we know that `icu::whatever::WhateverError` will work. However, the current error names in icu_datetime and icu_calendar break that rule. You actually need to go to the docs page to know what the name of the error is.

In addition to being more guessable, using crate names in the error name also reduces the amount of bikeshedding. I'm not sure I would have chosen `DateTimeFormatterError` and `DateTimeError`, for example, separate from not using the crate name.

**Comment by zbraniecki** [comment]
> My preference for a long time has been to export the crate's error module as simply Error, since most people never need to import this type

My position is moving closer to yours over time. I used to prefer separation between types that are commonly imported into mixed-component uses (say, main.rs imports `icu_datetime::Error` and `icu_plurals::Error` and then it's just easier to have `DateTimeError` and `PluralsError` than to rename in import), and types that are rarely used outside of internal single-module code (say, `icu_datetime::pattern::runtime::parser::Error` is ok, because it's unlikely that ICU customers will want to import it alongside other error types too often).

I'm now moving toward `use component::module` and `module::Error` more often. I think it's a good solution for scenarios where you have multiple modules or components mixed together, and the `module::ModuleError` doesn't really help too much while getting longer and redundant.

**Comment by sffc** [comment]
Please vote:

https://docs.google.com/document/d/1LnAeOmP6AfUqKY0NOzOX5CPggS6ZDEEM397uSnMiI3o/edit#

**Comment by Manishearth** [comment]
> My preference for a long time has been to export the crate's error enum as simply `Error`, since most people never need to import this type, and it makes it easier knowing that you can always `use icu::whatever::Error` and it works. However, we decided long ago that explicit namespacing should apply to error types.

I'll say that around 1.0 Rust tried to pick this up as a consistent style guideline (you can see this reflected in a lot of stdlib APIs), and everyone hated it and didn't follow it. People are reluctant to refer to _types_ qualified by an imported module/crate name[^1], and folks tended to rename the type to CrateNameError anyway, so it wasn't worth it (and people stopped doing it after a while).

So, from experience, this is nice in theory, but in practice nobody really does it right and everyone hates it.


 [^1]: I think it's because the convention that has grown is that everything except functions (and enum variants) should be directly imported, with there being a strong convention that free functions — which are rare — should usually be used by referencing their module

**Comment by sffc** [comment]
We already formed consensus to move forward with namespaces to hold datetime fields (fields::Hour) and locid subtags (extensions::unicode::Value).

I think the case is _even stronger_ to do this with Error, because

1. Most people never import the error type thanks to Eyre and the ? operator
2. Those that do are most likely implementing From, possibly from multiple sources; and I find implementing From is easier with fully qualified names anyway (more readable, more predictable, and easier with optional dependencies)

**Comment by Manishearth** [comment]
> * Most people never import the error type thanks to Eyre and the ? operator

I don't think this is quite correct; Eyre is used more in the (non-low-resource) application space; e.g. rustc does not and likely will never pervasively use Eyre (though it might use it in some contexts, it's big). Libraries tend to do their own errors.

> Those that do are most likely implementing From, possibly from multiple sources; and I find implementing From is easier with fully qualified names anyway (more readable, more predictable, and easier with optional dependencies)

Again, I think this works well in theory, in practice this leads to people renaming errors and being unhappy about it. I feel like there's some aversion in the community to using types by fully qualified path more than once in a file (and From impls need at least two, often more if it's a From on an enum)

Actually I bet the enum is a big part of it, probably because `icu_foo::Error::Variant1(..)` looks ugly; I think while there's an aversion to FQ paths in type names, there's an _even larger_ aversion to that for variants.

Personally the reason I was in favor of namespaced datetime fields was that datetime fields are rather rare a use case and it feels fine to have it be a lil ugly then. I'm more in favor of namespaced types in APIs when:

 - The _same crate_ has a lot of types that will be similarly named
 - The types are used in a group. (e.g. people namespace syn/diplomat/rustc `ast` a bunch, that works nicely)

(personally I'm more lax about when I namespace types in my own imports, but that's the general guidelines I follow for API design)

**Comment by sffc** [comment]
Going with option 5 since options 1-3 all have vetoes, options 5 and 4 have similar scores, and 5 is easier to implement without needing additional bikeshedding.
