### ISSUE TITLE
Rename *BreakSegmenter to *Segmenter

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#2663]
`WordBreakSegmenter` is a weird name - we segment into words, not word breaks. `WordBreakIterator` makes sense because we iterate over word breaks.

So I suggest either `WordBreakIterator` or `WordSegmenter` and Shane and Ting-Yu like `WordSegmenter` more.

Same goes for `LineSegmenter`.

**Comment by sffc** [comment]
LGTM on `FooBreakSegmenter` to `FooSegmenter` for all four segmenter types.

Note that we still need `FooBreakIterator` as the mutable iterator type that the segmenter returns when given a string.

**Comment by aethanyc** [comment]
cc @makotokato

**Comment by echeran** [comment]
I think the general term for this is segmentation.  However:

- When it comes to developers who use i18n APIs, people are familiar with "BreakIterator" because of ICU.
- Meanwhile, in the localization industry, translators will use the "segmentation", and they mostly use it as synonymous for the process of taking a full document and splitting it into text units, which are themselves split into individual sentences, and the sentences are referred to synonymously as "segments".
- The Unicode spec refers to this in one place as breaking, and another place as segmentation:

<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax">Granularity</th>
    <th class="tg-0lax">Unicode technical report</th>
    <th class="tg-0lax">ICU4J</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">grapheme cluster</td>
    <td class="tg-0lax" rowspan="3"><a href="https://unicode.org/reports/tr29/">UAX #29 Unicode Text Segmentation</a></td>
    <td class="tg-0lax"><code>BreakIterator.getCharacterInstance()</code></td>
  </tr>
  <tr>
    <td class="tg-0lax">word</td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal"><code>BreakIterator.getWordInstance()</code></span></td>
  </tr>
  <tr>
    <td class="tg-0lax">sentence</td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal"><code>BreakIterator.getSentenceInstance()</code></span></td>
  </tr>
  <tr>
    <td class="tg-0lax">line</td>
    <td class="tg-0lax"><a href="https://unicode.org/reports/tr14/">UAX #14 Unicode Line Breaking Algorithm</a></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal"><code>BreakIterator.getLineInstance()</code></span></td>
  </tr>
</tbody>
</table>

I'm currently not too opinionated on which prior art we're consistent _with_, so long as our naming _internally consistent_.  I liked the way @sffc distinguished in chat that Segmenter alludes to the ECMA-402 immutable design, and BreakIterator alludes to the ICU mutable design.

**Comment by zbraniecki** [comment]
> When it comes to developers who use i18n APIs, people are familiar with "BreakIterator" because of ICU.

This argument does not hold much water for me. We're about to release `Intl.Segmenter` in JavaScript. We're writing API for 10y+ horizon, and I suspect that with ICU4X+ECMA-402 we have control over which term is the default one.

The argument about localization industry already using the term segmentation reads to me as an argument for Segmenter as a concept.

I support `FooSegmenter` producing `FooBreakIterator` for each input. My only grievance was with `FooBreakSegmenter`.
