### ISSUE TITLE
What do I need to do to get `collator/reord@1` ?

### ISSUE THREAD

**Issue by glittershark** [unicode-org/icu4x#2692]
I'm trying to generate a BakedDataSource that provides enough data to construct a `Collator`. I have the following build script:
```rust
use icu_datagen::{keys, CldrLocaleSubset, CollationHanDatabase, Out, SourceData};
use icu_locid::langid;

fn main() {
    icu_datagen::datagen(
        Some(&[langid!("en-US")]),
        &keys(&[
            "collator/data@1",
            "collator/prim@1",
            "collator/dia@1",
            "collator/jamo@1",
            "collator/meta@1",
            "collator/reord@1",
            "normalizer/nfd@1",
            "normalizer/nfd@1",
            "normalizer/nfdex@1",
        ]),
        &SourceData::default()
            .with_fast_tries()
            .with_cldr_latest(CldrLocaleSubset::Full)
            .unwrap()
            .with_icuexport_latest()
            .unwrap()
            .with_collation_han_database(CollationHanDatabase::Implicit),
        vec![Out::Module {
            mod_directory: "src/gen".into(),
            pretty: true,
            insert_feature_gates: false,
            use_separate_crates: true,
        }],
    )
    .unwrap();
}

```

Which fails with: 
```
hread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DataError { kind: Custom, key: Some(DataKey{collator/reord@1}), str_context: Some("No data") }'
```

It's unclear to me what other options I need to pass to get this to work.

**Comment by robertbastian** [comment]
Argh, baking doesn't support emtpy keys, but apparently collator generates some. I'll have to look into how we can solve this.

**Comment by Manishearth** [comment]
@glittershark for more background, the bug you're experiencing is because for collation a bunch of this data is optional; and English doesn't need some of those keys (like `collator/reord@1`). The databake datagen is unfortunately broken when it encounters a key that has no data to generate.

While we work on fixing this, the easy fix would be to either include a second locale like `ja`, or to just comment out `collator/reord@1` and any other panicky entries. You will have to use `BakedDataProvider` as an `AnyProvider` (i.e. using `_with_any_provider`) instead of with the `_unstable_provider()` functions, but that isn't that big a deal.
