### ISSUE TITLE
[datetime] Style vs Length vs Width

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#273]
There's a combination of inconsistent names around what ECMA402 calls `dateStyle` and `timeStyle`. Shane raised this as a question whether we really should follow ECMA402 here and name it `style`, or use another term.

UTS #35 has a name `dateFormatLength`and `timeFormatLength` - https://unicode.org/reports/tr35/tr35-dates.html#dateFormats

```
<!ATTLIST dateFormatLength type ( full | long | medium | short ) #REQUIRED >
<!ATTLIST timeFormatLength type ( full | long | medium | short ) #REQUIRED >
```

and is followed by this sentence:

> Standard date and time patterns are each normally provided in four **types**: full (usually with weekday name), long (with wide month name), medium, and short (usually with numeric month).

(emphasis mine)

So, we could use widths, lengths, types, or styles. 

My problem with `styles` is that it misses an opportunity to convey that this is about how long the returned value will be. Style can be "Informal"/"Formal" or "Artistic"/"Technical" etc. "Width" and "Length" are scoped down to clearly indicate that we're talking about widths.

On the other hand, `StyleBag` seems reasonable, but `LengthBag` and `WidthBag` kind of feel off linguistically.
We also unlikely going to have another use for the word `style` in DateTime context, so we could let the wider semantical scope be occupied by it I think.

Either way, if we want to stick to ECMA402, we could suggest naming refactor there and see what comes out of it. For us, chosing and changing the name is not as drastic, especially early on.

**Comment by sffc** [comment]
For the meta question: This is an area where we need to decide how strictly to adhere to ECMA-402 APIs.  I think we should replicate behavior as much as possible, but if we establish a better name than 402 for some type or option, I think it should be in scope to adopt the better name.  This is especially true since we have multiple 402 authors working on ICU4X, so we are "qualified" to pass judgement on our own past work.

For the specific question: I have a slight preference for Length.  Text is linear (one-dimensional).  Width implies a second dimension.  [This post on Quora](https://qr.ae/pNPh6K) summarizes the difference:

> If you are only concerned with one dimension of something, then that one dimension will usually be called “length”: the length of a piece of string, the length of a person’s legs or arms.
>
> If you are concerned with two dimensions, they will usually be length and width (or, equivalently, breadth).

An argument could be made that "width" is appropriate because it means the number of horizontal pixels on a computer screen.  However, this argument does not work for vertical scripts like traditional Mongolian.

**Comment by sffc** [comment]
2021-03-25:

- @kpozin suggests "verbosity"
- @Manishearth suggests "compactness", "density", "extent"
- @echeran suggests "size", "brevity"
- @nordzilla suggests "magnitude", "presentation"
- @nciric suggests "composition"
- @zbraniecki suggests "format"

**Comment by sffc** [comment]
2021-03-25: Based on a straw poll, we will go with "length".  For now, we will keep the same enum values, but may reconsider their names.

Since this mostly affects DateTimeFormat right now, I'm assigning to Zibi to perform the refactoring for 0.2.
