### ISSUE TITLE
[naming][bikeshedding] `*Format` vs `*Formatter`

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#274]
Why do we have `DateTimeFormat` and not `DateTimeFormatter`? This API is a formatter, not a format, and it produces `FormattedDateTime`.

Is it just copypasta from ECMA402? I see ICU4C having `DateTimeFormat` and `NumberFormat` and `NumberFormatter`...

**Comment by zbraniecki** [comment]
My take is that we should have `*Formatter`.

**Comment by sffc** [comment]
My understanding of the history is that the original DateFormat and NumberFormat were conceptualized as **nouns** with a 1-to-1 mapping to a particular format of a date or a number.  For example, one might have an object corresponding to a French month-day format.  Then, the format is *applied* to the number/timestamp to produce the formatted string.

A *format object* could be used for other types of operations, too.  For example, it could be serialized into a string representation.

In modern usage, it's common to have objects that are **workers** rather than plain nouns.  So, one might have an object that processes a timestamp and produces a French month-day string.

**Comment by zbraniecki** [comment]
Thank you for the explanation!

I think the way we are establishing our API is closer to the latter. We don't have `process`, but we have `format` method which generates `FormattedX` and the object processes timestamps to generate it.

I think this is one naming thing I'd like to nominate for 0.1 to make sure we have at least the core components names settled.

**Comment by mihnita** [comment]
++1 for `*Formatter`

**Comment by zbraniecki** [comment]
We discussed it on the call and decided that there is a reason to delay the decision post 0.1. `Format` is consistent with ECMA402, `Formatter` would be consistent with ICU4C modern APIs. Let's keep looking at it, we have luxury to be able to rename for 0.2 if needed.
