### ISSUE TITLE
Create a SimpleFormatter util for common patterns

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#277]
ICU4X should have a SimpleFormatter class like ICU4C that handles patterns like these.  Can you make a follow-up issue and put in a `// TODO(issuenumber)`?

_Originally posted by @sffc in https://github.com/unicode-org/icu4x/pull/202#r495546260_

**Comment by dminor** [comment]
Hi @zbraniecki, I'm interested in working on this. I've had a look at the SimpleFormatter class in ICU4C, but I'm finding it difficult to get the full context from the pull request for #202. I was wondering if you could provide a few more details on what code we're hoping to clean up by adding SimpleFormatter? Thank you!

**Comment by sffc** [comment]
This is used for patterns like `{0} at {1}` (date at time) in DateTimeFormat.  It's also used for list format, measurement units, currency long names, and numerous other patterns in CLDR.

Take a look at ListFormat in ICU4C.  It exercises a lot of interesting code paths related to simple format.  I suggest that the ICU4X SimpleFormat should be designed to work well with ListFormat, because if it does, it should work well for any other use case, too.

We should think about how to carry field information with SimpleFormat (formatToParts in ECMA-402).  This ties in closely with #135.

Finally, it might be nice to evaluate a Serde version of SimpleFormat.  I imagine that we will want to put simple formats into data files.  The ICU4X serialization of a SimpleFormat need not be `{0} at {1}`; it could be, for example, an array-like structure such as `[0, "at", 1]` that can be rapidly encoded and decoded in JSON or Bincode.

**Comment by dminor** [comment]
Thank you for the suggestions!

**Comment by zbraniecki** [comment]
I agree with Shane that it ties to #135, but I think we don't have to make it a blocker. We can add a `utils/simple-formatter` which just provides a parser and resolver for now, and we can improve it with `format-to-parts` bits later.

I'm also not sure if I'd like to deeply bind it into `serde`. I see `serdes` custom serializer/deserializer as a valuable tool for writing resource formats, but for simple parsing it adds a lot of boilerplate for little gain.

My suggestion would be to start by just extracting the bits out of `datetime` crate that parse simple formatter and an Enum for storing `Position/Literal` types as `[0, "at", 1]` and resolving them with some values passed as `0` and `1`.

We should monitor #319 and its Unicode dependency to understand if the order of:

1) Take `[0, "at", 1]`
2) Replace `0` with `[Token(Year), Literal(" "), Token(Month)]`
3) Replace `1` with `[Token(Hour), Token(DayPeriod), Literal(":"), Token(Minute)]`
4) Store/Return as `[Token(Year), Literal(" "), Token(Month), Literal("at"), Token(Hour), Token(DayPeriod), Literal(":"), Token(Minute)]`

is the correct one, but I think it's a good start.

For that abstraction to work, we'll need to better understand how to hook simple formatter into "real formatter", because the `Vec<SimpleFormatterElement>` is not going to be good enough since simple formatter won't know about datetime, listformat and other tokens.
On the other hands those formatters will need to handle `Literal`, so the design of such abstraction should maybe be generic over `Element` enum of the customer crate so that `SimpleFormatter<DateTimeElement>` can format for datetime etc.?

**Comment by sffc** [comment]
2021-01-15: Implement as an iterator. Does not need to block on #135.

**Comment by sffc** [comment]
I think SimpleFormatter will be an important step in our goal of reducing the massaging of data at runtime.  I should at least be able to put SimpleFormatter as a field of the data provider struct.

**Comment by zbraniecki** [comment]
Noted. I have it almost fully operational. Massaging some lifetimes and generics right now and hope to put up a PR next week.
