### ISSUE TITLE
Add ability to map icu_properties::Script to 4-ASCII-letter short name

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2832]
ICU4X uses a transparent struct newtyping `u16` for [`icu_properties::Script`](https://icu4x.unicode.org/doc/icu_properties/struct.Script.html). HarfBuzz, on the other hand, wants (32-bit) C enum [values that consist of the bits for the 4-ASCII-letter script short names](https://searchfox.org/mozilla-central/rev/8cfe1317c14fe6c997193141b8807d58f92c4f48/gfx/harfbuzz/src/hb-common.h#510).

With ICU4C as the back end, these can be bridged by [`uscript_getShortName`](https://searchfox.org/mozilla-central/rev/8cfe1317c14fe6c997193141b8807d58f92c4f48/intl/icu/source/common/unicode/uscript.h#544-554).

To be able to use ICU4X as a HarfBuzz Unicode data back end, ICU4X should have an API that maps `icu_properties::Script` to `[u8; 4]` containing the script short name. (Glue code can then [make a `u32` out of the `[u8; 4]`](https://searchfox.org/mozilla-central/rev/8cfe1317c14fe6c997193141b8807d58f92c4f48/gfx/harfbuzz/src/hb-common.h#159-169) and cast that into `hb_script_t`.)

Implementation-wise, we should have data that has a `ZeroVec<[u8; 4]>` that can be indexed by the numeric value of `icu_properties::Script`. (Or, alternatively, a fancier transparent newtype around `[u8; 4]` that knows how to view data as a 4-ASCII-byte `&str` also.)

**Comment by sffc** [comment]
Since we already hard-code the script numeric IDs, I think it would be okay to consider hard-coding the script ASCII codes. They aren't necessarily data-driven; they are spec-driven. The impact is that if you run old code with new data, you could get numeric scripts from the data provider that don't have a string mapping.

**Comment by sffc** [comment]
Either way, a reasonable representation would be `ZeroVec<TinyAsciiStr<4>>`.

**Comment by hsivonen** [comment]
Gecko also needs the length of this lookup table to be exposed so that it can proactively query a given font in HarfBuzz for all known scripts.

**Comment by sffc** [comment]
- @Manishearth - We could add the script-enum-to-script-code API fairly easily; the data we need is already in icuexportdata. But I would start with a hard-coded table and use icuexportdata for testing.
- @sffc - It doesn't seem that Harfbuzz can tell us via the enum signature whether or not it supports a certain script code. Casting from TinyStr4 to `hb_script_t` might not be well-defined if the two supported sets of scripts go out of sync. Should we just do the mapping directly from script enum to `hb_script_t` in the harfbuzz glue code?
- @Manishearth - What happens if Harfbuzz gets a valid but unknown script? It appears that it just treats it as an opaque thing.
- @sffc - If that behavior is clear and well defined, then I'm happy with the casting approach.

@hsivonen Feedback on the above discussion?

**Comment by Manishearth** [comment]
> It appears that it just treats it as an opaque thing.


In particular, I bet harfbuzz is just testing this against font metadata, in which case "unknown but valid (new) script" should Just Work

**Comment by hsivonen** [comment]
Currently, Firefox doesn't appear to figure out if HarfBuzz knows about a given script before applying the rule that turns a 4-letter code received from ICU4C into a 32-bit value to be passed to HarfBuzz. 

Furthermore, Firefox wants to iterate over all the known (currently known to ICU4C) scripts in order probe a given font via HarfBuzz for each script. This means that Firefox wants to know the number of scripts. Given that Firefox routinely passes all scripts known to ICU4C to HarfBuzz like this, I assume that doing so isn't a problem in practice, but @jfkthame would actually know.

I think we should have `ZeroVec<TinyAsciiStr<4>>` that's exported from `icuexportdata` and loaded via the provider so that it can be expected (unless GIGO happens) to be consistent with what `icuexportdata` has exported and the data provider is providing for the script enum.

Furthermore, I think we should expose the length of this `ZeroVec` so that an app can iterate over integers from 0 up to but not including that length, cast each integer to the script enum, and query for the corresponding 4-letter code.

**Comment by hsivonen** [comment]
(In Rust, an iterator over the `ZeroVec` should suffice, but with FFI, it's probably better to expose the length over FFI instead of trying to expose an iterator over FFI.)

**Comment by Manishearth** [comment]
Ah, if you want this to be data-driven I might not have time to do this. We can do it easily as a code-driven thing but new data will not add new codes.

I have already added a names-to-codes map, what you need here is a reverse code-to-names map. We didn't add it because there are many kinds of names and it wasn't clear what the breadth of use cases was for that (Should we have separate maps for short/long? What about aliases?)

If we do a code-to-names map it becomes trivial to iterate over them in order, as well.

Unassigning self from this since I'm not sure if we can get consensus on a data model in time for the release.

**Comment by sffc** [comment]
This ticket is not release-optional, based on consensus on what constitutes release-blocking at the team meeting last week, so we need to find another assignee.

I don't read @hsivonen's comment as changing anything about the data model *for harfbuzz*. We may want script code parsing in the future but that's not a harfbuzz blocker

**Comment by Manishearth** [comment]
@sffc @hsivonen said that he wanted it to be loaded via the provider.

I'm fine _doing_ this, I just think that if this is going to be data-driven we'll have to push the release back a bit while we pin down a data model.

I can add data-driven _tests_ since that doesn't stabilize anything, and that was my original plan. As you said, script codes come from the spec so we can have this map be in code rather than in data.

**Comment by sffc** [comment]
We can discuss again on Thursday

**Comment by sffc** [comment]
Conclusion from 2023-03-23 meeting:

- Yes, make this data-driven
- We can start with a key to map from uproperty discriminant to short codes and another key with the same struct to map to long codes, and eventually add one for aliases. We could also leverage the existing data model (optimized for string to discriminant) and improve it later.

**Comment by Manishearth** [comment]
My current plan is the following:

 - Attempt to add a ValuesToNames API for 1.2, that works for short and long names
 - If we don't have time, fall back to the inefficient but workable way of getting names from the NamesToValues data. Ideally use it in the harfbuzz glue _only_, but we can expose an `_unstable` method that later changes the key it needs
 - Punt extra aliases to the future. There are very few of them anyway and we don't have any users yet. It could possibly use the same structure if stored as a sorted ZeroVec rather than as a ZeroMap.
 - Punt mask values to the future as well, but consider them in the design.
