### ISSUE TITLE
Ship data for certain components directly on crates.io

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2888]
Data for certain components, especially ones that aren't locale-dependent, can be shipped on crates.io to make integration processes easier. Examples:

1. icu_normalizer
2. icu_properties
3. icu_segmenter

CC @robertbastian @hsivonen

**Comment by robertbastian** [comment]
I'm in favour of this. A few points that we discussed on Slack that I want to record here:
* We will need to figure out a way to combine baked providers without using `ForkByKeyProvider`. This can be achieved by generating macros that add the `DataProvider` implementations, instead of generating a provider struct.
  * This macro could also be used to select locales, although datagen should be the primary interface for that
* We probably need to ship postcard data as well, unless we figure out a way to fork between `AnyProvider` and `BufferProvider`. Tbd whether to do this in the same crate behind a feature, or have 2x crates

**Comment by hsivonen** [comment]
Marking this U-gecko, because this would make it easier to allow IDNA in the upstream `url` crate be (optionally) backed by ICU4X such that the relevant normalization data (and data that #2850 will hopefully introduce) won't be duplicated with the rest of Gecko. (As opposed to carrying Gecko-specific patches to this effect.)

**Comment by robertbastian** [comment]
Closing this in favour of #2945 which is the canonical shipped-compile-time-data issue.
