### ISSUE TITLE
Use `cargo quickinstall` on CI

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3037]
https://github.com/cargo-bins/cargo-quickinstall

We could avoid all custom caching of tool binaries, enabling us to use more tools like `cargo workspaces` without adding hundreds of lines of caching boilerplate everywhere.

We also don't get cache misses with quickinstall.

**Comment by sffc** [comment]
Discussion:

- Seems that cargo-quickinstall only caches the most popular versions of the most popular crates? We may be able to use it for cargo-make, but maybe not for cargo-readmes, cargo-all-features, etc.
- Would be nice to not introduce an additional third-party dependency
- The _best_ solution is for actions-rs to get upgraded support for modern GHA caching so that cargo-install "just works" with caching. This requires someone to take ownership of actions-rs.

Thoughts @robertbastian?

**Comment by robertbastian** [comment]
`cargo quickinstall` falls back to `cargo install` the first time it encounters the binary, but then it will add the binary to it's repo. I've tried installing diplomat through it and now it has diplomat.

actions-rs is unmaintained and deprecated, we actually just merged a PR replacing the install actions with just running `cargo install`.

**Comment by sffc** [comment]
Discuss with:

- @Manishearth 
- @robertbastian

**Comment by Manishearth** [comment]
I think https://github.com/unicode-org/icu4x/pull/4642 obsoletes this.
