### ISSUE TITLE
Migrate unic-locale to ICU4X

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#31]
@zbraniecki has graciously offered to migrate https://github.com/zbraniecki/unic-locale to this repository and make it the core locale type for ICU4X.  This issue is for tracking the progress of this migration.

**Comment by zbraniecki** [comment]
I'm working on the PRs for that.

I decided to remove a bunch of features from `unic_langid`, so that the import is easier:
* No proc_macros
* No CLDR reliant data (`minimize`, `maximize`, `likely_subtags`)

I'm also unifying `Locale` and `LanguageIdentifier` into a single crate, which has a number of nice benefits, makes tests and benchmarks a bit easier and so on.

I'm currently cleaning up the code and will submit two separate PRs: one for `LanguageIdentifier`, and a separate one for `Locale`.
My hope is that it'll make the initial review easier.

**Comment by zbraniecki** [comment]
I think this is done. We'll add features from `unic-locale` over time.
