### ISSUE TITLE
Can a data provider be written in a way that allows data provision delegation?

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#32]
Would it be possible to foresee a common key space for data, where ICU4X data uses only a small part of?  That would allow multiplexing data providers, something we'd like to explore in Fuchsia.  This is more of an inquiry if something like this would be of interest for ICU4X rather than a requirement.

**Comment by sffc** [comment]
This sounds interesting, but can you provide more context / definitions?  What do you mean by "common key space for data" and "multiplexing data providers"?

**Comment by sffc** [comment]
Ping.  I'd like to understand more about this ask so that it can be part of the DataProvider trait.

**Comment by filmil** [comment]
Let me try to clarify here.

A data provider is somewhat akin to a map.  You give it a key, and it gives you back the associated value. I wonder if there is interest to have a unified key space so that a single data provider endpoint could serve any message. My use case is a system-wide data provider for Fuchsia: using a single endpoint, you could look up a message for your specific program, or a data hunk that is part of the CLDR.  This would be possible if we subdivided the key space such that the two key values may never collide.

**Comment by sffc** [comment]
I see.

The short answer is yes; integer-valued keys is definitely part of the data-provider.md draft.  However, some of the keys carry along additional metadata, like language tag, currency code, etc.  Are keys in Fuchsia allowed to have metadata?

Can we reserve a chunk of key space for ICU4X?  How many bits of key space would that be?  If there are enough bits, then as long as the length of the ICU4X payload is bounded, then we can stick them into the key.

**Comment by sffc** [comment]
@filmil Ping

**Comment by filmil** [comment]
@sffc What info do you need? I'm looking at a 64-bit key space; we could reserve a few bits for a product family or some such.  Would that work?

**Comment by sffc** [comment]
Great.  So, of the 64 bits, how many are reserved for product family, and how many can we use for ICU4X?  For example, could we have a scheme such as:

- 16 bits: Fuchsia: product family
- 16 bits: ICU4X: key (e.g., DECIMAL_SYMBOLS_V1)
- 48 bits: ICU4X: payload (e.g., a currency code)

**Comment by sffc** [comment]
Also: is the 64-bit key space set in stone?

I believe we want the payload to be able to include:

1. A language identifier
2. An arbitrary string, such as a currency code or measurement unit identifier
3. Room to expand to other possible fields in the future

If we could make the key space larger, like 128 bits or 256 bits, or if we could have a way to attach an arbitrary payload to the key, it would enable us to be more flexible.

However, if the decision of 64 bits is set in stone, we can make it work.

**Comment by filmil** [comment]
Well, not exactly set in stone; but it would be nice if identical messages
could be folded into the same actual message.  E.g. if library A has a
string "Open", and library B has that same string, then they share IDs.

In this particular case, language ID is  irrelevant, since all translations
of the same message ("Open") in all languages share the ID.

**Comment by macchiati** [comment]
I'm not exactly sure what you mean. I'm concerned about one possible
interpretation.

Suppose that we have the mapping <key1, "Open">, which is then translated
to German, French, etc. We've found that it is dangerous to assume that we
can use the same key across multiple products. To take a simple case, a
different product might have <key2, "Open"> which translates differently,
because for key1 it is a status (is open), while for key2 it is a verb
(open it up). Typically the translation instructions are different in those
cases, of course. You can even have those within the same product, and need
two different keys because the translations would be different.

Mark

**Comment by zbraniecki** [comment]
Agree with Mark. Please, don't use source language strings as identifiers.

**Comment by filmil** [comment]
Hi folks. Source language strings alone are not used as the sole basis of the identifier.  Instead, it's identifier and context, which allows one to disambiguate English homographs that aren't homographs in other languages.  This, I believe, is the standard way this particular issue is handled in l10n.

**Comment by zbraniecki** [comment]
> This, I believe, is the standard way this particular issue is handled in l10n.

It is not. This is how Gettext handles identifiers (source string + context), and it is considered a flawed design. I would strongly recommend using unique identifiers.

Four main issues with the gettext model are:
1) Even within the same context strings may differ depending on their role in the UI
2) Using source strings as an identifier means that any stylistic changes to the source string invalidate the translation resulting in unnecessary churn and higher cost of translations. It has been estimated that 10-15% of string changes in Firefox are stylistic and should not result in ID invalidation.
3) You're locking yourself in "simple string" model, and complex strings, such as placeables, selectors, fragments of markup, become problematic.
4) The model is inherently tying translation unit to a single string, while modern UIs often are better served with a muilti-value translation units bind to a multi-value UI widget.

Since your design is aiming at the future generation of software, I would recommend tracking [MessageFormat 2.0 WG](https://github.com/unicode-org/message-format-wg).

The reason I'm raising this is that the choice of identifiers has a very far fetching consequences and a very high switch cost once the ecosystem is built around a given model. It's relatively easy to deploy an algorithm that generates unique IDs out of a source, but not the other way around.

**Comment by filmil** [comment]
> > This, I believe, is the standard way this particular issue is handled in l10n.
> 
> It is not. This is how Gettext handles identifiers (source string + context), and it is considered a flawed design. I would strongly recommend using unique identifiers.
> 
> Four main issues with the gettext model are:

Sorry, I wasn't talking about the gettext model in particular.  I think we can agree that messages need some sort of a stable identifier. Irrespective of how that identifier is generated. Which is I think the level of detail that that is enough for this feature request.

(This bit is out of scope here, but since you care, thought I'd mention it. If you are curious, you can see the example of [Fuchsia's current approach](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/src/intl/example/).  It is simplistic, and designed to handle Fuchsia's current needs. I think doors are open to evolvin. I am interested in MessageFormat 2.0 indeed, so will take a look.  I'd be glad to discuss with you, but that can happen out of band.)

**Comment by zbraniecki** [comment]
Ah, good. Yes. Thank you for your patience and detailed response. The example you showed looks like a safe start. In particular, XML of such kind can be extended to handle more complex units if needed, and there is an identifier. :)

**Comment by sffc** [comment]
I shared an example this morning for which I'm hoping Filip can give an example of how you envision this being supported in the 64-bit key space: You want to select the short currency symbol for GBP in locale zh-Hant-TW.  How do we put this in 64 bits in an extensible way?

- Even if we only use the LSR subtags in the language code, we need ceil(log2(26^9)) = 43 bits of entropy (2-3 letters for the language, 4 letters for the script, 2 letters for the region).  We could probably compress that more, but not without breaking from the language identifier data model.
- The currency code is another ceil(log2(26^3)) = 15 bits.

So, just with the payload, we've already used up 58 of our 64 bits of entropy.  This doesn't consider extra bits required for Fuchsia or ICU4X routing.

Having more bits (128 or 256), or being able to attach an arbitrary payload to the request, would be helpful.

**Comment by macchiati** [comment]
Most messaging systems I've seen treat the locale and the message ID as
separate entities. They might be packaged together in a request, but they
are logically orthogonal.

Mark

**Comment by sffc** [comment]
@filmil Thoughts on https://github.com/unicode-org/icu4x/issues/32#issuecomment-628914048?

**Comment by filmil** [comment]
Hi, @sffc , thanks for waiting for me to get un-distracted enough to give your comment https://github.com/unicode-org/icu4x/issues/32#issuecomment-628914048 a thought.

After going into a bit more detail I realized that you were right all along, and we don't need to place all data points into an integer keyspace.

Now, at least in the context of Fuchsia OS, it still makes sense to give each unique piece of data an unique identifier in some keyspace.  I will write up a slightly longer message to discuss with y'all.  I'd have written up a proposal but I still have very basic open questions that I'd like to sort out first.

**Comment by filmil** [comment]
Hi folks.  Finally, [here's a write-up][wrup] of what I had in mind.

The main question is whether this proposal is something that we want to bother with under ICU4X.  Since we're defining a data provider and expecting multiple and independent implementations, perhaps it is a good place to provide extension points.  The extension points here are simple but could have a lasting impact on how i18n data is used, given that it's a basic tenet of ICU4X.

Read and comment, please?  I made it into a Google Doc, since it's not clear whether the proposal is a keeper, but would be happy to address any comments -- feel free to request access if you want to comment.

[wrup]: https://docs.google.com/document/d/1MUiLpJg8ekaNdTpnRqlAoXctsHCWciEx3hwhqfVNlbw/pub

**Comment by sffc** [comment]
Thanks for sharing!

I like your idea of thinking about this in terms of a domain ("source") that defines a key format.  For example, we could use the domain "icu4x.unicode.org" (or "org.unicode.icu4x"), and then use a URI-like or other format to request our data.  Meanwhile, Chromium or Firefox could have their own domain and keyspace.

Hmm, should we use HTTP?  The request could become,

```
GET /calendar/month-names-v1/gregory HTTP/1.1
Host: icu4x.unicode.org
Accept: application/json
Accept-Language: es-MX, en-US
Accept-Encoding: deflate, gzip
```

**Comment by echeran** [comment]
I also like the inclusion of domain/source (I think of it as a "namespace") to prevent collisions by ensuring that the request info represents a globally unique key.  I would have a slight preference "org.unicode.icu4x" over "icu4x.unicode.org" to match the style used in Java package names, Maven artifact group ids, etc.

I wonder, in the write-up doc, in the "Unique IDs" section, the example provided shows a key as `Key: { source = “org.mozilla”, message_id=42, locale=”en-US”} ...`, whereas [the link in that section](https://github.com/unicode-org/icu4x/blob/master/components/data-provider/src/lib.rs#L52) to current data provider code points to the `Request` struct, which contains a field of type `Key`.  Is the doc viewing / equating the `Request` struct as effectively being the lookup key?  I could understand that logical mapping, I just want to make sure I understand how the current & proposed ideas compare.

I think I understand the comment about needing to have a more extensible way of representing the dimensions of "hunkspace", which explains why XRI is more flexible than URIs in the way -- perhaps like how named arguments (associative data) is more flexible than positional arguments.  In that vein, could we just use JSON to serialize the info (ex: instead of HTTP), since it allows associative, sequential, nesting, and then it can also be as simple as plain scalars for domains/sources/namespaces that only need 1 dimension for message lookup?

**Comment by filmil** [comment]
Hello, all.  I updated the proposal with examples: https://docs.google.com/document/d/1MUiLpJg8ekaNdTpnRqlAoXctsHCWciEx3hwhqfVNlbw/edit#heading=h.dune88qjir4p

PTAL: @sffc @echeran ; others: at your option.
