### ISSUE TITLE
Investigate why WordSegmenter doesn't return same breakpoints as DictionarySegmenter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3236]
There are the following test cases:

```rust
        // Match case, then no match case
        let s = "エディターエディ";
        let result: Vec<usize> = segmenter.segment_str(s).collect();
        assert_eq!(result, vec![0, 15, 24]);

        let s_utf16: Vec<u16> = s.encode_utf16().collect();
        let result: Vec<usize> = segmenter.segment_utf16(&s_utf16).collect();
        assert_eq!(result, vec![0, 5, 8]);
```

These return different results depending on whether `segmenter` is a WordSegmenter or a DictionarySegmenter. When it is a WordSegmenter, we don't get the middle breakpoint.

**Comment by sffc** [comment]
@aethanyc @makotokato Any idea about this? (see #3235)

**Comment by aethanyc** [comment]
WordSegmenter doesn't return the middle breakpoint probably due to [**WB13: Do not break between Katakana.**](https://www.unicode.org/reports/tr29/#WB13)

For DictionarySegmenter, I see "エディター" is listed in https://raw.githubusercontent.com/unicode-org/icu/main/icu4c/source/data/brkitr/dictionaries/cjdict.txt. That is probably why it breaks there.

The word segmentation in [ICU demo](https://util.unicode.org/UnicodeJsps/breaks.jsp) also has no breakpoint in the middle of "エディターエディ", so our behavior seems OK.

**Comment by sffc** [comment]
Okay. I thought we relied on the dictionary for Japanese word break (sending all katakana to the dictionary engine), but do the TR29 rules override the dictionary in this case?

**Comment by aethanyc** [comment]
> Okay. I thought we relied on the dictionary for Japanese word break (sending all katakana to the dictionary engine), but do the TR29 rules override the dictionary in this case?

Yes, I believe UAX29 rules has higher priority than dictionary in our current implementation. We have issue https://github.com/unicode-org/icu4x/issues/2239 to consider whether we should use dictionary instead UAX29 rules for Katakana.
