### ISSUE TITLE
Additional discussion on test locales

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#342]
Our list is currently:

- ar - Arabic
- be - Belarusian
- bn - Bangla
- ccp - Chakma
- en - English
- es - Spanish
- fr - French
- ja - Japanese
- sr - Serbian
- th - Thai
- tr - Turkish

@macchiati suggested adopting Russian instead of Belarusian because it has more speakers and is considered the major Cyrillic language.  We had previously expressed a desire to cover a mix of bigger and smaller languages.  He also suggested considering Hindi instead of Bangla.

**Comment by mihnita** [comment]
Russian sgtm (in fact I proposed Russian myself)
They both cover the same technical challenges (non-Latin script, inflected, 4 plurals, genitive month names)

I preferred Bangla instead of Hindi because Hindi uses ASCII digits by default (`0030`-`0039`), while Bangla has its own digits (`09E6`-`09EF`). Otherwise they are equivalent.

**Comment by sffc** [comment]
2020-10-30: Swap be for ru.  @mihnita to open a PR.
