### ISSUE TITLE
Globaldata data location / data crate API guarantees

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3535]
Where is globaldata stored in the repo?

Is it shipped as a standalone crate or inside the component crate?

Related: #3537

Discuss with:

- @robertbastian 
- @sffc 
- @Manishearth 

Optional:

- @echeran

**Comment by Manishearth** [comment]
Personally: standalone crates that live inside the component crates (but are published as separate crates, like `zerovec/derive`)

This makes it overall easier to perform crate replacement in clients.

**Comment by robertbastian** [comment]
> Is it shipped as a standalone crate or inside the component crate?

I think this should be discussed together with versioning #3537. If we tightly couple to ICU4X versions, we might as well put the data into the crates.

**Comment by Manishearth** [comment]
- @robertbastian we already solved api guarantees yesterday. needs to be stable for component crates to consume: "a list of macros that Do The Thing"
 - @sffc if we tell people they can use these APIs they also need to update callsites if the signatures of these macros change
 - @robertbastian but we can't tell people to not use these yeah?
 - @sffc doc(hidden) and DO NOT USE COMPLETELY UNSTABLE
 - @sffc or we can document these as "here is how this works and we can keep things working"
 - @robertbastian i think this is something we can guarantee bc we're keeping databake stable
 - @sffc the new thing is we haven't had these key specific macros. are these now a part of databake's public api?
 - @robertbastian because it's all macros we can make any changes inside them imo. may want to add a single non-key-specific macro that you have to call on the provider object that can do global initialization if necessary. then we won't be boxed in a corner
 - @Manishearth (i can buy that)
 - @sffc unsure about non-key-specific macro
 - @robertbastian basically any metadata/boilerplate; global macro could add a const or static or whatever is needed. i needed this at some point but we don't need it now, may need again in the future. dummy macro for now, does nothing.
 - @sffc what happens if you don't call it now
 - @robertbastian we guarantee: if you have a combo of macros that works today, it will compile in the future
 - @sffc example of future cases?
 - @robertbastian currently fallback uses the baked data from the locid_transform crate. only works well if all the versions are the same. we may change our mind and make fallback data per-databake invocation instead (i.e., per-crate), and then we'd need it.
 - @sffc @Manishearth convinced that we may wish to do things of this shape at some point (not convinced of precise thing)

Decision: The existence and shape of the macros is public API, we add a dummy global initialization macro in case it's needed in the future. A combination of macros that works now (that uses the global macro) will work in the future. The global macros presence is enforced with some const static assert trick (defining that manually is not allowed).

signoff: @Manishearth @robertbastian @sffc 


Data location: Anyone opposed to keeping them where they are.

 - @robertbastian would like to figure out codeowners stuff
 - @Manishearth defaulting to icu4x-owners works okayishly
 - @Manishearth could also make an icu4x-generated-code-owner
 - @robertbastian keeping them in the components crates is also nice because it localizes changes
 - @sffc i like collapsing folders of generated code tho.
 - @sffc can we name them .drs or something
 - @robertbastian <noncommittal noises>
 - @sffc we've had problems with .rs in the past and i'd kinda like to make them text files as far as the compiler is concerned.
 
Decision: Stick to `components/foobar/data` for now, no codeowner (by using icu4x-owners or a new crate). We recommend people doing large cross-cutting changes make PRs with few commits and datagen commits are separate (and ideally at the end). Further optimization can be discussed between reviewers and PR authors for specific PRs. Let's revisit if this is a problem, this is a purely internal decision.


lgtm: @robertbastian @sffc @Manishearth
