### ISSUE TITLE
Globaldata crate versioning

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3537]
How should we apply Cargo versions to the globaldata crates like `icu_plurals_data`?

Discuss with:

- @Manishearth 
- @sffc 
- @robertbastian 

Optional:

- @echeran

**Comment by Manishearth** [comment]
IMO we version them with ICU4X the usual way. I am okay with using patch releases to carry CLDR updates. I would very much like the major and semimajor versions to always be the ICU4X version because anything else requires that the user perform some spelunking.

If we _want_ we can use ["prelease" version numbers](https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases) to do stuff like `v1.3.0-cldr42` etc for non-primary CLDR versions. Cargo does not automatically pick these up so they should overall be fine, and people can explicitly `cargo update` to them if they want.

This would be a bunch of effort to publish multiple sets of data, but it ought to be automatable if we really want.

**Comment by robertbastian** [comment]
Unlike postcard, the format is tied to a major ICU4X version (we do want to change some things in `icu_provider` in 2.0), so we should use ICU4X major versions. I don't see the value of incorporating minor versions, as data versioning should be as independent as possible from component versioning. Hence my vote is for `1.43.0`.

**Comment by Manishearth** [comment]
No, the format is tied to a minor ICU4X version, since `provider` is unstable (and has already broken stability for some components multiple times0

I think `1.43.0` is going to be confusing, and doubly confusing for when crates add new keys and we need to go back and keep track of `1.43.1` or whatever.

**Comment by robertbastian** [comment]
Ah right, and it's actually a `=` dependency. If we keep it unstable then this defeats the whole purpose of separate crates.

**Comment by Manishearth** [comment]
I think we can still manage with the explicit policy of using the appropriate range deps when depending on globaldata and never breaking `provider` stability in patch releases. But it is tricky, yeah.

**Comment by robertbastian** [comment]
- @robertbastian Why do we need to release these potentially mismatching version as crates anyway?
- @Manishearth users might want to use the latest CLDR before we do a release
- @robertbastian we might not want separate crate, we can put the data in the component crates and do patch releases with new CLDR versions
- @eggrobin the version mismatch is an issue
- @Manishearth only for some crates
- @sffc forward/backward compat is not a baked data issue, we have a policy for this
- @robertbastian we have solved the technical side of this for postcard, but whether using N+1 CLDR is correct is another issue
- @sffc our solution to this is have new data structs for each algorithm change
- @eggrobin segmenter changes every year
- @Manishearth this is going to be messy
- @Manishearth for Google we probably don't need separate crates, we can patch with environment variables
- @sffc the scenario I want to support is to use current ICU4X with older CLDR, in code bases where CLDR updates might be slower
- @robertbastian in this case you are going to use custom data anyway. This discussion is about published data
- @Manishearth people who really care about data provenance should not use our published data. They can try with their own data and it should still work
- @eggrobin it might produce gibberish in some corner
- @Manishearth yes. Do we want to maintain old releases so that they work with new data?
- @robertbastian it will be a lot of work to determine what works with what
- @Manishearth we, as in ICU and ICU4X should do this. It would require asking e.g. PAG to clearly point out these issues in release notes
- @eggrobin this is *a lot* of work. There are three places in UTS that do this, and it's already very hard
- @Manishearth how would you verify that a version mismatch works?
- @sffc I don't care that much about PAG
- @robertbastian I think we're sidetracking a bit, even if we can determine whether a version mismatch works, is this something we want to encourage clients to do by allowing mismatches in releases?
- @Manishearth Shane's use case if valid, but I'm happy to tell these clients to use the environment variable
- @sffc I don't know why we're discussing it, we've agreed on this last year in `data_versioning.md`
- @robertbastian let's get back to the issue, do we want to publish mismatched versions?

< omitted > 

Proposal: 
- data crates share versioning with main crate aside from the patch number
- logic crates depend on patch crates with a narrow range allowing only patches
- the data crate's patch (or prelease) may be used to publish CLDR updates, tbd how/whether we will actually publish data

Exact versioning scheme:
 - Patch version begins at 0, increments for _both_ CLDR version updates and patch release fixes to the data (`1.3.0`, `1.3.1`)
 - Document the CLDR version in data crate docs. Always.
 - _Negative_ CLDR version releases use prerelease versions, e.g. `1.3.0-cldr41`

Agree: @eggrobin @sffc @skius @Manishearth @robertbastian
