### ISSUE TITLE
How to treat `Script_Extensions` property in UnicodeSets

### ISSUE THREAD

**Issue by skius** [unicode-org/icu4x#3555]
It is unclear how (or if at all) we should implement the Script_Extensions property for UnicodeSets, i.e., `\p{scx=Latn,Grek}`. 

References: 
* https://www.unicode.org/reports/tr24/#Script_Extensions
* https://www.unicode.org/reports/tr18/#Script_Property

**Comment by sffc** [comment]
@markusicu @macchiati Thoughts on this?

**Comment by markusicu** [comment]
As documented in UTS18. From where the link points: “The expression `\p{sc=Hira}` includes those characters whose _Script_ value _is_ Hira, while the expression `\p{scx=Hira}` includes all the characters whose _Script_Extensions_ value _contains_ Hira.”

If you want both Latin and Greek characters, use set union as usual: [`\p{scx=Latn}\p{scx=Grek}`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7Bscx%3DLatn%7D%5Cp%7Bscx%3DGrek%7D&g=&i=).

**Comment by skius** [comment]
Thanks for your reply, @markusicu. Do I understand correctly that syntax such as https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Script_Extensions=Arabic,Coptic:] is unspecified and does not have to be supported?

**Comment by markusicu** [comment]
> Do I understand correctly that syntax such as [`[:Script_Extensions=Arabic,Coptic:]`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B:Script_Extensions=Arabic,Coptic:%5D) is unspecified and does not have to be supported?

Right. Don't support that.

That happens to give you _something_ in this tool (not in ICU) because the Unicode Tools JSP code mostly turns all values into strings and matches on those. There are some characters that happen to have only and exactly Arabic and Coptic in their Script_Extensions (or maybe other values that alphabetically fall outside those two).

You can see that it doesn't treat these as a set of script values if you reverse the order: [`[:Script_Extensions=Coptic,Arabic:]`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AScript_Extensions%3DCoptic%2CArabic%3A%5D&g=&i=) yields no characters.

There are other bugs in the Unicode Tools due to this string processing (e.g., bad results from using the Age property). We haven't found the time to revamp the storage and matching of values in these tools.

**Comment by skius** [comment]
Thank you!

**Comment by skius** [comment]
Fixed in #3547
