### ISSUE TITLE
Hebrew Epoch Bug (Negative years)

### ISSUE THREAD

**Issue by sotam1069** [unicode-org/icu4x#3739]
While starting to implement the Hebrew Calendar I tested the epoch and noticed that the `fixed_from_julian_integers` function is off by one day compared to the date that the book gives aswell as what the code from the books gives. This difference in value most likely has to do with the way the function handles negative years.

Hebrew Epoch in Julian: `(-3761, 10, 7)`

R.D Date of Hebrew Epoch (book) : `-1373427`
R.D Date of Hebrew Epoch (lisp): `-1373427`

Hebrew Epoch using `fixed_from_julian_integers`: `-1373428`

**Comment by sffc** [comment]
Possibly related: https://github.com/unicode-org/icu4x/issues/3477

**Comment by atcupps** [comment]
I have a partial fix for #3477, I can open up a pull request for that

**Comment by atcupps** [comment]
#3751 seems to fix this issue (I created a test for it); however, because the Hebrew epoch given in the book `(-3761, 10, 7)` uses a year system which is not arithmetic, while the function `fixed_from_julian_integers` uses arithmetic years, so in this and similar cases where dates are being created using years from the book, the new function `fixed_from_julian_book_version` should be used (this may be renamed). Alternatively, the year could be adjusted by one. So, `fixed_from_julian_integers(-3760, 10, 7) == fixed_from_julian_book_version(-3761, 10, 7)`.

**Comment by Manishearth** [comment]
Yep, this is fixed and tested

https://github.com/unicode-org/icu4x/pull/3751/files#diff-7824001007a0226c41edc4ab1cf9adb8b7ea6d52f7dac7479bf90b8939474e1bR636
