### ISSUE TITLE
Decide on naming of "legacy" titlecase adjustment mode

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3801]
Regarding `new_legacy()` on `TitlecaseMapper`:

> Thought: I wonder if this should be called `new_spec()` or `new_chapter3()` or similar, to take a positive angle toward what this is, rather than the negative term "legacy" which is not very specific.

_Originally posted by @sffc in https://github.com/unicode-org/icu4x/pull/3779#discussion_r1284049394_

cc @markusicu @sffc

**Comment by sffc** [comment]
My take is,

1. If it's "legacy" then why are we shipping it? ICU4X doesn't ship legacy things. That's ICU4C's job.
2. It's not actually "legacy" because there is a current Unicode specification that recommends this behavior.
3. The "better" behavior is in the function without a suffix.
4. I prefer to take positive rather than negative angles on suffixed functions. The suffix should have a sufficient amount of positive jargon that a passerby will be scared to use it without knowing what they're getting themselves into.

**Comment by Manishearth** [comment]
> If it's "legacy" then why are we shipping it? ICU4X doesn't ship legacy things. That's ICU4C's job.


Because one would want to interop with other systems using it. Yes, we should ship legacy things, when needed for interop.

Also for people who aren't using head adjustment; it requires less data.

> It's not actually "legacy" because there is a current Unicode specification that recommends this behavior.

That's fair but nowhere else on casemapping do we have a mode to follow what the unicode specification recommends. I think `new_chapter3` would be misleading because we do not implement that algorithm; we implement a tailored version (as is recommended in the chapter anyway), and we have no way to turn off the tailoring.

I'm not opposed to picking something that is not `legacy`, I'm just opposed to picking something whose name primarily derives from the spec, since we are switching a _particular_ thing over to the spec mode.

**Comment by markusicu** [comment]
I agree that it's better to describe what it does rather than whether we like it ("legacy") or where it is defined ("spec" or "chapter3"). Besides, "new legacy" sounds like an oxymoron.

In ICU4J I called it [`CaseMap.Title.adjustToCased()`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/CaseMap.Title.html#adjustToCased--).

For ICU4X, how about
- `TitlecaseMapper::new_adjust_to_cased()` or `CaseMapper::titlecase_adjust_to_cased()`, or
- `TitlecaseMapper::new_skip_to_cased()` or `CaseMapper::titlecase_skip_to_cased()`

**Comment by Manishearth** [comment]
@markusicu hmm, yeah that works

**Comment by sffc** [comment]
- @sffc - We need to bikeshed `CaseMapper::titlecase_segment_...`
- @Manishearth - Maybe we could just have `CaseMapper::titlecase_segment_no_adjust` and say that's the main use case
- @sffc - The only use case for this function is if you care about your data.
- @markusicu - `_with_only_case_data`?

`CaseMapper::titlecase_segment_with_only_case_data`

LGTM: @markusicu @sffc @Manishearth
