### ISSUE TITLE
Support strings in UnicodeSet

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#396]
Right now we have UnicodeSet that only supports code points.  For full support of all Unicode properties, including sequence properties, we will need to support strings.

I think it is still useful to have a data type that supports code points.  My preference would be to:

1. Rename the existing code-point UnicodeSet to CodePointSet
2. Make a new class UnicodeSet that wraps a CodePointSet and adds string support

**Comment by macchiati** [comment]
I would like to understand more (especially given that I know little about
Rust). Maybe you could say more of the motivation for having two distinct
classes. Is it having less code?

The other side of the coin is that it is conceptually easier to just have
UnicodeSet (with the functionality of your #2) than to have both
CodePointSet and UnicodeSet.

Mark

**Comment by sffc** [comment]
I think CodePointSet is a useful data type that stands on its own merits:

1. Useful for very many text processing tasks when strings are not needed
2. Better separation, modularization, and compartmentalization, leading to smaller code size
3. Can represent Unicode properties of code points (not sequence properties)

I don't buy that having one class is conceptually easier.  UnicodeSet works the same way whether or not CodePointSet is also available.

**Comment by sffc** [comment]
2020-12-04:

- @mihnita points out that the API for CodePointSet is different from UnicodeSet because it is based around ranges, so you can add ranges and iterate over ranges.
- @echeran sees "strings of code points" as an abstraction over the set of code points; the two classes expose different abstractions, so they should be kept separate
- @mihnita suggests considering a trait (interface) that both classes could implement

**Comment by macchiati** [comment]
My concern is more that about the API people start creating methods that
take a UnicodeSet (or a CodePointSet) and can't take the other.

It feels like cases where we originally specified the decimal separator as
a char, instead of a string, then had to add alternate APIs, or APIs that
took a StringBuffer that then needed to upgrade to StringBuilder.

Mark

**Comment by sffc** [comment]
For sure we should recommend UnicodeSet to users who don't know which one to use.

When I've faced similar choices in other areas, like ECMAScript and ICU, if there are two classes that are both useful but users should generally favor one over the other, we just make sure that the "normal" class has a shorter, more inviting name than the "advanced" class, and add thorough documentation to push people toward the "normal" class.  I see this as a similar situation: CodePointSet is the "advanced" class, which we've established to be useful in specific circumstances, and UnicodeSet is the "normal" class.

This line of reasoning is also why I've warmed up to exposing both LanguageIdentifier (advanced) and Locale (normal).

**Comment by indolering** [comment]
> @mihnita suggests considering a trait (interface) that both classes could implement

This gets to the heart of the issue: UnicodeSet as a [fragile base class](https://en.wikipedia.org/wiki/Fragile_base_class).  Instead of adding support for strings, you would turn UnicodeSet into a Trait with the bare minimum functionality required to be useful.

This goes beyond just support for strings, I personally would like to be able to use UnicodeSets in no-std/alloc environments and const expressions, for example.
