### ISSUE TITLE
General question regarding Temporal compatibility

### ISSUE THREAD

**Issue by nekevss** [unicode-org/icu4x#4075]
Hi there! I was just wondering if there was any discussions on implementing [`CalendarFieldDescriptors`](https://tc39.es/proposal-temporal/#sec-temporal-calendarfielddescriptors) and/or [`CalendarFieldKeysToIgnore`](https://tc39.es/proposal-temporal/#sec-temporal-calendarfieldkeystoignore) from the Temporal proposal spec.

**Comment by sffc** [comment]
@hsivonen Is there another issue to track this?

**Comment by hsivonen** [comment]
> @hsivonen Is there another issue to track this?

No, because I (perhaps incorrectly) though that this stuff would be hard-coded as lists into the glue code.

**Comment by sffc** [comment]
Yeah, looking at this closer, this is in the gray area between what should be in ICU4X core versus what should be in the JS engine wrapper. However, I think the correct answer is to put it in the wrapper, because:

1. The ICU4X calendar trait requires that all calendars speak the same language of era and month codes (https://docs.rs/icu_calendar/1.3.0/icu_calendar/trait.Calendar.html#tymethod.date_from_codes) so there is no additional information that ICU4X could provide by implementing these methods
2. We decided in https://github.com/tc39/proposal-temporal/issues/2664 to be consistent of the fields for all CLDR calendars.

I will therefore close this issue. Please comment if you think it should be re-opened.
