### ISSUE TITLE
Testing: fixtures vs. parameterized vs. data-driven

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#410]
I'm seeing three different patterns emerge for ICU4X testing.

In [PluralRules](https://github.com/unicode-org/icu4x/blob/4dfb4e29fbaabd1560156fbccb71c4676845cd49/components/plurals/tests/fixtures/rules.json#L1) and DateTimeFormat, @zbraniecki uses test fixtures. The test cases are backed by data; the data lives in JSON files inside the project folder.

In [FixedDecimal](https://github.com/unicode-org/icu4x/blob/4dfb4e29fbaabd1560156fbccb71c4676845cd49/utils/fixed_decimal/src/decimal.rs#L529), I use parameterized testing. The test cases are backed by data; the data lives in the code file.

In #51, @echeran is working on adding data-driven testing through the data provider. The test data will live in a common directory (probably under /resources/testdata) and will be served up to clients via the DataProvider protocol.

I think we should pick one of these approaches and use it across the board. Pros and cons:

1. Fixtures
    - Pro: Well understood and standardized approach at solving this problem
    - Con: A fair bit of boilerplate is required
2. Parameterized
    - Pro: Easy to read and implement; everything is in one place
    - Con: Data cannot be shared across programming languages (without additional tooling)
3. DataProvider
    - Pro: Easy to use across programming languages
    - Pro: Can be deeply integrated with ICU4X features, like multiple locales
    - Pro: Test data can be versioned parallel with CLDR data version
    - Pro: Test data updates are "broadcasted" along with ICU4X data
    - Con: Novelty without a lot of prior art

Thoughts?

**Comment by echeran** [comment]
That's a good list of pros and cons for each of the different approaches. Parameterized is easiest and goes a decent way to concisely conveying the cases (general cases + corner cases) of the algorithm under test. Given that a lot of i18n tests seem to be asserting the logical correctness of rule-like transformation algorithms, have nicely parameterized tests goes a long way.

Fixtures are good, they require extra work to create the fixture test harness, but one thing about them is that the level of abstraction means it can be tricky sometimes to associate the inputs to the outputs easily.  This may be a critique shared with the DataProvider approach, too.

The DataProvider approach sounds like the ideal solution, because by adhering to the data provider interface and a plain data input file that can live independently of code, can be easily ported to other target languages of ICU4X.  But first off, it needs a good push from me so that it can be exercised and examined (and doesn't remain in the 'todo' state on my plate indefinitely). Second, as mentioned earlier, it might have the same drawbacks as fixtures in not easily showing the relationship between the code/functionality and the inputs/outputs under test.

**Comment by filmil** [comment]
It would be nice if @zbraniecki confirmed, but if I recall correctly, the fixtures were part of the idea for cross-language conformance testing.

A fixture, with appropriate ways to parse and load the fixture data in each language, would allow us to confirm that icu4x gives the same results as icu4c or icu4j when invoked on analogous input.  This extends to WASM, as well as any other wrappers or libraries.

**Comment by sffc** [comment]
I suggested using DataProvider to provide the test data as an alternative to fixtures as a way to avoid having to port the fixture test harness code to each programming language.  My idea was that since we are already committed to building an infrastructure around DataProvider in all of the target languages, we can leverage the same infrastructure for testing.

**Comment by sffc** [comment]
2021-01-15: Implement option 3.  We could migrate back to Option 1 later.

**Comment by sffc** [comment]
Dupe of #51
