### ISSUE TITLE
Add something feature not to use `dictionary_wl_ext_v1` with `compiled_data` feature

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#4111]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1854031

When using `icu_segemter` with `compiled_data`, `icu_segmenter_data` crate (even if it is customized) has to have `impl_segmenter_dictionary_wl_ext_v1`. But this baked data isn't required on Gecko, so we need something feature to use this feature, such "dictionary_ext" in `icu_segmenter`.

**Comment by sffc** [comment]
If you choose to use compiled data (there are other threads that suggest that the Mozilla use case is specialized enough that you should continue using explicit data providers, but maybe those threads don't apply to segmenter), then you should either build with all keys and let DCE strip them, or build all keys but use the segmenter-models flag on Datagen to select only the models you want, so that you end up with an empty data key for dictionary_wl_ext.

CC @robertbastian

**Comment by sffc** [comment]
@makotokato See the reply above with suggestions. We discussed this in the TC call and decided that this is WAI.

**Comment by makotokato** [comment]
I see. OK to add modified data

**Comment by sffc** [comment]
It would not be unreasonable to add a `dictionary` Cargo feature to the `icu_segmenter` crate; we discussed doing that when we added the `lstm` feature but decided it was not necessary because dictionary segmentation does not pull in additional dependencies. However, I confirmed with @makotokato that this solution would not solve his particular problem, because he still needs the CJ dictionary for WordBreakSegmenter.

Adding a Cargo feature on a more granular level, like a data key level, is not a path I would like to go down. We already have too many Cargo features in ICU4X, and we have a clearly paved path for people like @makotokato who have constraints that make it difficult to use the compiled data constructors.
