### ISSUE TITLE
Should we include IDNA in ICU4X?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#42]
IDNA is in UTS 46, but it is a very specific subject area.  The existing IDNA Rust crate lives alongside other URL-related functionality.

ICU's IDNA has had [bugs](https://unicode-org.atlassian.net/browse/ICU-21030) piling up, with no clear owner, since IDNA is largely tangential to the core ICU functionality of localized text processing.  UAX 31 and UTS 39 (identifiers and confusables) are largely in the same bucket.

I personally would like to see us focus on ECMA-402, and declare UAX 31, UTS 39, and UTS 46 out of scope of ICU4X, at least for the time being.

@markusicu @macchiati @kpozin

**Comment by macchiati** [comment]
I think there is plenty else that is higher priority right now.

**Comment by zbraniecki** [comment]
Mozilla will need IDNA to be able to replace ICU. I don't think it's the highest priority, but I don't think we should drop it either from the target.

**Comment by sffc** [comment]
I tend to feel that when it comes to implementing specs other than UTS 35, they can usually be implemented as standalone projects. They don't really need the same data pipeline infrastructure that ICU4X brings to the table. It might be advisable for us to say explicitly that we are only focused on implementing LDML (UTS 35), to reduce the scope and prevent us from collecting cruft that we officially own but don't actively maintain.

Can Mozilla depend on the existing idna crate? Why do you want it in ICU4X?

**Comment by zbraniecki** [comment]
I think you brought up a good point!

The main reason for having it under ICU4X is data alignment. Most users will care about having their project on Unicode 13, and CLDR 36.1.
Today, they can say "we use ICU 64.1 which gives us Unicode 13 and CLDR 36.1" and be done.

If we narrow down ICU4X much further than what ICU provides, we ask those users to pull in ICU4X for features X, Y, Z, and `unicode-script` version 1.2, and `unicode-normalization` vs 1.4 and `unicode-idna` version 3.0 in order to have unified Unicode and CLDR.

I don't know how much we can alleviate this problem, but I think that looking at the core needs of major ICU consumers and assuming that the set they use ICU for, is the set they want to have behind a single Unicode/CLDR dataset is what they'll need to align for.
A scenario where ICU4X updated to a new Unicode, while `unicode-script` did not, may become a headache.

The `DataProvider` brings up not only a good way to marshal data, but also a good way to unify all Unicode needs around a single version.

**Comment by hsivonen** [comment]
> The main reason for having it under ICU4X is data alignment.

Isn't IDNA's data use deliberately frozen at Unicode 3.2? That is, having a single source of data could help with binary size but is not a correctness issue.

**Comment by sffc** [comment]
I wouldn't mind publishing a crate that exposes raw Unicode property data, and then let someone else maintain the supplemental algorithms (UAX 31, UTS 39, UTS 46) in their own crate.

Actually, UCD data is probably different enough from CLDR data that it could get its own data pipeline infrastructure.  That's a topic for a different issue.

**Comment by sffc** [comment]
> If we narrow down ICU4X much further than what ICU provides … I think that looking at the core needs of major ICU consumers and assuming that the set they use ICU for …

The scope, as we agreed in the original charter document, is the ECMA-402 surface area.  We should talk in terms of "expanding" the scope from ECMA-402, not "narrowing" the scope from ICU4C/ICU4J.

**Comment by sffc** [comment]
We agreed that ICU4X should expose a Unicode properties API that would enable leaf functions like IDNA to be implemented on top of ICU4X's infrastructure.  Action is on me to document this.
