### ISSUE TITLE
es-MX FixedDecimalFormatter data seems to be missing

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/icu4x#4232]
es-MX uses `.` for the decimal separator:

https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-numbers-full/main/es-MX/numbers.json

However, the ICU4X data file has no entry for es-MX or for es-419, meaning that es-MX falls back to es data, which uses `,` as the decimal separator:

https://github.com/unicode-org/icu4x/blob/main/provider/baked/decimal/data/macros/decimal_symbols_v1.rs.data

**Comment by sffc** [comment]
Verbose datagen output:

```
2023-10-27T02:01:00.599Z TRACE [icu_datagen::driver] Generating key/locale: decimal/symbols@1/es-MX
2023-10-27T02:01:00.839Z TRACE [icu_datagen::driver] Deduplicating decimal/symbols@1/es-MX (inherits from es-419)
2023-10-27T02:01:00.826Z TRACE [icu_datagen::driver] Deduplicating decimal/symbols@1/es-419 (inherits from und)
```

But es-419 does not inherit from und.

**Comment by sffc** [comment]
The problem was that the runtime fallback mode was deduplicating locales that had _any_ parent with equal data, but it should have been deduplicating locales only if the _closest_ parent had equal data. This affected es-MX because it has the same data as `und`, but it has different data than `es`, which was being reached by fallback.

This affected data in the following components:

    - `icu_compactdecimal_data`
    - `icu_datetime_data`
    - `icu_decimal_data`
    - `icu_displaynames_data`
    - `icu_properties_data`
