### ISSUE TITLE
Should we remove cyclic dev-deps?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4475]
Cyclic dev-deps cause various problems, such as with rust-analyzer and IDEs (https://github.com/rust-lang/rust-analyzer/issues/14167). Apparently JetBrains removes the cyclic dev-deps and suppresses the resulting warnings in the IDE, and rust-analyzer is proposed to do the same thing.

Currently we have the following types of cyclic dev-deps:

1. Component crates dev-dep on `icu` for docs. I've never really liked this.
2. Derive crates, like zerovec_derive, dev-dep on the main crate. Seems like an easy fix to just move tests to the main crate.
3. icu_provider has a dev-dep to icu_locid_transform. Seems like an easy fix to move those tests around.

Or, we can keep the cyclic dev-deps and let tooling continue to deal with it.

Thoughts?

@zbraniecki @Manishearth

**Comment by Manishearth** [comment]
I don't think that issue is related, it's about cycles where a crate has _itself_ as a dev dep. Not the general case of a crate depending on some crate that depends on itself (which has rather well defined semantics).

Cyclic dev-deps are pretty standard in the ecosystem, I don't think we should be moving away from them. I'm in favor of letting tooling continue dealing with it.

**Comment by Manishearth** [comment]
We probably should remove cyclic dev-deps from unit tests though. As I'm writing there, those _are_ rather bad.

**Comment by robertbastian** [comment]
We decided to use the meta crate for docs tests, so unless you want to add a fake meta crate at the top of every docs test, we should not remove the dev dep.

**Comment by Manishearth** [comment]
Worth noting: I wrote an in depth explanation of how cyclic dev deps work and the different kinds of cyclic deps on that issue https://github.com/rust-lang/rust-analyzer/issues/14167#issuecomment-1864922655

**Comment by sffc** [comment]
Discuss with:

- @Manishearth 
- @sffc 
- @robertbastian

**Comment by Manishearth** [comment]
Is there still something to be discussed here?

Strawman proposal:

 - We remove the usage of anything cyclic from unit tests. Unfortunately this cannot be easily enforced but we may be able to make it stop working upstream in the long run.
 - Integration tests, doctests, and examples are allowed to be cyclic, as this is an explicit and intentional design of Cargo.

**Comment by sffc** [comment]
Given that "no cyclic deps in unit tests" can't be easily enforced, I'd be happy with a conclusion that we will accept PRs to remove that type of cyclic dep when they cause problems, but not try to systematically enforce that style.

I guess we're not going to be removing the `icu` and `*_derive` cyclic dev deps anytime soon, which means I'll need to live with the rust-analyzer error until it gets fixed by them.

**Comment by Manishearth** [comment]
That's a conclusion I support.

There seems to be movement on the rust-analyzer side especially after I explained that the problem shouldn't be intractable for integration tests.

**Comment by sffc** [comment]
I don't think there's any action needed on this issue, then, so closing it.
