### ISSUE TITLE
Test on beta instead of nightly

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4611]
We've had three issues with nightly over the last week, all of which require work on our end. I don't think it's our job to provide a canary for the Rust project. We should test beta, which is a more mature pre-release that is actually intended for third parties to test with.

**Comment by robertbastian** [comment]
https://stackoverflow.com/a/70746297

**Comment by sffc** [comment]
- @sffc - Beta gives 6 weeks; there is more time to fix bugs in Nightly
- @robertbastian - The expected time for problems on Nightly is 9 weeks
- @Manishearth - It's easier to get things fixed in Nightly than Beta, and we get dangerously close on Beta to running up against deadlines
- @robertbastian - Don't we get tested on Crater?
- @Manishearth - Yeah but they might not test all of our configurations
- @sffc - Given our position working fairly closely with the Rust team, thanks to @Manishearth, I'm fine sticking with the `nightly` channel, but I see the case behind moving to `beta` and we could consider doing it in the future
- @robertbastian - These nightly failures are very noisy; this week there have been 3 failures and they are all in our dependencies.
- @Manishearth - Mostly because the dependencies are using antipatterns, and I'm advocating for those crates to stop using these antipatterns. I also feel that dependencies are kind-of your responsibility so you should care if dependencies start failing.
- @Manishearth - We could consider turning off nightly CI for datagen, since we don't care as much about datagen deps.
- @robertbastian - People generally don't need to build icu4x on nightly. They need to build the library on nightly for targeting weird platforms.
- @Manishearth - There might be cases where clients use nightly for their own reasons. For example, servo has one toolchain and they use nightly.
- @sffc - Can we test on nightly -7 days?
- @Manishearth - Doing a rollback PR on the same day is easier.


Proposed solution:

 - We care about ICU4X itself building on nightly
 - We care much less about datagen building and running on nightly, but will still test it
 - We add a CI daily cronjob for latest beta which reports to the main channel. Failures on this cronjob should be fixed promptly.
 - The :sob: robot reports to a different channel for nightly. Failures on this cronjob should be monitored.

LGTM: @Manishearth @sffc @robertbastian @younies
