### ISSUE TITLE
Migrate data structs to icu_pattern in 2.0

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5256]
Now that we have `icu_pattern`, we should migrate more components to use it where possible. Candidates:

1. `icu_decimal` (related: #4437)
2. `icu_list`
3. Anything sitting around in `icu_experimental` that hasn't been migrated yet (not a 2.0 blocker)
4. _Maybe_ `icu_datetime` but that will require more surgery and might not be worth it
5. Others?

CC @robertbastian

**Comment by robertbastian** [comment]
`icu_list` has a couple of invariants that are not available on `icu_pattern`, specifically that `{0}` and `{1}` have to appear in that order, and that nothing can precede the `{0}` (end and middle patterns) or follow the `{1}` (start and middle patterns). These invariants allow taking substrings of the patterns to be stitched together, instead of creating a massive tree of `Writeable`s, which I think is more efficient.

**Comment by sffc** [comment]
Nested writeables can usually be composed in such a way that it should be equivalent to a loop when unrolled, but I agree it can be tricky to get to that point.

The list data struct could apply the additional invariants during deserialization.

The main thing we want for 2.0 though is to evaluate the cases and make an educated engineering decision that certain things are too much work / infeasible / lacking in ROI. I'm okay making such a determination for ListFormatter data.

**Comment by robertbastian** [comment]
> The list data struct could apply the additional invariants during deserialization.

Then I'm basically writing a new pattern type. As I already have a pattern type I don't see what the upside would be.

**Comment by sffc** [comment]
Closing this because all work is tracked elsewhere
