### ISSUE TITLE
Add JSON Schema or similar mechanism for data struct stability

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#538]
We should perform data-driven stability testing of data structs. I think the best way to do this would be to introduce JSON Schema declarations for each versioned struct, which would be tested against the serialized form of the structs.

JSON Schema will work for the human-readable form, but we should also think about how we can go about testing the machine-readable (Bincode) form.

Related: #523

Suggested task list:

- [ ] Review the problem space in ICU4X
- [ ] Research a tool that can represent everything that we store in ICU4X data structs (perhaps JSON Schema or perhaps something else)
- [ ] Decide how and where to save the schema files in the ICU4X repository (perhaps somewhere under FFI?)
- [ ] Implement the actual test

**Comment by gregtatum** [comment]
JSON Schema: https://json-schema.org/
Here's a random rust implementation: https://github.com/Stranger6667/jsonschema-rs

**Comment by sffc** [comment]
The FFI code could also help enforce stability.

**Comment by sffc** [comment]
We should prioritize this for 1.0.

**Comment by sffc** [comment]
Discussion: We may take a different hash-based approach.

**Comment by Manishearth** [comment]
(I've got WIP for this)

**Comment by Manishearth** [comment]
I've marked https://github.com/unicode-org/icu4x/pull/1772 as fixing this, but it's not _quite_ doing the thing mentioned in the issue. I'm happy to mark it as not entirely a fix, however.


https://github.com/unicode-org/icu4x/pull/1772 basically adds a sha2 fingerprint for each key/locale combo, so it's possible to quickly check what has changed for a given git log. This will also change when _data_ changes (even if the format doesn't), so it'll be noisier than the perfect case, but probably still workable.

A way to avoid this changing on data changes would be to figure out a way to get schema information.  This can't be its own custom derive; serde has its own simpler type system, and dependencies may have custom serde impls for things that map types to others (e.g. it's very common for tuple structs to be transparent in serde-land). This _could_ use the same kind of library from #1775: the main downside is that anything in this space would still operate on _values_, not _types_, so `Some(4)` and `None` are different "types" according to serde. This complicates things like sequences to boot: What's the type of `.serialize_seq([Some(1), Some(1), None, None])`? What if the Options are further down the tree inside a sequence? What about other situations where different serde "types" are produced based on runtime data? We do something like this in the human readable deserialization of litemap and zeromap. We could just serialize it as a sequence of schema elements, at least that will be easier to spot-check, but we'll still have spurious diffs whenever the shape of sub-data changes.

Furthermore, any serde-based solution won't be able to notice ULE impl changes since zerovec sits entirely outside of serde's type system: on binary serialization formats, serde just sees byte buffers.

@sffc and I discussed this and the general path forward that we see is that we wait for data-driven testing (https://github.com/unicode-org/icu4x/issues/51, planned to happen this quarter hopefully), and have a CI job that's able to run an older instance of ICU4X on newer data. (The reverse is trickier; since tests may have been added)


I think schema-fingerprinting is still something potentially useful, but the main challenge is going to be "merging" different entries of different type. I do have some ideas for this but it kinda turns into a major project of its own. Might experiment with this at some point.
