### ISSUE TITLE
UTC vs GMT

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#5497]
> UTC has been widely embraced by most countries and is the effective successor to [Greenwich Mean Time](https://en.wikipedia.org/wiki/Greenwich_Mean_Time) (GMT) in everyday usage and common applications.

- [Wikipedia](https://en.wikipedia.org/wiki/Coordinated_Universal_Time#cite_note-2:~:text=UTC%20has%20been%20widely%20embraced%20by%20most%20countries%20and%20is%20the%20effective%20successor%20to%20Greenwich%20Mean%20Time%20(GMT)%20in%20everyday%20usage%20and%20common%20applications.)

Yet ICU4X uses GMT, both on APIs (`icu::timezone::GmtOffset`) as well as in output (`"GMT-05:00"`). The latter is dictated by UTS 35, which seems to have historically used GMT, but currently uses GMT and UTC [interchangeably](https://unicode.org/reports/tr35/tr35-dates.html#Time_Zone_Format_Terminology:~:text=%22PDT%22%20(short)-,Localized%20GMT%20format,-%3A%20A%20constant). Unfortunately CLDR data has fields like `gmtFormat` (instead of a more neutral `offsetFormat`), which naturally result in values like `GMT{0}` instead of the more appropriate `UTC{0}`.

I do want to address this on the CLDR level, but this issue should discuss updating IUC4X APIs to use the more appropriate UTC. IXDTF and ISO 8601 also use "UTC offset" terminology, which already appears in ICU4X as well (e.g. through the beautifully named `GmtOffset::try_from_utc_offset_record`).

My concrete proposal for ICU4X is:
- Rename `GmtOffset` -> `UtcOffset`
- Rename datetime APIs like `NeoTimeZoneGmtMarker` to a more neutral `NeoTimeZoneOffsetMarker`, but document it as "UTC offset"

**Comment by robertbastian** [comment]
More from Wikipedia:

> On 1 January 1972, GMT as the international civil time standard was superseded by [Coordinated Universal Time (UTC)](https://en.wikipedia.org/wiki/Coordinated_Universal_Time), maintained by an ensemble of atomic clocks around the world.

> The term "GMT" is also used as [one of the names](https://en.wikipedia.org/wiki/Western_European_Time) for the [time zone](https://en.wikipedia.org/wiki/Time_zone) [UTC+00:00](https://en.wikipedia.org/wiki/UTC%2B00:00)

> English speakers often use GMT as a synonym for UTC.

> The term "GMT" should thus not be used for purposes that require precision.

**Comment by sffc** [comment]
- @sffc - I agree that we should probably use UTC more consistently. Is there a risk that CLDR adds different transliations for UTC?
- @robertbastian - UTS 35 already uses them interchangeably
- @hsivonen - UTC has leap seconds, and software doesn't typically handle them.
- @robertbastian - It's correct for time zones because time zones are defined in terms of UTC, not GMT. And we're not doing maths, we're just displaying things, so leap seconds don't really matter
- @nekevss - Typically I prefer UTC, but I understand if you want to align with CLDR
- @robertbastian - For some things, we should just use "offset", not "GMT offset".
- @sffc - Should we name the struct just "Offset" or maybe "ZoneOffset"?
- @robertbastian - It _is_ the UTC offset in this context.
- @nekevss - Do we care about the difference between -0 and +0 in the `UtcOffset` type?
- @robertbastian - Sounds like a parsing thing
- @sffc - I also think it's an IXDTF thing
