### ISSUE TITLE
Publish env_preferences?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5869]
Currently it is marked as `publish = false`. Is this intentional?

CC @robertbastian @zbraniecki @ashu26jha

**Comment by zbraniecki** [comment]
yes

**Comment by Finchiedev** [comment]
I'd like to publish a crate that integrates `env_preferences` - would it be possible to publish the current version, possibly in a similar way to `icu_experimental` where it is clearly marked as unstable and subject to change? I'm also very happy to help resolve any blocking issues if needed :)

**Comment by robertbastian** [comment]
Yes we can publish a 0.1.0 if you need it.

**Comment by sffc** [comment]
Discussion in the ICU4X WG meeting:

- @robertbastian I think the only open question is the name, but I don't care if we rename it in the future and keep env_preferences at 0.1.0. We don't have a better solution for utils
- @sffc We've renamed crates before, it's just a little unfortunate when people find the old crates on crates.io and think it is the new crate
- @robertbastian We have a our graveyard crate which we can push over it. We have some existing crates we haven't pushed graveyard releases for, yet.
- @sffc Yeah, like `icu_locid`.
- @sffc I'm not sure if I like `env_preferences` but it seems _fine_, and I'd rather unblock @finchiedev than spend another few weeks bikeshedding this.

**Comment by Finchiedev** [comment]
Thank you all very much! Just to clarify, this is not an immediate blocker, so please don't feel any need to rush for my sake! I might throw some suggestions into #6821 as well :)

**Comment by Manishearth** [comment]
ICU4X WG meeting discussion:

- @Manishearth Proposed conclusion: Name is fine for now.  Can always rename. Release whenever @Finchiedev thinks it is appropriate.
- @hsivonen How complete is this for loading things like LC_COLLATE? I see that there is platform-specific code on Windows the last time I looked.
- @manishearth seems to be able to fetch the value but not do anything for it
- @sffc There was an open question of how we should name the crate. We could change it later, but it's been a bit of a pain point when we've renamed crates. It's _nice_ to have the right name on the first try.
- @Manishearth Are there release blockers?
- @hsivonen Looking at the code there seems to be some stuff not yet exposed
- @hsivonen It would be nice for the coreutils project to be able to use this; it's not clear that the crate is at that point, yet
- @manishearth it's not, but it's not a release blocker.
- @sffc If Finchiedev, the largest recent contributor, thinks that the crate has enough features to be useful, I think we should release the crate (as 0.1).
- @sffc We should collect ideas for a name, have a ballot, and then decide.
- @hsivonen The crate [sys-locale](https://lib.rs/crates/sys-locale) does some of this.

Name ideas:
- `env_preferences`
- `system_locale_preferences`
- ?

Next steps: Bikeshed name. We are probably ready for a release after that.

@zbraniecki @Finchiedev @robertbastian please add name suggestions if you have any!

**Comment by robertbastian** [comment]
* icu_locale_sys

**Comment by zbraniecki** [comment]
* `icu_platform_preferences`
* `icu_host_preferences`
* `icu_runtime_preferences`

**Comment by Manishearth** [comment]
Names:
 - env_preferences
 - system_locale_preferences
 - icu_locale_sys
 - icu_platform_preferences
 - icu_host_preferences
 - icu_runtime_preferences


Discussion:
 - @robertbastian: DOn't see the urgency
 - @sffc 2.1 release?
 - @hsivonen Ubuntu is going to use uutils in their next release. Should I ask sylvestre if a release would be useful? They use ICU4X. They need this eventualyl I don't know what they do now. 
 - @sffc My impression is that it's good enough for a 0.1 release
 - @manishearth not the best most polished crate rn, but it's quite decent. Releasing gets us users, which means we can finish that last set of polish based on user needs.
 - @zbraniecki Would prefix with icu_ 
 - @zbraniecki If I saw env_preferences, i would imagine it is all prefs not just i18n prefs, like architecture stuff etc. So we should say that this is somehow intl prefs.
 - @zbraniecki Wouldn't mind taking a week to review docs and api and suggest cleanups
 - @manishearth I agree, Robert's proposed `icu_locale_sys` seems nice. Or `icu_sys_locale`. 
 - @zbraniecki Sounds narrow to locale.
 - @sffc preferences are in the icu_locale crate.
 - @sffc icu_locale_sys goes well with icu_loclae_core, icu_locale_fallback, etc.
 - @sffc If preferences had ended up being its own crate this would be icu_preferences_sys, but they are in locale, so perhaps this should be icu_locale_sys
 - @manishearth everything that is a preference is sufficiently locale-like that it won't be confusing
 - @zbraniecki yeah... okay with assuming preferences are locale like
 - @nekevss Is the icu4x dependency feature flagged? It should be so people can get the raw APIs if they want.
 - @Manishearth I think it should be but doesn't have to be for 0.1
 - @zbraniecki Seems useful to have the raw APIs
 - @nekevss I have to check the ECMA spec. But if this pulls system locales from Boa, i'd prefer to depend on this. The only way to fetch timezones is iana timezone and I don't know how I feel about that crate.
 - @sffc timezone fetching is a non-locale thing
 - @manishearth maybe icu_sys
 - @sffc -sys has an existing meaning in rust
 - @manishearth system?
 - @zbraniecki system makes me think FFI.
 - @nekevss I mentally model sys as being system access.
 - @manishearth in APIs it's one thing, in crates it means C wrapper.
 - @zbraniecki I like env. But it strongly indicates environment. End result isn't quite that. Maybe imply host?
 - @hsivonen +1 host. Env is maybe too suggestive.
 - @Manishearth: how does everyone feel abouit `icu_host_preferences`
 - (general positive sounds)
 - @sffc would like env, icu_env or icu_host
 - @manishearth `icu_host` sounds like a server
 - @zbraniecki To brainstorm more: when you have more layers (...)
 - @sffc TimeZone isn't a preference, preference means somethng specific.
 - @hsivonen icu_host_settings?
 - @nekevss It's a utils crate you don't have to worry abotu the namign conflict if you don't have the prefix.
 - @sffc I think this should eventually be in the ICU metacrate, average user just wants to do `icu::something` to get the host locale. 
 - @sffc We don't use underscores in module names, so `host_preferences` should be smushed into a single token
 - @Manishearth I don't think we made that decision in general
 - @hsivonen Agree with zibi, folks will look for crates that start with icu. We should do a crate name that starts with icu. `icu_host_settings` is fine. We have `icu_harfbuzz` already. I would like us to have `icu_sqlite`.
 - @zbraniecki Mental model is we have 3 bits to encode into it. We want to say it is i18n. We do not wish to claim we are collecting _everything_: just i18n stuff. Second is we are collecting settings/prefs. Third is that they are locale specific. That naturally lands into the three bits. We don't have to use icu but then we should use intl or internationalization. Would be okay with `icu_host_info`, loosens the idea that the end user is setting it in prefs. If this crate would retrieve the current OS last fallback locale, that is not a setting. Could see this being `info`. One day we may even want people to be able to set these things.
 - @manishearth I think we made the smushcase decision for datetime and timezone.
 - @manishearth I don't think this should be in the metacrate, I'm wary of having non-algorithmic stuff in the metacrate. The moment an algorithmic crate has systemish depednencies i get more wary.
 - @sffc This is the first question I get asked
 - @sffc `icu::host::locale()` is clean and discoverable. It's the first question we get asked as an i18n library. It is a problem we should embrace.
 - @Manishearth Features don't solve it since it's harder to trust feature resolution to not accidentally pull something in and break the build. We've had this problem before but it's mostly an "ah darn we have an extra dependency" problem not a "ah our extra dependency broke our build".
 - @manishearth I find `icu_host` is very servery.
 - @zbraniecki `icu_host` sounds like it sets a host. `icu_host_info` or `icu_host_settings` seems okay. I think this is an important question and the way ICU4C models it is harmful since it's not clear where it comes from. Making it explicit is good. But I think we should avoid saying that you can use all of ICU4X until you get here, and then you need to figure it out on your own.
 - @nekevss In general this crate feels like t has two functionalities: it's being specifically scoped to i18n, which I totally understand, but the raw info side there's no harm if someone wants to add non-i18n prefs. Like a light mode/dark mode pref. Gating a host preference/env preference, but if someone wants to contribute more, you're potentially losing out on a realm for easy adoption "oh i need light mode and i18n and it's all in the same deptree". Fine to 100% scope it ICU. I think there's a world where there could be a more raw low level crate with a larger potential scope but we don't have to.
 - @nekevss Was very annoyed at timezone libraries all packaging their own tzdata loading instead of there being any raw library. Ends up with people recreating crates
 - @sffc `icu_host_info` seems fine to me. Don't share the opinion that `icu_host` means server in my experience. Maybe `icu_hostinfo`.
 - @hsivonen If you put those words together they do become a term of art that is not what we mean here. I agree with what Manish said that it's aluable that we're not scary: we provide this functionality but we make it clear whether someone has opted in. Would prefer this to be "include this crate in your deps". But then I don't see the appeal of the metacrate anyway.
 - @zbraniecki I want to say I don't want it to collect everything. I think it should go into a separate theme_host_preferences crate. Theme, font, etc shoudl go into a different place, so you don't pull the whole world in. I don't think that should be this crate.
 - @Manishearth If we need to we could splti to host_preference_raw later.
 - @manishearth the core_foundation_sys dep is a problem
 - @zbraniecki will take some time to look at the crate/name
 - @sffc We can decouple the metacrate decision for now. I think calling it `icu_something` is good. We could technically do `icu::host::` even with `icu_host_info`.
 - @Manishearth Is there a reason to prefer "info" over "settings"?
 - @sffc The important word is "host". Adding "info" is a filler word. I don't think I want to spend the word "settings" here.
 - @robertbastian "info" is broader than "settings"
 - @zbraniecki Some things may not be settings. I'm not sure if that applies to the settings accessible from this crate. Hmm, if an OS has multiple supported LLMs, that is host information, not host settings.
 - @sffc If we want a filler word, `icu_host_util` or `icu_hostutil`
 - @hsivonen No on utils
 - @sffc We agreed for time zones that in types, we use camel case `TimeZone`, methods snake case `time_zone`, and modules concatenated case `timezone`. So this would imply that "host info" should be stylized as `hostinfo` in module (and crate) names.
 - @manishearth timezone and datetime are syntactically a noun adjunct and a noun, but are terms of art / atoms. A time zone is not a zone of time as much as it is its own thing. Having smoosh for them is fine; but overall we should use underscores consistently. So our default policy is underscore splitting, and exceptions can be made if someone wishes to argue that something is a term of art that behaves like its own word.
 - @hsivonen `hostinfo` is the DNS atom, and our host info is not the same atom.
 - @sffc ok

Conclusion: `icu_host_info` as a name. No decision on metacrate presence, to be figured out eventually.

LGTM: @Manishearth @robertbastian @zbraniecki @hsivonen @sffc

Conclusion: If this goes in the metacrate, it can be called `icu::host_info`.

LGTM: @Manishearth @sffc @hsivonen @zbraniecki @robertbastian @nekevss

**Comment by hsivonen** [comment]
I noticed that #6574 remains open even though it seems to be of importance for this the practicality of using this crate on Linux.

**Comment by sffc** [comment]
More WG discussion:

- @zbraniecki I was trying to look at what we're trying to accomplish. It works across different OSes. I'm using DTF as an example. I'll share my screen.
- @zbraniecki I was unsure about whether to return strings or ICU4X enums. In general I'm returning enums, but I also have multiple functions so you can pick the type you want.
- @zbraniecki Mostly I'm unsure about the time zone. Currently I have a new type `RawTimeZone` with two variants, Iana and Windows, and let the user parse it themselves. It's not clear if I even need Windows any more; it seems like I usually get IANA even on Windows.
- @robertbastian Crates like Jiff already do the system time zone. I don't know if we can do much with it in this crate.
- @zbraniecki We still need it for populating `-u-tz`, unless we just say we don't populate that subtag.
- @robertbastian We could, at best, check that it matches.
- @zbraniecki ...
- @hsivonen On Linux, are you doing the thing where if the POSIX locale says the locale is C, you parse the relevant environment variable yourself? Because we can't do the API call that asks the system to do the parsing because it isn't threadsafe.
- @zbraniecki I know you flagged this to me. I haven't goten to it yet.
- @hsivonen Regarding the time zone, just from a "what host info exists" and "what things i18n in general deal with" perspective, it seems strange if we don't have a way to query for time zone. If our position is "use Jiff for that", does Jiff do it correctly across all platforms?
- @robertbastian Yes. And actually the important part is getting the system TZDB even more than the system time zone. We've decided to use other crates for this.
- @hsivonen Are you retaining the collation things that finchiedev added?
- @zbraniecki Still working on it. (zbraniecki and hsivonen discuss how to set and retrieve the settings)
- (additional discussion about retrieving regions)
- @robertbastian You depend on the datetime crate behind a feature. What's the advantage to this instead of parsing to a locale and then to the preferences?
- @zbraniecki We might have preferences we can't express in the locale, like date formats.
- @robertbastian OK. If you add a preference for the pattern, for example, it would need to live in either `locale_core` or `datetime`. It can't live in `locale_core`.
- @zbraniecki I think it should live in `datetime`.
- @robertbastian My suggestion was to move the `DateTimePreferences` struct into the `locale_core` crate.
- @sffc This is a good discussion to have. I think we can decouple it from releasing 0.1 of `icu_host_info`.
