### ISSUE TITLE
Implement catalog Unicode properties like enumerated properties

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#589]
Catalog Unicode properties behave more or less like enumerated properties -- there is no practical difference.  Therefore, we should include those in the PPUCD parser and in data provider ResourceKeys and Rust enums.

**Comment by markusicu** [comment]
Yes. In ppucd.txt:
```
property;Catalog;age;Age
property;Catalog;blk;Block
property;Catalog;sc;Script
```
In https://www.unicode.org/Public/UCD/latest/ucd/PropertyAliases.txt :
```
# ================================================
# Catalog Properties
# ================================================
age                      ; Age
blk                      ; Block
sc                       ; Script
```
Documentation: https://www.unicode.org/reports/tr44/#About_Property_Table
- Catalog properties have enumerated values which are expected to be regularly extended in successive versions of the Unicode Standard. This distinguishes them from Enumeration properties.
- Enumeration properties have enumerated values which constitute a logical partition space; new values will generally not be added to them in successive versions of the standard.

So... no practical difference for users of properties. Some properties are expected to get new enum values in every major Unicode version, and others may or may not get new ones.

I would prioritize:
1. Script is one of the most useful Unicode properties.
2. Block is popular but often misunderstood and mis-applied. It is mostly an artifact of how the UTC plans and uses the Unicode code space. For example, many blocks include unassigned code points, and several scripts have characters in multiple blocks.
3. Age can be useful for limiting something to not-the-latest-and-greatest Unicode characters, for example to let fonts catch up.

See `UAX #44` for details.
We could ask @macchiati for an opinion, too.

----
Note that there is also a Script_Extensions property. It is “Miscellaneous” because its values are *sets of Script values*. An example from https://www.unicode.org/reports/tr18/: `\p{scx=Kana}` -- “The match is to all characters whose Script_Extensions property value *includes* the specified value(s). So this expression matches U+30FC, which has the Script_Extensions value {Hira, Kana}”

I would prioritize Script_Extensions over Block.
