### ISSUE TITLE
LineSegmenter skips breakpoint when there is a colon

### ISSUE THREAD

**Issue by Loirooriol** [unicode-org/icu4x#5918]
Maybe I'm misunderstanding something, but shouldn't both of these produce the same result?

```rs
println!("{:?}", LineSegmenter::new_auto().segment_str("a :b").collect::<Vec<_>>());
// [0, 4]
println!("{:?}", LineSegmenter::new_auto().segment_str("a _b").collect::<Vec<_>>());
// [0, 2, 4]
```

See https://github.com/servo/servo/issues/34657 for reference.

**Comment by sffc** [comment]
@aethanyc @makotokato @eggrobin

**Comment by eggrobin** [comment]
> shouldn't both of these produce the same result?

No they shouldn’t. line breaks are prohibited before colons, see [LB15d](https://www.unicode.org/reports/tr14/#LB15d) and the description of class [IS](https://www.unicode.org/reports/tr14/#IS).

This is has been the case in the line breaking algorithm for twenty-five years, and it is by design, because French (and related typographic traditions) use spaces before some punctation but do not allow for line breaks there.

**Comment by Loirooriol** [comment]
OK, thanks. Then I need to investigate why web browsers allow a line break in `<div style="width: 0px">a :b</div>`.

**Comment by eggrobin** [comment]
> Then I need to investigate why web browsers allow a line break in `<div style="width: 0px">a :b</div>`

@loirooriol, I think I can provide some background here. Internet Explorer does (well, did) not allow one, because Michel Suignard (who designed the line breaking algorithm in 1999) made sure it did not.
Chrome does because they are stuck with a poorly thought-out optimization. I figured out whom to reach out to to get that fixed, and I intend to help fix it soon, see the discussion in https://issues.chromium.org/issues/40851484.
