### ISSUE TITLE
Add and use BCP-47 time-zone identifiers in TimeZonesProvider

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#606]
Right now we are using the full IANA-style time-zone IDs from CLDR.

We would like to move toward using the [BCP-47](https://github.com/unicode-org/cldr/blob/90aaf561d1827ce06b1e9c4173a70c018665c7d2/common/bcp47/timezone.xml) identifiers so that we can store the time-zone IDs as TinyStrings. 

Depends on
* #562

**Comment by sffc** [comment]
Blocked on #562

**Comment by dminor** [comment]
@nordzilla  We plan to release 0.3 in about 3 weeks. Do you expect this to be unblocked in time for the 0.3 release, or should we punt to 0.4?

**Comment by sffc** [comment]
We have not documented the reasons why we need this.  Here is the motivation:

1. Shorter strings means smaller data size.
2. Fixed-length strings means we can stack-allocate time zone identifiers.
3. Using a BCP47-compatible identifier means we can consider breaking the time zone data down using the `-u-tz` extension during vertical fallback.

A note on data size: much of the benefit of data size can be realized by using a hashing algorithm instead of the BCP47 strings.  We prefer BCP47 because:

1. Strings are hand-curated to be human readable and prevent collisions
2. The data file is more readable
3. Simpler code / easier to maintain; no dependence on a proprietary hashing algorithm
