### ISSUE TITLE
Investigate why clippy CI isn't failing

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#643]
See #642.  There were over 300 clippy warnings, which accumulated over some time, but CI failed to flag them.  Figure out why it isn't being flagged.

CC @zbraniecki @echeran @gregtatum

**Comment by sffc** [comment]
Make sure Clippy is on stable.

**Comment by sffc** [comment]
CC @Manishearth

**Comment by echeran** [comment]
I'm having trouble with something that could be related. 

I started off removing the option `-Aclippy::unknown-clippy-lints` from `.cargo/config.toml` and the CI workflow yaml in order to see if I could trigger some nightly-version clippy errors. And that seems to be how this issue started -- we may want to run nightly clippy locally but still only want to use stable clippy in CI.

But before getting to that, it seems like there's some "sticky" or caching behavior going on that was causing some confusion. If you first run `cargo clippy-all`, you'll get several of these warnings:
```
warning: lint `clippy::unknown_clippy_lints` has been removed: this lint has been integrated into the `unknown_lints` rustc lint
  |
  = note: requested on the command line with `-A clippy::unknown_clippy_lints`

warning: 1 warning emitted
```
But even after changing the alias for clippy-all in `.cargo/config.toml` to remove `-Aclippy::unknown-clippy-lints`, running `cargo clippy-all` still gave me those above warnings.

I suspect that there's some strange caching going on with cargo and the aliases defined in `.cargo/config.toml`. Does that make sense? Does that explain the mismatch of local & CI clippy behavior?

According to the warning, if we want to compile code that allows nightly lints (unknown to stable), would we have to make all our `rustc` commands use `-A unkown-lints` if that's [the option](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unknown-lints) that controls the lint level of new lints from nightly?

**Comment by sffc** [comment]
I noticed that `-D warnings` was removed here; why?

https://github.com/unicode-org/icu4x/commit/ae89da479dfbbcfc73fbaa977cd3f4ecfd0e4fac

**Comment by sffc** [comment]
Note that now that we have a stable Rust version, we shouldn't have the problems we were having before with Clippy passing and failing differently on different Rust versions.
