### ISSUE TITLE
[locale] Potential parsing optimization based on subtag length

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#71]
In the #43 I was able to improve the parsing performance by ~24% by separating length measuring and returning `Err` before I parsed the subtag into a `TinyStr`.

The reason it works so well is because in multiple places we use parsing to test if a subtag is of a given type, but in most cases we can learn it just from the length of the subtag.

A potential optimization may be to either separate length measuring in the parser (so, take the length, check if it's `2..=4` and if not don't even try to parse as X) or even add an internal constructor that takes a length (`from_bytes_with_length`) so that you measure the length of the subtag once.

Depending on the cost of constructing the `Result::Err` and the cost of taking the `len` of a subtag (we do this per `from_bytes`) we may get additional wins there.

**Comment by nordzilla** [comment]
It looks like there is a very small optimization that can be made in the `Language::from_bytes()` function by returning an `Err` if the length is not valid _before_ creating a `TinyStr` and checking `is_ascii_alphabetic()`. 

I think that separating the length measuring in the parser outside of the individual `from_bytes()`  functions, and introducing `from_bytes_with_length()` functions will not yield any performance improvements.

Calculating the length of a slice is not an expensive operation since slices store their length and cannot change size; the length of a slice is always known absolutely. If anything, adding a `from_bytes_with_length()` function may just add extra overhead in terms of having an extra parameter, as well as adding more code to maintain.

I will submit a PR with the small optimization to the `Language::from_bytes()` function.
