### ISSUE TITLE
Diplomat: Investigate using Rust as a transpilation source

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#74]
The "X" part of ICU4X is still not fully defined.  WebAssembly has been tossed out as one potential solution (main issue: #73).  However, we should also investigate other approaches.  One of those approaches could be treating Rust as a source language for transpilation.

Rust has certain advantages to serve as a source language for transpilation:

1. To transpile to most other languages, you need to "remove" things (lifetimes, etc) rather than add things.  The high amount of static analysis that can be done on native Rust is a treasure trove of information to use Rust as a source for transpilation.
2. Since we are writing Rust from scratch, we can write it in a way to be "transpiler-friendly": for example, abstracting out standard library dependencies.

Obviously, the big hurdle is that we would have to figure out how to write this Rust transpiler, which, as far as I can tell, does not exist yet.  For both Lisp and Rust, since these are uncommon languages at Google, it is uncertain whether we could find another team who would have the expertise to own the project.

However, given the strong community around Rust, I have a bit of hope that if we (at Google and Mozilla, two industry leaders) were to write such a tool, that it would obtain community adoption and be used in other projects.

**Comment by hsivonen** [comment]
In the case of Java, the main benefit I see with transpilation from Rust to Java as opposed to translating Wasm into Java byte code (which I expect @hagbard to be able to opine about given the latest commit at https://github.com/cretz/asmble/ ) is that the former could read from a `java.lang.CharSequence` and write to a `java.nio.CharBuffer` without dropping to the byte level in between. (Assuming that ICU4X internals stay in the kind of code that doesn't try to view a `&[u16]` as `&[u8]`.)

**Comment by hagbard** [comment]
Yeah, you'd almost certainly win for anything String related. WASM just can't "cast" char[] as a byte[], because that's not permitted in the spec, so it would be forced to copy.

I mean if we have evidence that for clients the performance is fine, then maybe, but it'll always be slower than JVM code running normally (and amenable to normal JVM hotspot compilation). WASM on JVM feels like an abstraction too far for me.

There are some "unsafe" APIs via sun.misc, but I've not seen any of those that could to things like convert arrays in-place (specifically an array stores the header and contents in a contiguous block, so having two arrays of different type pointing to the same memory is, I think, impossible).

**Comment by hagbard** [comment]
Oh, and as regards transpilation, it's not obviously clear that going from Rust to Java is going to be reasonable, since idiomatic Rust will aggressively "allocate" things (on the stack) because it's all basically free. You might end up with code that churns a lot of unnecessary GC allocations if you aren't careful. The whole idea of GC <-> non-GC conversion is a bit fraught, but probably doable with care.

**Comment by echeran** [comment]
I suppose the first consideration is if the Rust source->AST functionality is exposed publicly.  IIRC, that part of rustc is still private, but I don't remember if there are ongoing moves to refactor it out and make it public. @Manishearth would know better, of course.  

On a related note, I saw news of [rust-analyzer](https://rust-analyzer.github.io/blog/2020/04/20/first-release.html).  By "analyzer", I'm assuming it's a tool that does both source->AST conversion and adds static analysis information (I used [clojure.tools.analyzer](https://github.com/clojure/tools.analyzer) in my exploration of a Lisp impl for #1 ).  It looks like rust-analyzer is initially focused on IDE concerns, but the important part is that it is standalone, and thus reusable.  FWIW, judging by [HN comments](https://news.ycombinator.com/item?id=22995466), it has praise, but it is also very much alpha by its own admission and doesn't yet utilize rustc.  Does anyone have more insight on rust-analyzer and other tools?

Based on my experience, I'd suggest a [multi-pass design](https://youtu.be/Os7FE3J-U5Q) because it encourages simplicity as the opposite of having separate transformations unnecessarily complected together.  The naive design of my exploratory work was source (strings) -> analyzer output (AST+info) -> target (strings), so internal things like traversing the AST+info and distilling a subset were intertwined with target-language specific transformations as well as target-language string generation.  There's too much incidental complexity for that to be a sustainable design.

I would also suggest not just seeing the AST solely as a tree (ex: traversing using a tree visitor pattern), but also from a different angle, as nested plain data, if possible -- this could enable you to make your lives easier when pulling off info from the AST by doing [clever pattern matching declaratively](https://github.com/noprompt/meander).

**Comment by Manishearth** [comment]
Rust source->AST is typically done with the [syn](https://docs.rs/syn/) crate. It's how proc macros are typically written.

> doesn't yet utilize rustc

I believe this is deliberate, rust-analyzer is designed to have a more on-demand architecture. The previous attempt at IDE stuff used rustc and had problems because of that.

rust-analyzer is IDE-first but it's very much intended to be a general analysis tool.

**Comment by sffc** [comment]
Backlog for the time being; revisit early in Q3.

**Comment by filmil** [comment]
What's with all the notifications?

F

**Comment by sffc** [comment]
I decided to reopen all backlog issues to make them more discoverable by external contributors.  See #224

**Comment by Manishearth** [comment]
This happened, we use diplomat now
