### ISSUE TITLE
Figure out documentation story for C++ bindings

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#781]
We should probably start with something using doxygen, but eventually we'd like to use ReadTheDocs or something. There are plugins to make RTD consume doxygen.

**Comment by Manishearth** [comment]
Tool suggestions welcome!

**Comment by sffc** [comment]
2021-06-10:

- @mihnita - for C++ the only story in town is Doxygen; I'm familiar with how it works since we parse it in Okapi (as a file format to localize)
- @sffc - there are two decoupled questions: the syntax of the docs, and the tool to generate HTML files
- @mihnita - having code docs is useful for IDEs, etc.
- @Manishearth - agreed

**Comment by Manishearth** [comment]
Multiple C++ folks I talked to said that Doxygen works poorly with post-C++03 code, and I should just directly use Sphinx: this means I have to duplicate some of the signatures in the docs but it's not that big a deal, Sphinx has native support for C++ (it just cannot pull docs from comments. this seems fine to me)
