### ISSUE TITLE
Create a Normalizer component

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#972]
As part of the requirements of #971, ICU4X will need a Normalizer. The documentation for the ICU4C Normalizer is available with the [C API](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/unorm2_8h.html) and [C++ class](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1Normalizer2.html).

There is no ECMA-402 normalizer.

/cc @hsivonen

**Comment by zbraniecki** [comment]
My hunch is that we should look for the smallest possible subset of the normalizer that would enable Collator work to enable ECMA-402 compatibility there.

I am unsure if it means we need 50/80/100% of the ICU Normalizer functionality.

**Comment by sffc** [comment]
The primary normalization algorithms are just NFD, NFC, NFKD, and NFKC, and it's all data-driven.  I don't anticipate that implementing any one of those normalization algorithms is substantially more difficult than implementing all four, but I could be wrong.

**Comment by hsivonen** [comment]
NFD normalizer data comes out as a side effect of the collator work. Exposing a normalizer API for NFD shouldn't be a big effort.

**Comment by dahosek** [comment]
NFD is the simplest of the normalizations to implement as it's all essentially a mapping of a codepoint to a sequence of codepoints (with Hangul decomposition able to be expressed by algorithm). NFKD is a sort of enhanced version of that (doing things like mapping Ⅺ to XI and ⑳ to 20).

NFC is a bit more complicated in that it's mapping sequences to characters and the mapping is recursive, i.e., if you have a sequence ABC and map AB to D, you cannot just proceed to C but must check first that DC doesn't have a mapping. I'm not sure if there's a requirement for backtracking, e.g., if AB↦D and CD↦E but CA does not map, are we required to do CAB↦CD↦E. I would suspect that this should never be the case. There is a specification that NFC requires NFD to be applied before composition.

NKFC is defined as NFKD+the composition for NFC.

**Comment by hsivonen** [comment]
For NFD, the data structure plan I have is:

`CodePointTrie` that maps characters to 32-bit integers such that:

1. The default value is 0 and signifies that the NFD form of the character is the character itself.
2. There are entries for all non-surrogate, non-Hangul syllable code points that don't decompose to themselves.
3. If both halves of the 32-bit value are non-zero, the decompositions consists of two BMP characters with those two values.
4. If the high half is non-zero and the low half is zero, the decomposition is the single BMP character represented by the high half.
5. If the high half is zero and the low half is non-zero, the low half pack bits for index, length, and whether at least one character in the decomposition is an astral one. If the astral bit is set, the index and length are for a table of 32-bit values. Otherwise, they are for a table of 16-bit values.

Additionally, I'm going to have a `UnicodeSet` of the characters whose NFD decomposition doesn't start with a starter.

I hard-code the expansion of the four decomposing non-starters (the deprecated COMBINING DIALYTIKA TONOS and the three special Tibetan compound vowels) in the loop that fetches characters that match the `UnicodeSet` into the reordering buffer.

I handle Hangul syllables algorithmically.

**Comment by tarekgh** [comment]
Just wondering, would it make sense bringing [IDNA](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1IDNA.html#abd9b7b1a0d474117bf254407a5751fdd) when bringing the normalization to ICU4X? It should be straight forward, and the benefit would be big.

**Comment by sffc** [comment]
The plan right now is to expose sufficient APIs from ICU4X to enable an external IDNA crate to be created:

https://github.com/unicode-org/icu4x/issues/42

**Comment by hsivonen** [comment]
#1706 now contains an NFD normalizer (not properly documented yet), because I needed to write one for the identical/fifth level of collation.

**Comment by hsivonen** [comment]
* NFD has landed.
* NFKD is in #1967.
* My current thinking of how to appoarch NFC and NFKC is in #1979.

> Just wondering, would it make sense bringing [IDNA](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1IDNA.html#abd9b7b1a0d474117bf254407a5751fdd) when bringing the normalization to ICU4X?

My current plan is to provide the part of UTS 46 "Processing" section that covers the "mapped" and "valid" parts of the "Map" step and the "Normalize" step via ICU4X's normalizer, but the caller would be responsible for performing the "disallowed", "ignored", and "deviation" aspects of the "Map" step as pre-processing before calling into the normalizer.
